// Code generated by protoc-gen-panel-typescript from v1/panel.proto. DO NOT EDIT.
//
// What every message of a response reads as: nothing set, a field this SDK does not know, and
// each field set alone, with each value of an enum, one no version has, and a zero where the
// server may send one. A block is one message, reached through the call that returns it: of a
// stream, as its first response. A stream's own response has no check of nothing set: that is
// a pulse, which streams.ts has.
import * as w from "../dist/wire/v1/panel_pb.js";
import { first, newer, reading, readingDetail, type Init } from "./harness.ts";
import type { Pethost } from "pethost";

// The call an error is read from: any will do, since every call fails the same way.
const anyCall = (api: Pethost): Promise<unknown> => api.getMachine({});

// What each message reads as when nothing is set in it: from a response, and from its JSON.
export const empty = {
  GetMachineRequest: () => ({}),
  GetMachineResponse: () => ({ projects: [], deletedProjects: [] }),
  Machine: () => ({ name: "", location: "", cpuUsedCores: 0, cpuTotalCores: 0, memoryUsedBytes: 0n, memoryTotalBytes: 0n, diskUsedBytes: 0n, diskTotalBytes: 0n, hostname: "", sshHostKeyFingerprint: "", sshKeys: [], backupsEnabled: false, snapshotListFailureMessage: "", backupRetentionHours: 0, acmeEnabled: false, appsDomain: "", daemonVersion: "", dockerVersion: "", sessions: [] }),
  MachineSession: () => ({ sessionId: "", projectId: "", service: "", port: 0, clientAddress: "", sshKeyLabel: "", sshKeyFingerprint: "" }),
  DiskUsage: () => ({ imagesBytes: 0n, volumesBytes: 0n, containerLayersBytes: 0n, projectFilesBytes: 0n, containerLogsBytes: 0n, httpTrafficBytes: 0n }),
  SshKey: () => ({ publicKey: "", label: "", fingerprint: "" }),
  GithubConnection: () => ({ appName: "", installUrl: "", repositories: [], repositoryCount: 0, webhooksEnabled: false }),
  GithubRepository: () => ({ repository: "", defaultBranch: "", private: false }),
  DeletedProject: () => ({ projectId: "", snapshotCount: 0 }),
  RunMachineActionRequest: () => ({}),
  RestartMachineAction: () => ({ atMaintenanceWindow: false, interruptOperations: false }),
  RunMachineActionResponse: () => ({}),
  ProjectMetadata: () => ({}),
  ProjectSummary: () => ({ projectId: "", problems: [], services: [], url: "", hosts: [], cpuUsedCores: 0, memoryUsedBytes: 0n, runningOperations: [], pinned: false, diskUsedBytes: 0n }),
  ServiceSummary: () => ({ service: "" }),
  ProjectProblem: () => ({ service: "", operationId: "", problemMessage: "" }),
  GetProjectRequest: () => ({ projectId: "", includeSecretValues: false, snapshotsVolume: "" }),
  GetProjectResponse: () => ({}),
  Project: () => ({ projectId: "", problems: [], url: "", cpuUsedCores: 0, memoryUsedBytes: 0n, deployId: "", xPethostAppliesAtOnce: false, services: [], volumes: [], routes: [], hosts: [], passwordProtected: false, operations: [], snapshots: [], snapshotCount: 0 }),
  RunningServicesAction: () => ({ services: [] }),
  ProjectSource: () => ({}),
  GithubSource: () => ({ pinned: false, autoDeployPending: false }),
  GithubCommit: () => ({ sha: "", title: "", url: "" }),
  Service: () => ({ service: "", containerRunning: false, image: "", buildsImage: false, imageDigest: "", imageSizeBytes: 0n, command: [], runAsUser: "", outOfMemory: false, restartCount: 0, cpuUsedCores: 0, memoryUsedBytes: 0n, memoryLimitBytes: 0n, cpuLimitCores: 0, writableLayerBytes: 0n, ports: [], listeningPorts: [], publishedPorts: [], volumeMounts: [], environment: [], envFiles: [], sshCommand: "" }),
  PublishedPort: () => ({ machinePort: 0, containerPort: 0, protocol: "", machineOnly: false }),
  VolumeMount: () => ({ volume: "", containerPath: "" }),
  HealthCheck: () => ({ command: [], intervalSeconds: 0, consecutiveFailureCount: 0, recentResultsPassed: [], lastFailureOutput: "" }),
  EnvironmentVariable: () => ({ name: "", value: "", secret: false, sourceFile: "", fromEnvFileVariables: [], valueLeftOut: false }),
  Volume: () => ({ volume: "", sizeBytes: 0n, mountedBy: [], snapshotCount: 0, declared: false }),
  VolumeMountedBy: () => ({ service: "", containerPath: "" }),
  Host: () => ({ host: "", url: "", unavailableMessage: "" }),
  Route: () => ({ host: "", path: "", service: "", port: 0, stripPath: false }),
  Operation: () => ({ operationId: "", failureMessage: "", madeCurrent: false, service: "", failedExitCode: 0, snapshotId: "", restoredVolumes: [], undoSnapshotId: "", archiveName: "", adjustments: [], changedPaths: [], changedPathCount: 0, filesKept: false }),
  Snapshot: () => ({ snapshotId: "", sizeBytes: 0n, volumes: [] }),
  HttpTrafficSummary: () => ({ requestCount: 0n, serverErrorCount: 0n, latencyP50Ms: 0, latencyP95Ms: 0 }),
  CreateProjectRequest: () => ({ projectId: "", uploadId: "", files: [], timeoutSeconds: 0, operationId: "" }),
  CreateProjectResponse: () => ({ violations: [], adjustments: [], log: [] }),
  DeployProjectRequest: () => ({ projectId: "", baseDeployId: "", files: [], timeoutSeconds: 0, operationId: "" }),
  MountVolume: () => ({ service: "", volume: "", containerPath: "" }),
  ProjectExtension: () => ({ routes: [], removeRoutes: false, password: "", removePassword: false }),
  FileChange: () => ({ path: "", executable: false }),
  DeployProjectResponse: () => ({ violations: [], adjustments: [], log: [] }),
  SpecViolation: () => ({ service: "", location: "", violationMessage: "" }),
  ListCommitsRequest: () => ({ projectId: "", beforeCommit: "" }),
  ListCommitsResponse: () => ({ commits: [], more: false }),
  BranchCommit: () => ({ author: "", deployed: false, newest: false }),
  RunProjectActionRequest: () => ({ projectId: "", operationId: "" }),
  ServicesAction: () => ({ services: [] }),
  RecreateServiceAction: () => ({ service: "", pullLatestImage: false }),
  BackUpAction: () => ({}),
  RestoreSnapshotAction: () => ({ snapshotId: "", volumes: [] }),
  CancelOperationAction: () => ({ operationId: "" }),
  DeleteProjectAction: () => ({ skipFinalBackup: false }),
  RunProjectActionResponse: () => ({ log: [] }),
  GetOperationRequest: () => ({ projectId: "", operationId: "" }),
  GetOperationResponse: () => ({ log: [], logLineCount: 0, nextAfterLogLine: 0 }),
  OperationLogLine: () => ({ text: "" }),
  HttpTrafficFilter: () => ({ host: "", method: "", pathContains: "", pathPattern: "", statusClass: 0 }),
  QueryHttpTrafficRequest: () => ({ projectId: "", lastSeconds: 0, bucketWidthSeconds: 0, requestLimit: 0, pageToken: "" }),
  QueryHttpTrafficResponse: () => ({ buckets: [], topPaths: [], newestSequence: 0n, requests: [], nextPageToken: "", tailSequence: 0n }),
  HttpTrafficBucket: () => ({}),
  HttpPathTraffic: () => ({ method: "", pathPattern: "" }),
  HttpRequest: () => ({ sequence: 0n, host: "", method: "", path: "", pathPattern: "", routePath: "", service: "", port: 0, statusCode: 0, responseSizeBytes: 0n, durationMs: 0, serviceDurationMs: 0, clientIpAddress: "", userAgent: "" }),
  ContainerLogFilter: () => ({ service: "", textContains: "" }),
  QueryContainerLogsRequest: () => ({ projectId: "", lastSeconds: 0, limit: 0, fromStart: false, pageToken: "" }),
  QueryContainerLogsResponse: () => ({ lines: [], nextPageToken: "", tailCursor: "" }),
  LogLine: () => ({ service: "", text: "" }),
  RunServiceCommandRequest: () => ({ projectId: "", service: "", command: [], stdin: "", runAsUser: "", workingDirectory: "", timeoutSeconds: 0 }),
  RunServiceCommandResponse: () => ({ exitCode: 0, timedOut: false, stdout: "", stderr: "", outputTruncated: false }),
  FileEntry: () => ({ name: "", sizeBytes: 0n, mode: "", ownerUid: 0, ownerGid: 0, symlinkTarget: "" }),
  ReadPathRequest: () => ({ projectId: "", path: "", entryLimit: 0, offsetBytes: 0n, lengthBytes: 0, entryPageToken: "" }),
  ReadPathResponse: () => ({ volume: "", entries: [], entryCount: 0, nextEntryPageToken: "", text: "", binary: false, nextOffsetBytes: 0n, deployId: "" }),
  CreateTransferRequest: () => ({}),
  ArchiveUpload: () => ({ fileName: "" }),
  FileUpload: () => ({ projectId: "", path: "" }),
  PathDownload: () => ({ projectId: "", path: "" }),
  CreateTransferResponse: () => ({ url: "", httpMethod: "", command: "", uploadId: "", replaces: false, fileName: "", excludeNames: [] }),
  ProjectBusy: () => ({ operationId: "" }),
  ProjectChanged: () => ({}),
  MachineUnreachable: () => ({}),
  NoMachine: () => ({ url: "" }),
  WatchOperationRequest: () => ({ projectId: "", operationId: "" }),
  WatchOperationResponse: () => ({}),
  TailContainerLogsRequest: () => ({ projectId: "", afterCursor: "" }),
  TailContainerLogsResponse: () => ({ cursor: "" }),
  TailHttpTrafficRequest: () => ({ projectId: "", afterSequence: 0n }),
  TailHttpTrafficResponse: () => ({}),
};

{
  const m = reading(w.GetMachineResponseSchema, (leaf: Init<typeof w.GetMachineResponseSchema>): Init<typeof w.GetMachineResponseSchema> => (leaf), async (api) => (await api.getMachine({})));
  m.reads("GetMachineResponse: nothing set", {}, empty.GetMachineResponse());
  m.reads("GetMachineResponse: a field newer than the SDK", newer(w.GetMachineResponseSchema), empty.GetMachineResponse());
  m.reads("GetMachineResponse.machine", { machine: {} }, { ...empty.GetMachineResponse(), machine: empty.Machine() });
  m.reads("GetMachineResponse.projects", { projects: [{}] }, { ...empty.GetMachineResponse(), projects: [empty.ProjectSummary()] });
  m.reads("GetMachineResponse.deleted_projects", { deletedProjects: [{}] }, { ...empty.GetMachineResponse(), deletedProjects: [empty.DeletedProject()] });
  m.reads("GetMachineResponse.github", { github: {} }, { ...empty.GetMachineResponse(), github: empty.GithubConnection() });
}

{
  const m = reading(w.GetMachineResponseSchema, (leaf: Init<typeof w.MachineSchema>): Init<typeof w.GetMachineResponseSchema> => ({ machine: leaf }), async (api) => (await api.getMachine({}))?.machine);
  m.reads("Machine: nothing set", {}, empty.Machine());
  m.reads("Machine: a field newer than the SDK", newer(w.MachineSchema), empty.Machine());
  m.reads("Machine.name", { name: "name" }, { ...empty.Machine(), name: "name" });
  m.reads("Machine.location", { location: "location" }, { ...empty.Machine(), location: "location" });
  m.reads("Machine.sample_time", { sampleTime: { seconds: 1790000000n, nanos: 999600000 } }, { ...empty.Machine(), sampleTime: new Date(1790000000999) });
  m.reads("Machine.cpu_used_cores", { cpuUsedCores: 1005.5 }, { ...empty.Machine(), cpuUsedCores: 1005.5 });
  m.reads("Machine.cpu_total_cores", { cpuTotalCores: 1006.5 }, { ...empty.Machine(), cpuTotalCores: 1006.5 });
  m.reads("Machine.memory_used_bytes", { memoryUsedBytes: 9007199254740993n }, { ...empty.Machine(), memoryUsedBytes: 9007199254740993n });
  m.reads("Machine.memory_total_bytes", { memoryTotalBytes: 9007199254740993n }, { ...empty.Machine(), memoryTotalBytes: 9007199254740993n });
  m.reads("Machine.disk_used_bytes", { diskUsedBytes: 9007199254740993n }, { ...empty.Machine(), diskUsedBytes: 9007199254740993n });
  m.reads("Machine.disk_total_bytes", { diskTotalBytes: 9007199254740993n }, { ...empty.Machine(), diskTotalBytes: 9007199254740993n });
  m.reads("Machine.disk_usage", { diskUsage: {} }, { ...empty.Machine(), diskUsage: empty.DiskUsage() });
  m.reads("Machine.hostname", { hostname: "hostname" }, { ...empty.Machine(), hostname: "hostname" });
  m.reads("Machine.ssh_host_key_fingerprint", { sshHostKeyFingerprint: "ssh_host_key_fingerprint" }, { ...empty.Machine(), sshHostKeyFingerprint: "ssh_host_key_fingerprint" });
  m.reads("Machine.ssh_keys", { sshKeys: [{}] }, { ...empty.Machine(), sshKeys: [empty.SshKey()] });
  m.reads("Machine.backups_enabled", { backupsEnabled: true }, { ...empty.Machine(), backupsEnabled: true });
  m.reads("Machine.snapshot_list_time", { snapshotListTime: { seconds: 1790000000n, nanos: 999600000 } }, { ...empty.Machine(), snapshotListTime: new Date(1790000000999) });
  m.reads("Machine.snapshot_list_failure_message", { snapshotListFailureMessage: "snapshot_list_failure_message" }, { ...empty.Machine(), snapshotListFailureMessage: "snapshot_list_failure_message" });
  m.reads("Machine.backup_retention_hours", { backupRetentionHours: 1004 }, { ...empty.Machine(), backupRetentionHours: 1004 });
  m.reads("Machine.acme_enabled", { acmeEnabled: true }, { ...empty.Machine(), acmeEnabled: true });
  m.reads("Machine.apps_domain", { appsDomain: "apps_domain" }, { ...empty.Machine(), appsDomain: "apps_domain" });
  m.reads("Machine.daemon_version", { daemonVersion: "daemon_version" }, { ...empty.Machine(), daemonVersion: "daemon_version" });
  m.reads("Machine.docker_version", { dockerVersion: "docker_version" }, { ...empty.Machine(), dockerVersion: "docker_version" });
  m.reads("Machine.boot_time", { bootTime: { seconds: 1790000000n, nanos: 999600000 } }, { ...empty.Machine(), bootTime: new Date(1790000000999) });
  m.reads("Machine.restart_required_time", { restartRequiredTime: { seconds: 1790000000n, nanos: 999600000 } }, { ...empty.Machine(), restartRequiredTime: new Date(1790000000999) });
  m.reads("Machine.scheduled_restart_time", { scheduledRestartTime: { seconds: 1790000000n, nanos: 999600000 } }, { ...empty.Machine(), scheduledRestartTime: new Date(1790000000999) });
  m.reads("Machine.sessions", { sessions: [{}] }, { ...empty.Machine(), sessions: [empty.MachineSession()] });
}

{
  const m = reading(w.GetMachineResponseSchema, (leaf: Init<typeof w.MachineSessionSchema>): Init<typeof w.GetMachineResponseSchema> => ({ machine: { sessions: [leaf] } }), async (api) => (await api.getMachine({}))?.machine?.sessions?.[0]);
  m.reads("MachineSession: nothing set", {}, empty.MachineSession());
  m.reads("MachineSession: a field newer than the SDK", newer(w.MachineSessionSchema), empty.MachineSession());
  m.reads("MachineSession.session_id", { sessionId: "session_id" }, { ...empty.MachineSession(), sessionId: "session_id" });
  m.reads("MachineSession.kind: WEB_TERMINAL", { kind: w.MachineSessionKind.WEB_TERMINAL }, { ...empty.MachineSession(), kind: "WEB_TERMINAL" });
  m.reads("MachineSession.kind: SSH_TERMINAL", { kind: w.MachineSessionKind.SSH_TERMINAL }, { ...empty.MachineSession(), kind: "SSH_TERMINAL" });
  m.reads("MachineSession.kind: SSH_COMMAND", { kind: w.MachineSessionKind.SSH_COMMAND }, { ...empty.MachineSession(), kind: "SSH_COMMAND" });
  m.reads("MachineSession.kind: SFTP", { kind: w.MachineSessionKind.SFTP }, { ...empty.MachineSession(), kind: "SFTP" });
  m.reads("MachineSession.kind: TUNNEL", { kind: w.MachineSessionKind.TUNNEL }, { ...empty.MachineSession(), kind: "TUNNEL" });
  m.reads("MachineSession.kind: a value newer than the SDK", { kind: 9999 as w.MachineSessionKind }, { ...empty.MachineSession(), kind: 9999 });
  m.reads("MachineSession.project_id", { projectId: "project_id" }, { ...empty.MachineSession(), projectId: "project_id" });
  m.reads("MachineSession.service", { service: "service" }, { ...empty.MachineSession(), service: "service" });
  m.reads("MachineSession.port", { port: 1005 }, { ...empty.MachineSession(), port: 1005 });
  m.reads("MachineSession.start_time", { startTime: { seconds: 1790000000n, nanos: 999600000 } }, { ...empty.MachineSession(), startTime: new Date(1790000000999) });
  m.reads("MachineSession.client_address", { clientAddress: "client_address" }, { ...empty.MachineSession(), clientAddress: "client_address" });
  m.reads("MachineSession.ssh_key_label", { sshKeyLabel: "ssh_key_label" }, { ...empty.MachineSession(), sshKeyLabel: "ssh_key_label" });
  m.reads("MachineSession.ssh_key_fingerprint", { sshKeyFingerprint: "ssh_key_fingerprint" }, { ...empty.MachineSession(), sshKeyFingerprint: "ssh_key_fingerprint" });
}

{
  const m = reading(w.GetMachineResponseSchema, (leaf: Init<typeof w.DiskUsageSchema>): Init<typeof w.GetMachineResponseSchema> => ({ machine: { diskUsage: leaf } }), async (api) => (await api.getMachine({}))?.machine?.diskUsage);
  m.reads("DiskUsage: nothing set", {}, empty.DiskUsage());
  m.reads("DiskUsage: a field newer than the SDK", newer(w.DiskUsageSchema), empty.DiskUsage());
  m.reads("DiskUsage.images_bytes", { imagesBytes: 9007199254740993n }, { ...empty.DiskUsage(), imagesBytes: 9007199254740993n });
  m.reads("DiskUsage.build_cache_bytes", { buildCacheBytes: 9007199254740993n }, { ...empty.DiskUsage(), buildCacheBytes: 9007199254740993n });
  m.reads("DiskUsage.build_cache_bytes: zero", { buildCacheBytes: 0n }, { ...empty.DiskUsage(), buildCacheBytes: 0n });
  m.reads("DiskUsage.volumes_bytes", { volumesBytes: 9007199254740993n }, { ...empty.DiskUsage(), volumesBytes: 9007199254740993n });
  m.reads("DiskUsage.container_layers_bytes", { containerLayersBytes: 9007199254740993n }, { ...empty.DiskUsage(), containerLayersBytes: 9007199254740993n });
  m.reads("DiskUsage.project_files_bytes", { projectFilesBytes: 9007199254740993n }, { ...empty.DiskUsage(), projectFilesBytes: 9007199254740993n });
  m.reads("DiskUsage.container_logs_bytes", { containerLogsBytes: 9007199254740993n }, { ...empty.DiskUsage(), containerLogsBytes: 9007199254740993n });
  m.reads("DiskUsage.http_traffic_bytes", { httpTrafficBytes: 9007199254740993n }, { ...empty.DiskUsage(), httpTrafficBytes: 9007199254740993n });
}

{
  const m = reading(w.GetMachineResponseSchema, (leaf: Init<typeof w.SshKeySchema>): Init<typeof w.GetMachineResponseSchema> => ({ machine: { sshKeys: [leaf] } }), async (api) => (await api.getMachine({}))?.machine?.sshKeys?.[0]);
  m.reads("SshKey: nothing set", {}, empty.SshKey());
  m.reads("SshKey: a field newer than the SDK", newer(w.SshKeySchema), empty.SshKey());
  m.reads("SshKey.public_key", { publicKey: "public_key" }, { ...empty.SshKey(), publicKey: "public_key" });
  m.reads("SshKey.label", { label: "label" }, { ...empty.SshKey(), label: "label" });
  m.reads("SshKey.fingerprint", { fingerprint: "fingerprint" }, { ...empty.SshKey(), fingerprint: "fingerprint" });
}

{
  const m = reading(w.GetMachineResponseSchema, (leaf: Init<typeof w.GithubConnectionSchema>): Init<typeof w.GetMachineResponseSchema> => ({ github: leaf }), async (api) => (await api.getMachine({}))?.github);
  m.reads("GithubConnection: nothing set", {}, empty.GithubConnection());
  m.reads("GithubConnection: a field newer than the SDK", newer(w.GithubConnectionSchema), empty.GithubConnection());
  m.reads("GithubConnection.app_name", { appName: "app_name" }, { ...empty.GithubConnection(), appName: "app_name" });
  m.reads("GithubConnection.install_url", { installUrl: "install_url" }, { ...empty.GithubConnection(), installUrl: "install_url" });
  m.reads("GithubConnection.repositories", { repositories: [{}] }, { ...empty.GithubConnection(), repositories: [empty.GithubRepository()] });
  m.reads("GithubConnection.repository_count", { repositoryCount: 1004 }, { ...empty.GithubConnection(), repositoryCount: 1004 });
  m.reads("GithubConnection.webhooks_enabled", { webhooksEnabled: true }, { ...empty.GithubConnection(), webhooksEnabled: true });
}

{
  const m = reading(w.GetMachineResponseSchema, (leaf: Init<typeof w.GithubRepositorySchema>): Init<typeof w.GetMachineResponseSchema> => ({ github: { repositories: [leaf] } }), async (api) => (await api.getMachine({}))?.github?.repositories?.[0]);
  m.reads("GithubRepository: nothing set", {}, empty.GithubRepository());
  m.reads("GithubRepository: a field newer than the SDK", newer(w.GithubRepositorySchema), empty.GithubRepository());
  m.reads("GithubRepository.repository", { repository: "repository" }, { ...empty.GithubRepository(), repository: "repository" });
  m.reads("GithubRepository.default_branch", { defaultBranch: "default_branch" }, { ...empty.GithubRepository(), defaultBranch: "default_branch" });
  m.reads("GithubRepository.private", { private: true }, { ...empty.GithubRepository(), private: true });
  m.reads("GithubRepository.push_time", { pushTime: { seconds: 1790000000n, nanos: 999600000 } }, { ...empty.GithubRepository(), pushTime: new Date(1790000000999) });
}

{
  const m = reading(w.GetMachineResponseSchema, (leaf: Init<typeof w.DeletedProjectSchema>): Init<typeof w.GetMachineResponseSchema> => ({ deletedProjects: [leaf] }), async (api) => (await api.getMachine({}))?.deletedProjects?.[0]);
  m.reads("DeletedProject: nothing set", {}, empty.DeletedProject());
  m.reads("DeletedProject: a field newer than the SDK", newer(w.DeletedProjectSchema), empty.DeletedProject());
  m.reads("DeletedProject.project_id", { projectId: "project_id" }, { ...empty.DeletedProject(), projectId: "project_id" });
  m.reads("DeletedProject.newest_snapshot", { newestSnapshot: {} }, { ...empty.DeletedProject(), newestSnapshot: empty.Snapshot() });
  m.reads("DeletedProject.snapshot_count", { snapshotCount: 1003 }, { ...empty.DeletedProject(), snapshotCount: 1003 });
}

{
  const m = reading(w.RunMachineActionResponseSchema, (leaf: Init<typeof w.RunMachineActionResponseSchema>): Init<typeof w.RunMachineActionResponseSchema> => (leaf), async (api) => (await api.runMachineAction({})));
  m.reads("RunMachineActionResponse: nothing set", {}, empty.RunMachineActionResponse());
  m.reads("RunMachineActionResponse: a field newer than the SDK", newer(w.RunMachineActionResponseSchema), empty.RunMachineActionResponse());
  m.reads("RunMachineActionResponse.machine", { machine: {} }, { ...empty.RunMachineActionResponse(), machine: empty.Machine() });
}

{
  const m = reading(w.GetMachineResponseSchema, (leaf: Init<typeof w.ProjectMetadataSchema>): Init<typeof w.GetMachineResponseSchema> => ({ projects: [{ metadata: leaf }] }), async (api) => (await api.getMachine({}))?.projects?.[0]?.metadata);
  m.reads("ProjectMetadata: nothing set", {}, empty.ProjectMetadata());
  m.reads("ProjectMetadata: a field newer than the SDK", newer(w.ProjectMetadataSchema), empty.ProjectMetadata());
  m.reads("ProjectMetadata.name", { name: "name" }, { ...empty.ProjectMetadata(), name: "name" });
  m.reads("ProjectMetadata.name: zero", { name: "" }, { ...empty.ProjectMetadata(), name: "" });
  m.reads("ProjectMetadata.emoji", { emoji: "emoji" }, { ...empty.ProjectMetadata(), emoji: "emoji" });
  m.reads("ProjectMetadata.emoji: zero", { emoji: "" }, { ...empty.ProjectMetadata(), emoji: "" });
  m.reads("ProjectMetadata.description", { description: "description" }, { ...empty.ProjectMetadata(), description: "description" });
  m.reads("ProjectMetadata.description: zero", { description: "" }, { ...empty.ProjectMetadata(), description: "" });
  m.reads("ProjectMetadata.notes", { notes: "notes" }, { ...empty.ProjectMetadata(), notes: "notes" });
  m.reads("ProjectMetadata.notes: zero", { notes: "" }, { ...empty.ProjectMetadata(), notes: "" });
}

{
  const m = reading(w.GetMachineResponseSchema, (leaf: Init<typeof w.ProjectSummarySchema>): Init<typeof w.GetMachineResponseSchema> => ({ projects: [leaf] }), async (api) => (await api.getMachine({}))?.projects?.[0]);
  m.reads("ProjectSummary: nothing set", {}, empty.ProjectSummary());
  m.reads("ProjectSummary: a field newer than the SDK", newer(w.ProjectSummarySchema), empty.ProjectSummary());
  m.reads("ProjectSummary.project_id", { projectId: "project_id" }, { ...empty.ProjectSummary(), projectId: "project_id" });
  m.reads("ProjectSummary.metadata", { metadata: {} }, { ...empty.ProjectSummary(), metadata: empty.ProjectMetadata() });
  m.reads("ProjectSummary.problems", { problems: [{}] }, { ...empty.ProjectSummary(), problems: [empty.ProjectProblem()] });
  m.reads("ProjectSummary.services", { services: [{}] }, { ...empty.ProjectSummary(), services: [empty.ServiceSummary()] });
  m.reads("ProjectSummary.url", { url: "url" }, { ...empty.ProjectSummary(), url: "url" });
  m.reads("ProjectSummary.hosts", { hosts: ["hosts", ""] }, { ...empty.ProjectSummary(), hosts: ["hosts", ""] });
  m.reads("ProjectSummary.http_traffic_last_day", { httpTrafficLastDay: {} }, { ...empty.ProjectSummary(), httpTrafficLastDay: empty.HttpTrafficSummary() });
  m.reads("ProjectSummary.cpu_used_cores", { cpuUsedCores: 1008.5 }, { ...empty.ProjectSummary(), cpuUsedCores: 1008.5 });
  m.reads("ProjectSummary.memory_used_bytes", { memoryUsedBytes: 9007199254740993n }, { ...empty.ProjectSummary(), memoryUsedBytes: 9007199254740993n });
  m.reads("ProjectSummary.deploy_time", { deployTime: { seconds: 1790000000n, nanos: 999600000 } }, { ...empty.ProjectSummary(), deployTime: new Date(1790000000999) });
  m.reads("ProjectSummary.running_operations", { runningOperations: [{}] }, { ...empty.ProjectSummary(), runningOperations: [empty.Operation()] });
  m.reads("ProjectSummary.pinned", { pinned: true }, { ...empty.ProjectSummary(), pinned: true });
  m.reads("ProjectSummary.disk_used_bytes", { diskUsedBytes: 9007199254740993n }, { ...empty.ProjectSummary(), diskUsedBytes: 9007199254740993n });
}

{
  const m = reading(w.GetMachineResponseSchema, (leaf: Init<typeof w.ServiceSummarySchema>): Init<typeof w.GetMachineResponseSchema> => ({ projects: [{ services: [leaf] }] }), async (api) => (await api.getMachine({}))?.projects?.[0]?.services?.[0]);
  m.reads("ServiceSummary: nothing set", {}, empty.ServiceSummary());
  m.reads("ServiceSummary: a field newer than the SDK", newer(w.ServiceSummarySchema), empty.ServiceSummary());
  m.reads("ServiceSummary.service", { service: "service" }, { ...empty.ServiceSummary(), service: "service" });
  m.reads("ServiceSummary.state: NOT_CREATED", { state: w.ServiceState.NOT_CREATED }, { ...empty.ServiceSummary(), state: "NOT_CREATED" });
  m.reads("ServiceSummary.state: STARTING", { state: w.ServiceState.STARTING }, { ...empty.ServiceSummary(), state: "STARTING" });
  m.reads("ServiceSummary.state: RUNNING", { state: w.ServiceState.RUNNING }, { ...empty.ServiceSummary(), state: "RUNNING" });
  m.reads("ServiceSummary.state: HEALTHY", { state: w.ServiceState.HEALTHY }, { ...empty.ServiceSummary(), state: "HEALTHY" });
  m.reads("ServiceSummary.state: UNHEALTHY", { state: w.ServiceState.UNHEALTHY }, { ...empty.ServiceSummary(), state: "UNHEALTHY" });
  m.reads("ServiceSummary.state: RESTARTING", { state: w.ServiceState.RESTARTING }, { ...empty.ServiceSummary(), state: "RESTARTING" });
  m.reads("ServiceSummary.state: STOPPED", { state: w.ServiceState.STOPPED }, { ...empty.ServiceSummary(), state: "STOPPED" });
  m.reads("ServiceSummary.state: EXITED", { state: w.ServiceState.EXITED }, { ...empty.ServiceSummary(), state: "EXITED" });
  m.reads("ServiceSummary.state: a value newer than the SDK", { state: 9999 as w.ServiceState }, { ...empty.ServiceSummary(), state: 9999 });
}

{
  const m = reading(w.GetMachineResponseSchema, (leaf: Init<typeof w.ProjectProblemSchema>): Init<typeof w.GetMachineResponseSchema> => ({ projects: [{ problems: [leaf] }] }), async (api) => (await api.getMachine({}))?.projects?.[0]?.problems?.[0]);
  m.reads("ProjectProblem: nothing set", {}, empty.ProjectProblem());
  m.reads("ProjectProblem: a field newer than the SDK", newer(w.ProjectProblemSchema), empty.ProjectProblem());
  m.reads("ProjectProblem.kind: DEPLOY_FAILED", { kind: w.ProjectProblemKind.DEPLOY_FAILED }, { ...empty.ProjectProblem(), kind: "DEPLOY_FAILED" });
  m.reads("ProjectProblem.kind: SERVICE_UNHEALTHY", { kind: w.ProjectProblemKind.SERVICE_UNHEALTHY }, { ...empty.ProjectProblem(), kind: "SERVICE_UNHEALTHY" });
  m.reads("ProjectProblem.kind: SERVICE_RESTARTING", { kind: w.ProjectProblemKind.SERVICE_RESTARTING }, { ...empty.ProjectProblem(), kind: "SERVICE_RESTARTING" });
  m.reads("ProjectProblem.kind: SERVICE_OUT_OF_MEMORY", { kind: w.ProjectProblemKind.SERVICE_OUT_OF_MEMORY }, { ...empty.ProjectProblem(), kind: "SERVICE_OUT_OF_MEMORY" });
  m.reads("ProjectProblem.kind: BACKUP_FAILED", { kind: w.ProjectProblemKind.BACKUP_FAILED }, { ...empty.ProjectProblem(), kind: "BACKUP_FAILED" });
  m.reads("ProjectProblem.kind: DEPLOY_CANCELLED", { kind: w.ProjectProblemKind.DEPLOY_CANCELLED }, { ...empty.ProjectProblem(), kind: "DEPLOY_CANCELLED" });
  m.reads("ProjectProblem.kind: SERVICE_EXITED", { kind: w.ProjectProblemKind.SERVICE_EXITED }, { ...empty.ProjectProblem(), kind: "SERVICE_EXITED" });
  m.reads("ProjectProblem.kind: RESTORE_FAILED", { kind: w.ProjectProblemKind.RESTORE_FAILED }, { ...empty.ProjectProblem(), kind: "RESTORE_FAILED" });
  m.reads("ProjectProblem.kind: AUTO_DEPLOY_REFUSED", { kind: w.ProjectProblemKind.AUTO_DEPLOY_REFUSED }, { ...empty.ProjectProblem(), kind: "AUTO_DEPLOY_REFUSED" });
  m.reads("ProjectProblem.kind: SERVICE_PORT_CLOSED", { kind: w.ProjectProblemKind.SERVICE_PORT_CLOSED }, { ...empty.ProjectProblem(), kind: "SERVICE_PORT_CLOSED" });
  m.reads("ProjectProblem.kind: a value newer than the SDK", { kind: 9999 as w.ProjectProblemKind }, { ...empty.ProjectProblem(), kind: 9999 });
  m.reads("ProjectProblem.service", { service: "service" }, { ...empty.ProjectProblem(), service: "service" });
  m.reads("ProjectProblem.operation_id", { operationId: "operation_id" }, { ...empty.ProjectProblem(), operationId: "operation_id" });
  m.reads("ProjectProblem.since_time", { sinceTime: { seconds: 1790000000n, nanos: 999600000 } }, { ...empty.ProjectProblem(), sinceTime: new Date(1790000000999) });
  m.reads("ProjectProblem.problem_message", { problemMessage: "problem_message" }, { ...empty.ProjectProblem(), problemMessage: "problem_message" });
}

{
  const m = reading(w.GetProjectResponseSchema, (leaf: Init<typeof w.GetProjectResponseSchema>): Init<typeof w.GetProjectResponseSchema> => (leaf), async (api) => (await api.getProject({})));
  m.reads("GetProjectResponse: nothing set", {}, empty.GetProjectResponse());
  m.reads("GetProjectResponse: a field newer than the SDK", newer(w.GetProjectResponseSchema), empty.GetProjectResponse());
  m.reads("GetProjectResponse.project", { project: {} }, { ...empty.GetProjectResponse(), project: empty.Project() });
}

{
  const m = reading(w.GetProjectResponseSchema, (leaf: Init<typeof w.ProjectSchema>): Init<typeof w.GetProjectResponseSchema> => ({ project: leaf }), async (api) => (await api.getProject({}))?.project);
  m.reads("Project: nothing set", {}, empty.Project());
  m.reads("Project: a field newer than the SDK", newer(w.ProjectSchema), empty.Project());
  m.reads("Project.project_id", { projectId: "project_id" }, { ...empty.Project(), projectId: "project_id" });
  m.reads("Project.metadata", { metadata: {} }, { ...empty.Project(), metadata: empty.ProjectMetadata() });
  m.reads("Project.problems", { problems: [{}] }, { ...empty.Project(), problems: [empty.ProjectProblem()] });
  m.reads("Project.url", { url: "url" }, { ...empty.Project(), url: "url" });
  m.reads("Project.cpu_used_cores", { cpuUsedCores: 1005.5 }, { ...empty.Project(), cpuUsedCores: 1005.5 });
  m.reads("Project.memory_used_bytes", { memoryUsedBytes: 9007199254740993n }, { ...empty.Project(), memoryUsedBytes: 9007199254740993n });
  m.reads("Project.deploy_id", { deployId: "deploy_id" }, { ...empty.Project(), deployId: "deploy_id" });
  m.reads("Project.deploy_status: IN_PROGRESS", { deployStatus: w.OperationStatus.IN_PROGRESS }, { ...empty.Project(), deployStatus: "IN_PROGRESS" });
  m.reads("Project.deploy_status: SUCCEEDED", { deployStatus: w.OperationStatus.SUCCEEDED }, { ...empty.Project(), deployStatus: "SUCCEEDED" });
  m.reads("Project.deploy_status: FAILED", { deployStatus: w.OperationStatus.FAILED }, { ...empty.Project(), deployStatus: "FAILED" });
  m.reads("Project.deploy_status: CANCELLED", { deployStatus: w.OperationStatus.CANCELLED }, { ...empty.Project(), deployStatus: "CANCELLED" });
  m.reads("Project.deploy_status: a value newer than the SDK", { deployStatus: 9999 as w.OperationStatus }, { ...empty.Project(), deployStatus: 9999 });
  m.reads("Project.deploy_time", { deployTime: { seconds: 1790000000n, nanos: 999600000 } }, { ...empty.Project(), deployTime: new Date(1790000000999) });
  m.reads("Project.x_pethost_applies_at_once", { xPethostAppliesAtOnce: true }, { ...empty.Project(), xPethostAppliesAtOnce: true });
  m.reads("Project.services", { services: [{}] }, { ...empty.Project(), services: [empty.Service()] });
  m.reads("Project.volumes", { volumes: [{}] }, { ...empty.Project(), volumes: [empty.Volume()] });
  m.reads("Project.routes", { routes: [{}] }, { ...empty.Project(), routes: [empty.Route()] });
  m.reads("Project.hosts", { hosts: [{}] }, { ...empty.Project(), hosts: [empty.Host()] });
  m.reads("Project.password_protected", { passwordProtected: true }, { ...empty.Project(), passwordProtected: true });
  m.reads("Project.operations", { operations: [{}] }, { ...empty.Project(), operations: [empty.Operation()] });
  m.reads("Project.snapshots", { snapshots: [{}] }, { ...empty.Project(), snapshots: [empty.Snapshot()] });
  m.reads("Project.snapshot_count", { snapshotCount: 1015 }, { ...empty.Project(), snapshotCount: 1015 });
  m.reads("Project.snapshot_list_time", { snapshotListTime: { seconds: 1790000000n, nanos: 999600000 } }, { ...empty.Project(), snapshotListTime: new Date(1790000000999) });
  m.reads("Project.http_traffic_last_day", { httpTrafficLastDay: {} }, { ...empty.Project(), httpTrafficLastDay: empty.HttpTrafficSummary() });
  m.reads("Project.source", { source: {} }, { ...empty.Project(), source: empty.ProjectSource() });
  m.reads("Project.running_services_action", { runningServicesAction: {} }, { ...empty.Project(), runningServicesAction: empty.RunningServicesAction() });
}

{
  const m = reading(w.GetProjectResponseSchema, (leaf: Init<typeof w.RunningServicesActionSchema>): Init<typeof w.GetProjectResponseSchema> => ({ project: { runningServicesAction: leaf } }), async (api) => (await api.getProject({}))?.project?.runningServicesAction);
  m.reads("RunningServicesAction: nothing set", {}, empty.RunningServicesAction());
  m.reads("RunningServicesAction: a field newer than the SDK", newer(w.RunningServicesActionSchema), empty.RunningServicesAction());
  m.reads("RunningServicesAction.kind: START", { kind: w.ServicesActionKind.START }, { ...empty.RunningServicesAction(), kind: "START" });
  m.reads("RunningServicesAction.kind: STOP", { kind: w.ServicesActionKind.STOP }, { ...empty.RunningServicesAction(), kind: "STOP" });
  m.reads("RunningServicesAction.kind: RESTART", { kind: w.ServicesActionKind.RESTART }, { ...empty.RunningServicesAction(), kind: "RESTART" });
  m.reads("RunningServicesAction.kind: a value newer than the SDK", { kind: 9999 as w.ServicesActionKind }, { ...empty.RunningServicesAction(), kind: 9999 });
  m.reads("RunningServicesAction.services", { services: ["services", ""] }, { ...empty.RunningServicesAction(), services: ["services", ""] });
  m.reads("RunningServicesAction.start_time", { startTime: { seconds: 1790000000n, nanos: 999600000 } }, { ...empty.RunningServicesAction(), startTime: new Date(1790000000999) });
}

{
  const m = reading(w.GetProjectResponseSchema, (leaf: Init<typeof w.ProjectSourceSchema>): Init<typeof w.GetProjectResponseSchema> => ({ project: { source: leaf } }), async (api) => (await api.getProject({}))?.project?.source);
  m.reads("ProjectSource: nothing set", {}, empty.ProjectSource());
  m.reads("ProjectSource: a field or a oneof's member newer than the SDK", newer(w.ProjectSourceSchema), empty.ProjectSource());
  m.reads("ProjectSource.files", { kind: { case: "files", value: true } }, { ...empty.ProjectSource(), kind: "files", files: true });
  m.reads("ProjectSource.files: zero", { kind: { case: "files", value: false } }, { ...empty.ProjectSource(), kind: "files", files: false });
  m.reads("ProjectSource.github", { kind: { case: "github", value: {} } }, { ...empty.ProjectSource(), kind: "github", github: empty.GithubSource() });
}

{
  const m = reading(w.GetProjectResponseSchema, (leaf: Init<typeof w.GithubSourceSchema>): Init<typeof w.GetProjectResponseSchema> => ({ project: { source: { kind: { case: "github", value: leaf } } } }), async (api) => (await api.getProject({}))?.project?.source?.github);
  m.reads("GithubSource: nothing set", {}, empty.GithubSource());
  m.reads("GithubSource: a field newer than the SDK", newer(w.GithubSourceSchema), empty.GithubSource());
  m.reads("GithubSource.repository", { repository: "repository" }, { ...empty.GithubSource(), repository: "repository" });
  m.reads("GithubSource.repository: zero", { repository: "" }, { ...empty.GithubSource(), repository: "" });
  m.reads("GithubSource.branch", { branch: "branch" }, { ...empty.GithubSource(), branch: "branch" });
  m.reads("GithubSource.branch: zero", { branch: "" }, { ...empty.GithubSource(), branch: "" });
  m.reads("GithubSource.directory", { directory: "directory" }, { ...empty.GithubSource(), directory: "directory" });
  m.reads("GithubSource.directory: zero", { directory: "" }, { ...empty.GithubSource(), directory: "" });
  m.reads("GithubSource.auto_deploy", { autoDeploy: true }, { ...empty.GithubSource(), autoDeploy: true });
  m.reads("GithubSource.auto_deploy: zero", { autoDeploy: false }, { ...empty.GithubSource(), autoDeploy: false });
  m.reads("GithubSource.newest_commit", { newestCommit: {} }, { ...empty.GithubSource(), newestCommit: empty.GithubCommit() });
  m.reads("GithubSource.deployed_commit", { deployedCommit: {} }, { ...empty.GithubSource(), deployedCommit: empty.GithubCommit() });
  m.reads("GithubSource.pinned", { pinned: true }, { ...empty.GithubSource(), pinned: true });
  m.reads("GithubSource.auto_deploy_pending", { autoDeployPending: true }, { ...empty.GithubSource(), autoDeployPending: true });
}

{
  const m = reading(w.CreateProjectResponseSchema, (leaf: Init<typeof w.GithubCommitSchema>): Init<typeof w.CreateProjectResponseSchema> => ({ operation: { githubCommit: leaf } }), async (api) => (await api.createProject({}))?.operation?.githubCommit);
  m.reads("GithubCommit: nothing set", {}, empty.GithubCommit());
  m.reads("GithubCommit: a field newer than the SDK", newer(w.GithubCommitSchema), empty.GithubCommit());
  m.reads("GithubCommit.sha", { sha: "sha" }, { ...empty.GithubCommit(), sha: "sha" });
  m.reads("GithubCommit.title", { title: "title" }, { ...empty.GithubCommit(), title: "title" });
  m.reads("GithubCommit.url", { url: "url" }, { ...empty.GithubCommit(), url: "url" });
}

{
  const m = reading(w.GetProjectResponseSchema, (leaf: Init<typeof w.ServiceSchema>): Init<typeof w.GetProjectResponseSchema> => ({ project: { services: [leaf] } }), async (api) => (await api.getProject({}))?.project?.services?.[0]);
  m.reads("Service: nothing set", {}, empty.Service());
  m.reads("Service: a field newer than the SDK", newer(w.ServiceSchema), empty.Service());
  m.reads("Service.service", { service: "service" }, { ...empty.Service(), service: "service" });
  m.reads("Service.state: NOT_CREATED", { state: w.ServiceState.NOT_CREATED }, { ...empty.Service(), state: "NOT_CREATED" });
  m.reads("Service.state: STARTING", { state: w.ServiceState.STARTING }, { ...empty.Service(), state: "STARTING" });
  m.reads("Service.state: RUNNING", { state: w.ServiceState.RUNNING }, { ...empty.Service(), state: "RUNNING" });
  m.reads("Service.state: HEALTHY", { state: w.ServiceState.HEALTHY }, { ...empty.Service(), state: "HEALTHY" });
  m.reads("Service.state: UNHEALTHY", { state: w.ServiceState.UNHEALTHY }, { ...empty.Service(), state: "UNHEALTHY" });
  m.reads("Service.state: RESTARTING", { state: w.ServiceState.RESTARTING }, { ...empty.Service(), state: "RESTARTING" });
  m.reads("Service.state: STOPPED", { state: w.ServiceState.STOPPED }, { ...empty.Service(), state: "STOPPED" });
  m.reads("Service.state: EXITED", { state: w.ServiceState.EXITED }, { ...empty.Service(), state: "EXITED" });
  m.reads("Service.state: a value newer than the SDK", { state: 9999 as w.ServiceState }, { ...empty.Service(), state: 9999 });
  m.reads("Service.container_running", { containerRunning: true }, { ...empty.Service(), containerRunning: true });
  m.reads("Service.image", { image: "image" }, { ...empty.Service(), image: "image" });
  m.reads("Service.builds_image", { buildsImage: true }, { ...empty.Service(), buildsImage: true });
  m.reads("Service.image_digest", { imageDigest: "image_digest" }, { ...empty.Service(), imageDigest: "image_digest" });
  m.reads("Service.image_size_bytes", { imageSizeBytes: 9007199254740993n }, { ...empty.Service(), imageSizeBytes: 9007199254740993n });
  m.reads("Service.command", { command: ["command", ""] }, { ...empty.Service(), command: ["command", ""] });
  m.reads("Service.run_as_user", { runAsUser: "run_as_user" }, { ...empty.Service(), runAsUser: "run_as_user" });
  m.reads("Service.start_time", { startTime: { seconds: 1790000000n, nanos: 999600000 } }, { ...empty.Service(), startTime: new Date(1790000000999) });
  m.reads("Service.finish_time", { finishTime: { seconds: 1790000000n, nanos: 999600000 } }, { ...empty.Service(), finishTime: new Date(1790000000999) });
  m.reads("Service.exit_code", { exitCode: -1011 }, { ...empty.Service(), exitCode: -1011 });
  m.reads("Service.exit_code: zero", { exitCode: 0 }, { ...empty.Service(), exitCode: 0 });
  m.reads("Service.out_of_memory", { outOfMemory: true }, { ...empty.Service(), outOfMemory: true });
  m.reads("Service.restart_count", { restartCount: 1013 }, { ...empty.Service(), restartCount: 1013 });
  m.reads("Service.cpu_used_cores", { cpuUsedCores: 1014.5 }, { ...empty.Service(), cpuUsedCores: 1014.5 });
  m.reads("Service.memory_used_bytes", { memoryUsedBytes: 9007199254740993n }, { ...empty.Service(), memoryUsedBytes: 9007199254740993n });
  m.reads("Service.memory_limit_bytes", { memoryLimitBytes: 9007199254740993n }, { ...empty.Service(), memoryLimitBytes: 9007199254740993n });
  m.reads("Service.cpu_limit_cores", { cpuLimitCores: 1017.5 }, { ...empty.Service(), cpuLimitCores: 1017.5 });
  m.reads("Service.writable_layer_bytes", { writableLayerBytes: 9007199254740993n }, { ...empty.Service(), writableLayerBytes: 9007199254740993n });
  m.reads("Service.ports", { ports: [1019, 0] }, { ...empty.Service(), ports: [1019, 0] });
  m.reads("Service.listening_ports", { listeningPorts: [1028, 0] }, { ...empty.Service(), listeningPorts: [1028, 0] });
  m.reads("Service.published_ports", { publishedPorts: [{}] }, { ...empty.Service(), publishedPorts: [empty.PublishedPort()] });
  m.reads("Service.volume_mounts", { volumeMounts: [{}] }, { ...empty.Service(), volumeMounts: [empty.VolumeMount()] });
  m.reads("Service.restart_policy: NO", { restartPolicy: w.RestartPolicy.NO }, { ...empty.Service(), restartPolicy: "NO" });
  m.reads("Service.restart_policy: ON_FAILURE", { restartPolicy: w.RestartPolicy.ON_FAILURE }, { ...empty.Service(), restartPolicy: "ON_FAILURE" });
  m.reads("Service.restart_policy: UNLESS_STOPPED", { restartPolicy: w.RestartPolicy.UNLESS_STOPPED }, { ...empty.Service(), restartPolicy: "UNLESS_STOPPED" });
  m.reads("Service.restart_policy: ALWAYS", { restartPolicy: w.RestartPolicy.ALWAYS }, { ...empty.Service(), restartPolicy: "ALWAYS" });
  m.reads("Service.restart_policy: a value newer than the SDK", { restartPolicy: 9999 as w.RestartPolicy }, { ...empty.Service(), restartPolicy: 9999 });
  m.reads("Service.health_check", { healthCheck: {} }, { ...empty.Service(), healthCheck: empty.HealthCheck() });
  m.reads("Service.environment", { environment: [{}] }, { ...empty.Service(), environment: [empty.EnvironmentVariable()] });
  m.reads("Service.env_files", { envFiles: ["env_files", ""] }, { ...empty.Service(), envFiles: ["env_files", ""] });
  m.reads("Service.ssh_command", { sshCommand: "ssh_command" }, { ...empty.Service(), sshCommand: "ssh_command" });
}

{
  const m = reading(w.GetProjectResponseSchema, (leaf: Init<typeof w.PublishedPortSchema>): Init<typeof w.GetProjectResponseSchema> => ({ project: { services: [{ publishedPorts: [leaf] }] } }), async (api) => (await api.getProject({}))?.project?.services?.[0]?.publishedPorts?.[0]);
  m.reads("PublishedPort: nothing set", {}, empty.PublishedPort());
  m.reads("PublishedPort: a field newer than the SDK", newer(w.PublishedPortSchema), empty.PublishedPort());
  m.reads("PublishedPort.machine_port", { machinePort: 1001 }, { ...empty.PublishedPort(), machinePort: 1001 });
  m.reads("PublishedPort.container_port", { containerPort: 1002 }, { ...empty.PublishedPort(), containerPort: 1002 });
  m.reads("PublishedPort.protocol", { protocol: "protocol" }, { ...empty.PublishedPort(), protocol: "protocol" });
  m.reads("PublishedPort.machine_only", { machineOnly: true }, { ...empty.PublishedPort(), machineOnly: true });
}

{
  const m = reading(w.GetProjectResponseSchema, (leaf: Init<typeof w.VolumeMountSchema>): Init<typeof w.GetProjectResponseSchema> => ({ project: { services: [{ volumeMounts: [leaf] }] } }), async (api) => (await api.getProject({}))?.project?.services?.[0]?.volumeMounts?.[0]);
  m.reads("VolumeMount: nothing set", {}, empty.VolumeMount());
  m.reads("VolumeMount: a field newer than the SDK", newer(w.VolumeMountSchema), empty.VolumeMount());
  m.reads("VolumeMount.volume", { volume: "volume" }, { ...empty.VolumeMount(), volume: "volume" });
  m.reads("VolumeMount.container_path", { containerPath: "container_path" }, { ...empty.VolumeMount(), containerPath: "container_path" });
}

{
  const m = reading(w.GetProjectResponseSchema, (leaf: Init<typeof w.HealthCheckSchema>): Init<typeof w.GetProjectResponseSchema> => ({ project: { services: [{ healthCheck: leaf }] } }), async (api) => (await api.getProject({}))?.project?.services?.[0]?.healthCheck);
  m.reads("HealthCheck: nothing set", {}, empty.HealthCheck());
  m.reads("HealthCheck: a field newer than the SDK", newer(w.HealthCheckSchema), empty.HealthCheck());
  m.reads("HealthCheck.command", { command: ["command", ""] }, { ...empty.HealthCheck(), command: ["command", ""] });
  m.reads("HealthCheck.interval_seconds", { intervalSeconds: 1002 }, { ...empty.HealthCheck(), intervalSeconds: 1002 });
  m.reads("HealthCheck.status: STARTING", { status: w.HealthStatus.STARTING }, { ...empty.HealthCheck(), status: "STARTING" });
  m.reads("HealthCheck.status: HEALTHY", { status: w.HealthStatus.HEALTHY }, { ...empty.HealthCheck(), status: "HEALTHY" });
  m.reads("HealthCheck.status: UNHEALTHY", { status: w.HealthStatus.UNHEALTHY }, { ...empty.HealthCheck(), status: "UNHEALTHY" });
  m.reads("HealthCheck.status: a value newer than the SDK", { status: 9999 as w.HealthStatus }, { ...empty.HealthCheck(), status: 9999 });
  m.reads("HealthCheck.consecutive_failure_count", { consecutiveFailureCount: 1004 }, { ...empty.HealthCheck(), consecutiveFailureCount: 1004 });
  m.reads("HealthCheck.recent_results_passed", { recentResultsPassed: [true, false] }, { ...empty.HealthCheck(), recentResultsPassed: [true, false] });
  m.reads("HealthCheck.last_failure_output", { lastFailureOutput: "last_failure_output" }, { ...empty.HealthCheck(), lastFailureOutput: "last_failure_output" });
}

{
  const m = reading(w.GetProjectResponseSchema, (leaf: Init<typeof w.EnvironmentVariableSchema>): Init<typeof w.GetProjectResponseSchema> => ({ project: { services: [{ environment: [leaf] }] } }), async (api) => (await api.getProject({}))?.project?.services?.[0]?.environment?.[0]);
  m.reads("EnvironmentVariable: nothing set", {}, empty.EnvironmentVariable());
  m.reads("EnvironmentVariable: a field newer than the SDK", newer(w.EnvironmentVariableSchema), empty.EnvironmentVariable());
  m.reads("EnvironmentVariable.name", { name: "name" }, { ...empty.EnvironmentVariable(), name: "name" });
  m.reads("EnvironmentVariable.value", { value: "value" }, { ...empty.EnvironmentVariable(), value: "value" });
  m.reads("EnvironmentVariable.secret", { secret: true }, { ...empty.EnvironmentVariable(), secret: true });
  m.reads("EnvironmentVariable.source_file", { sourceFile: "source_file" }, { ...empty.EnvironmentVariable(), sourceFile: "source_file" });
  m.reads("EnvironmentVariable.from_env_file_variables", { fromEnvFileVariables: ["from_env_file_variables", ""] }, { ...empty.EnvironmentVariable(), fromEnvFileVariables: ["from_env_file_variables", ""] });
  m.reads("EnvironmentVariable.value_left_out", { valueLeftOut: true }, { ...empty.EnvironmentVariable(), valueLeftOut: true });
}

{
  const m = reading(w.GetProjectResponseSchema, (leaf: Init<typeof w.VolumeSchema>): Init<typeof w.GetProjectResponseSchema> => ({ project: { volumes: [leaf] } }), async (api) => (await api.getProject({}))?.project?.volumes?.[0]);
  m.reads("Volume: nothing set", {}, empty.Volume());
  m.reads("Volume: a field newer than the SDK", newer(w.VolumeSchema), empty.Volume());
  m.reads("Volume.volume", { volume: "volume" }, { ...empty.Volume(), volume: "volume" });
  m.reads("Volume.size_bytes", { sizeBytes: 9007199254740993n }, { ...empty.Volume(), sizeBytes: 9007199254740993n });
  m.reads("Volume.mounted_by", { mountedBy: [{}] }, { ...empty.Volume(), mountedBy: [empty.VolumeMountedBy()] });
  m.reads("Volume.last_backup_time", { lastBackupTime: { seconds: 1790000000n, nanos: 999600000 } }, { ...empty.Volume(), lastBackupTime: new Date(1790000000999) });
  m.reads("Volume.snapshot_count", { snapshotCount: 1006 }, { ...empty.Volume(), snapshotCount: 1006 });
  m.reads("Volume.declared", { declared: true }, { ...empty.Volume(), declared: true });
}

{
  const m = reading(w.GetProjectResponseSchema, (leaf: Init<typeof w.VolumeMountedBySchema>): Init<typeof w.GetProjectResponseSchema> => ({ project: { volumes: [{ mountedBy: [leaf] }] } }), async (api) => (await api.getProject({}))?.project?.volumes?.[0]?.mountedBy?.[0]);
  m.reads("VolumeMountedBy: nothing set", {}, empty.VolumeMountedBy());
  m.reads("VolumeMountedBy: a field newer than the SDK", newer(w.VolumeMountedBySchema), empty.VolumeMountedBy());
  m.reads("VolumeMountedBy.service", { service: "service" }, { ...empty.VolumeMountedBy(), service: "service" });
  m.reads("VolumeMountedBy.container_path", { containerPath: "container_path" }, { ...empty.VolumeMountedBy(), containerPath: "container_path" });
}

{
  const m = reading(w.GetProjectResponseSchema, (leaf: Init<typeof w.HostSchema>): Init<typeof w.GetProjectResponseSchema> => ({ project: { hosts: [leaf] } }), async (api) => (await api.getProject({}))?.project?.hosts?.[0]);
  m.reads("Host: nothing set", {}, empty.Host());
  m.reads("Host: a field newer than the SDK", newer(w.HostSchema), empty.Host());
  m.reads("Host.host", { host: "host" }, { ...empty.Host(), host: "host" });
  m.reads("Host.url", { url: "url" }, { ...empty.Host(), url: "url" });
  m.reads("Host.certificate_source: NONE", { certificateSource: w.CertificateSource.NONE }, { ...empty.Host(), certificateSource: "NONE" });
  m.reads("Host.certificate_source: INSTALLED", { certificateSource: w.CertificateSource.INSTALLED }, { ...empty.Host(), certificateSource: "INSTALLED" });
  m.reads("Host.certificate_source: AUTOMATIC", { certificateSource: w.CertificateSource.AUTOMATIC }, { ...empty.Host(), certificateSource: "AUTOMATIC" });
  m.reads("Host.certificate_source: a value newer than the SDK", { certificateSource: 9999 as w.CertificateSource }, { ...empty.Host(), certificateSource: 9999 });
  m.reads("Host.certificate_expire_time", { certificateExpireTime: { seconds: 1790000000n, nanos: 999600000 } }, { ...empty.Host(), certificateExpireTime: new Date(1790000000999) });
  m.reads("Host.unavailable_message", { unavailableMessage: "unavailable_message" }, { ...empty.Host(), unavailableMessage: "unavailable_message" });
}

{
  const m = reading(w.GetProjectResponseSchema, (leaf: Init<typeof w.RouteSchema>): Init<typeof w.GetProjectResponseSchema> => ({ project: { routes: [leaf] } }), async (api) => (await api.getProject({}))?.project?.routes?.[0]);
  m.reads("Route: nothing set", {}, empty.Route());
  m.reads("Route: a field newer than the SDK", newer(w.RouteSchema), empty.Route());
  m.reads("Route.host", { host: "host" }, { ...empty.Route(), host: "host" });
  m.reads("Route.path", { path: "path" }, { ...empty.Route(), path: "path" });
  m.reads("Route.service", { service: "service" }, { ...empty.Route(), service: "service" });
  m.reads("Route.port", { port: 1004 }, { ...empty.Route(), port: 1004 });
  m.reads("Route.strip_path", { stripPath: true }, { ...empty.Route(), stripPath: true });
}

{
  const m = reading(w.CreateProjectResponseSchema, (leaf: Init<typeof w.OperationSchema>): Init<typeof w.CreateProjectResponseSchema> => ({ operation: leaf }), async (api) => (await api.createProject({}))?.operation);
  m.reads("Operation: nothing set", {}, empty.Operation());
  m.reads("Operation: a field newer than the SDK", newer(w.OperationSchema), empty.Operation());
  m.reads("Operation.operation_id", { operationId: "operation_id" }, { ...empty.Operation(), operationId: "operation_id" });
  m.reads("Operation.kind: DEPLOY", { kind: w.OperationKind.DEPLOY }, { ...empty.Operation(), kind: "DEPLOY" });
  m.reads("Operation.kind: RECREATE_SERVICE", { kind: w.OperationKind.RECREATE_SERVICE }, { ...empty.Operation(), kind: "RECREATE_SERVICE" });
  m.reads("Operation.kind: BACKUP", { kind: w.OperationKind.BACKUP }, { ...empty.Operation(), kind: "BACKUP" });
  m.reads("Operation.kind: RESTORE", { kind: w.OperationKind.RESTORE }, { ...empty.Operation(), kind: "RESTORE" });
  m.reads("Operation.kind: DELETE", { kind: w.OperationKind.DELETE }, { ...empty.Operation(), kind: "DELETE" });
  m.reads("Operation.kind: a value newer than the SDK", { kind: 9999 as w.OperationKind }, { ...empty.Operation(), kind: 9999 });
  m.reads("Operation.status: IN_PROGRESS", { status: w.OperationStatus.IN_PROGRESS }, { ...empty.Operation(), status: "IN_PROGRESS" });
  m.reads("Operation.status: SUCCEEDED", { status: w.OperationStatus.SUCCEEDED }, { ...empty.Operation(), status: "SUCCEEDED" });
  m.reads("Operation.status: FAILED", { status: w.OperationStatus.FAILED }, { ...empty.Operation(), status: "FAILED" });
  m.reads("Operation.status: CANCELLED", { status: w.OperationStatus.CANCELLED }, { ...empty.Operation(), status: "CANCELLED" });
  m.reads("Operation.status: a value newer than the SDK", { status: 9999 as w.OperationStatus }, { ...empty.Operation(), status: 9999 });
  m.reads("Operation.start_time", { startTime: { seconds: 1790000000n, nanos: 999600000 } }, { ...empty.Operation(), startTime: new Date(1790000000999) });
  m.reads("Operation.finish_time", { finishTime: { seconds: 1790000000n, nanos: 999600000 } }, { ...empty.Operation(), finishTime: new Date(1790000000999) });
  m.reads("Operation.failure_message", { failureMessage: "failure_message" }, { ...empty.Operation(), failureMessage: "failure_message" });
  m.reads("Operation.deploy_failure_reason: IMAGE_PULL_FAILED", { deployFailureReason: w.DeployFailureReason.IMAGE_PULL_FAILED }, { ...empty.Operation(), deployFailureReason: "IMAGE_PULL_FAILED" });
  m.reads("Operation.deploy_failure_reason: IMAGE_BUILD_FAILED", { deployFailureReason: w.DeployFailureReason.IMAGE_BUILD_FAILED }, { ...empty.Operation(), deployFailureReason: "IMAGE_BUILD_FAILED" });
  m.reads("Operation.deploy_failure_reason: CONTAINER_START_FAILED", { deployFailureReason: w.DeployFailureReason.CONTAINER_START_FAILED }, { ...empty.Operation(), deployFailureReason: "CONTAINER_START_FAILED" });
  m.reads("Operation.deploy_failure_reason: DISK_FULL", { deployFailureReason: w.DeployFailureReason.DISK_FULL }, { ...empty.Operation(), deployFailureReason: "DISK_FULL" });
  m.reads("Operation.deploy_failure_reason: INTERNAL", { deployFailureReason: w.DeployFailureReason.INTERNAL }, { ...empty.Operation(), deployFailureReason: "INTERNAL" });
  m.reads("Operation.deploy_failure_reason: PORT_UNAVAILABLE", { deployFailureReason: w.DeployFailureReason.PORT_UNAVAILABLE }, { ...empty.Operation(), deployFailureReason: "PORT_UNAVAILABLE" });
  m.reads("Operation.deploy_failure_reason: CONTAINER_EXITED", { deployFailureReason: w.DeployFailureReason.CONTAINER_EXITED }, { ...empty.Operation(), deployFailureReason: "CONTAINER_EXITED" });
  m.reads("Operation.deploy_failure_reason: CONTAINER_UNHEALTHY", { deployFailureReason: w.DeployFailureReason.CONTAINER_UNHEALTHY }, { ...empty.Operation(), deployFailureReason: "CONTAINER_UNHEALTHY" });
  m.reads("Operation.deploy_failure_reason: TIMED_OUT", { deployFailureReason: w.DeployFailureReason.TIMED_OUT }, { ...empty.Operation(), deployFailureReason: "TIMED_OUT" });
  m.reads("Operation.deploy_failure_reason: UNCOVERED_IMAGE_VOLUME", { deployFailureReason: w.DeployFailureReason.UNCOVERED_IMAGE_VOLUME }, { ...empty.Operation(), deployFailureReason: "UNCOVERED_IMAGE_VOLUME" });
  m.reads("Operation.deploy_failure_reason: BUILD_MEMORY_UNAVAILABLE", { deployFailureReason: w.DeployFailureReason.BUILD_MEMORY_UNAVAILABLE }, { ...empty.Operation(), deployFailureReason: "BUILD_MEMORY_UNAVAILABLE" });
  m.reads("Operation.deploy_failure_reason: a value newer than the SDK", { deployFailureReason: 9999 as w.DeployFailureReason }, { ...empty.Operation(), deployFailureReason: 9999 });
  m.reads("Operation.made_current", { madeCurrent: true }, { ...empty.Operation(), madeCurrent: true });
  m.reads("Operation.service", { service: "service" }, { ...empty.Operation(), service: "service" });
  m.reads("Operation.failed_exit_code", { failedExitCode: -1010 }, { ...empty.Operation(), failedExitCode: -1010 });
  m.reads("Operation.snapshot_id", { snapshotId: "snapshot_id" }, { ...empty.Operation(), snapshotId: "snapshot_id" });
  m.reads("Operation.restored_volumes", { restoredVolumes: ["restored_volumes", ""] }, { ...empty.Operation(), restoredVolumes: ["restored_volumes", ""] });
  m.reads("Operation.undo_snapshot_id", { undoSnapshotId: "undo_snapshot_id" }, { ...empty.Operation(), undoSnapshotId: "undo_snapshot_id" });
  m.reads("Operation.github_commit", { githubCommit: {} }, { ...empty.Operation(), githubCommit: empty.GithubCommit() });
  m.reads("Operation.archive_name", { archiveName: "archive_name" }, { ...empty.Operation(), archiveName: "archive_name" });
  m.reads("Operation.adjustments", { adjustments: ["adjustments", ""] }, { ...empty.Operation(), adjustments: ["adjustments", ""] });
  m.reads("Operation.changed_paths", { changedPaths: ["changed_paths", ""] }, { ...empty.Operation(), changedPaths: ["changed_paths", ""] });
  m.reads("Operation.changed_path_count", { changedPathCount: 1018 }, { ...empty.Operation(), changedPathCount: 1018 });
  m.reads("Operation.files_kept", { filesKept: true }, { ...empty.Operation(), filesKept: true });
}

{
  const m = reading(w.GetMachineResponseSchema, (leaf: Init<typeof w.SnapshotSchema>): Init<typeof w.GetMachineResponseSchema> => ({ deletedProjects: [{ newestSnapshot: leaf }] }), async (api) => (await api.getMachine({}))?.deletedProjects?.[0]?.newestSnapshot);
  m.reads("Snapshot: nothing set", {}, empty.Snapshot());
  m.reads("Snapshot: a field newer than the SDK", newer(w.SnapshotSchema), empty.Snapshot());
  m.reads("Snapshot.snapshot_id", { snapshotId: "snapshot_id" }, { ...empty.Snapshot(), snapshotId: "snapshot_id" });
  m.reads("Snapshot.create_time", { createTime: { seconds: 1790000000n, nanos: 999600000 } }, { ...empty.Snapshot(), createTime: new Date(1790000000999) });
  m.reads("Snapshot.size_bytes", { sizeBytes: 9007199254740993n }, { ...empty.Snapshot(), sizeBytes: 9007199254740993n });
  m.reads("Snapshot.volumes", { volumes: ["volumes", ""] }, { ...empty.Snapshot(), volumes: ["volumes", ""] });
}

{
  const m = reading(w.QueryHttpTrafficResponseSchema, (leaf: Init<typeof w.HttpTrafficSummarySchema>): Init<typeof w.QueryHttpTrafficResponseSchema> => ({ summary: leaf }), async (api) => (await api.queryHttpTraffic({}))?.summary);
  m.reads("HttpTrafficSummary: nothing set", {}, empty.HttpTrafficSummary());
  m.reads("HttpTrafficSummary: a field newer than the SDK", newer(w.HttpTrafficSummarySchema), empty.HttpTrafficSummary());
  m.reads("HttpTrafficSummary.request_count", { requestCount: 9007199254740993n }, { ...empty.HttpTrafficSummary(), requestCount: 9007199254740993n });
  m.reads("HttpTrafficSummary.server_error_count", { serverErrorCount: 9007199254740993n }, { ...empty.HttpTrafficSummary(), serverErrorCount: 9007199254740993n });
  m.reads("HttpTrafficSummary.latency_p50_ms", { latencyP50Ms: 1003 }, { ...empty.HttpTrafficSummary(), latencyP50Ms: 1003 });
  m.reads("HttpTrafficSummary.latency_p95_ms", { latencyP95Ms: 1004 }, { ...empty.HttpTrafficSummary(), latencyP95Ms: 1004 });
}

{
  const m = reading(w.CreateProjectResponseSchema, (leaf: Init<typeof w.CreateProjectResponseSchema>): Init<typeof w.CreateProjectResponseSchema> => (leaf), async (api) => (await api.createProject({})));
  m.reads("CreateProjectResponse: nothing set", {}, empty.CreateProjectResponse());
  m.reads("CreateProjectResponse: a field newer than the SDK", newer(w.CreateProjectResponseSchema), empty.CreateProjectResponse());
  m.reads("CreateProjectResponse.operation", { operation: {} }, { ...empty.CreateProjectResponse(), operation: empty.Operation() });
  m.reads("CreateProjectResponse.violations", { violations: [{}] }, { ...empty.CreateProjectResponse(), violations: [empty.SpecViolation()] });
  m.reads("CreateProjectResponse.adjustments", { adjustments: ["adjustments", ""] }, { ...empty.CreateProjectResponse(), adjustments: ["adjustments", ""] });
  m.reads("CreateProjectResponse.project", { project: {} }, { ...empty.CreateProjectResponse(), project: empty.Project() });
  m.reads("CreateProjectResponse.log", { log: [{}] }, { ...empty.CreateProjectResponse(), log: [empty.OperationLogLine()] });
}

{
  const m = reading(w.DeployProjectResponseSchema, (leaf: Init<typeof w.DeployProjectResponseSchema>): Init<typeof w.DeployProjectResponseSchema> => (leaf), async (api) => (await api.deployProject({})));
  m.reads("DeployProjectResponse: nothing set", {}, empty.DeployProjectResponse());
  m.reads("DeployProjectResponse: a field newer than the SDK", newer(w.DeployProjectResponseSchema), empty.DeployProjectResponse());
  m.reads("DeployProjectResponse.operation", { operation: {} }, { ...empty.DeployProjectResponse(), operation: empty.Operation() });
  m.reads("DeployProjectResponse.violations", { violations: [{}] }, { ...empty.DeployProjectResponse(), violations: [empty.SpecViolation()] });
  m.reads("DeployProjectResponse.adjustments", { adjustments: ["adjustments", ""] }, { ...empty.DeployProjectResponse(), adjustments: ["adjustments", ""] });
  m.reads("DeployProjectResponse.project", { project: {} }, { ...empty.DeployProjectResponse(), project: empty.Project() });
  m.reads("DeployProjectResponse.log", { log: [{}] }, { ...empty.DeployProjectResponse(), log: [empty.OperationLogLine()] });
}

{
  const m = reading(w.CreateProjectResponseSchema, (leaf: Init<typeof w.SpecViolationSchema>): Init<typeof w.CreateProjectResponseSchema> => ({ violations: [leaf] }), async (api) => (await api.createProject({}))?.violations?.[0]);
  m.reads("SpecViolation: nothing set", {}, empty.SpecViolation());
  m.reads("SpecViolation: a field newer than the SDK", newer(w.SpecViolationSchema), empty.SpecViolation());
  m.reads("SpecViolation.service", { service: "service" }, { ...empty.SpecViolation(), service: "service" });
  m.reads("SpecViolation.location", { location: "location" }, { ...empty.SpecViolation(), location: "location" });
  m.reads("SpecViolation.violation_message", { violationMessage: "violation_message" }, { ...empty.SpecViolation(), violationMessage: "violation_message" });
}

{
  const m = reading(w.ListCommitsResponseSchema, (leaf: Init<typeof w.ListCommitsResponseSchema>): Init<typeof w.ListCommitsResponseSchema> => (leaf), async (api) => (await api.listCommits({})));
  m.reads("ListCommitsResponse: nothing set", {}, empty.ListCommitsResponse());
  m.reads("ListCommitsResponse: a field newer than the SDK", newer(w.ListCommitsResponseSchema), empty.ListCommitsResponse());
  m.reads("ListCommitsResponse.commits", { commits: [{}] }, { ...empty.ListCommitsResponse(), commits: [empty.BranchCommit()] });
  m.reads("ListCommitsResponse.more", { more: true }, { ...empty.ListCommitsResponse(), more: true });
}

{
  const m = reading(w.ListCommitsResponseSchema, (leaf: Init<typeof w.BranchCommitSchema>): Init<typeof w.ListCommitsResponseSchema> => ({ commits: [leaf] }), async (api) => (await api.listCommits({}))?.commits?.[0]);
  m.reads("BranchCommit: nothing set", {}, empty.BranchCommit());
  m.reads("BranchCommit: a field newer than the SDK", newer(w.BranchCommitSchema), empty.BranchCommit());
  m.reads("BranchCommit.commit", { commit: {} }, { ...empty.BranchCommit(), commit: empty.GithubCommit() });
  m.reads("BranchCommit.author", { author: "author" }, { ...empty.BranchCommit(), author: "author" });
  m.reads("BranchCommit.commit_time", { commitTime: { seconds: 1790000000n, nanos: 999600000 } }, { ...empty.BranchCommit(), commitTime: new Date(1790000000999) });
  m.reads("BranchCommit.deployed", { deployed: true }, { ...empty.BranchCommit(), deployed: true });
  m.reads("BranchCommit.last_deploy", { lastDeploy: {} }, { ...empty.BranchCommit(), lastDeploy: empty.Operation() });
  m.reads("BranchCommit.newest", { newest: true }, { ...empty.BranchCommit(), newest: true });
}

{
  const m = reading(w.RunProjectActionResponseSchema, (leaf: Init<typeof w.RunProjectActionResponseSchema>): Init<typeof w.RunProjectActionResponseSchema> => (leaf), async (api) => (await api.runProjectAction({})));
  m.reads("RunProjectActionResponse: nothing set", {}, empty.RunProjectActionResponse());
  m.reads("RunProjectActionResponse: a field newer than the SDK", newer(w.RunProjectActionResponseSchema), empty.RunProjectActionResponse());
  m.reads("RunProjectActionResponse.operation", { operation: {} }, { ...empty.RunProjectActionResponse(), operation: empty.Operation() });
  m.reads("RunProjectActionResponse.project", { project: {} }, { ...empty.RunProjectActionResponse(), project: empty.Project() });
  m.reads("RunProjectActionResponse.log", { log: [{}] }, { ...empty.RunProjectActionResponse(), log: [empty.OperationLogLine()] });
}

{
  const m = reading(w.GetOperationResponseSchema, (leaf: Init<typeof w.GetOperationResponseSchema>): Init<typeof w.GetOperationResponseSchema> => (leaf), async (api) => (await api.getOperation({})));
  m.reads("GetOperationResponse: nothing set", {}, empty.GetOperationResponse());
  m.reads("GetOperationResponse: a field newer than the SDK", newer(w.GetOperationResponseSchema), empty.GetOperationResponse());
  m.reads("GetOperationResponse.operation", { operation: {} }, { ...empty.GetOperationResponse(), operation: empty.Operation() });
  m.reads("GetOperationResponse.project", { project: {} }, { ...empty.GetOperationResponse(), project: empty.Project() });
  m.reads("GetOperationResponse.log", { log: [{}] }, { ...empty.GetOperationResponse(), log: [empty.OperationLogLine()] });
  m.reads("GetOperationResponse.log_line_count", { logLineCount: 1003 }, { ...empty.GetOperationResponse(), logLineCount: 1003 });
  m.reads("GetOperationResponse.next_after_log_line", { nextAfterLogLine: 1004 }, { ...empty.GetOperationResponse(), nextAfterLogLine: 1004 });
}

{
  const m = reading(w.CreateProjectResponseSchema, (leaf: Init<typeof w.OperationLogLineSchema>): Init<typeof w.CreateProjectResponseSchema> => ({ log: [leaf] }), async (api) => (await api.createProject({}))?.log?.[0]);
  m.reads("OperationLogLine: nothing set", {}, empty.OperationLogLine());
  m.reads("OperationLogLine: a field newer than the SDK", newer(w.OperationLogLineSchema), empty.OperationLogLine());
  m.reads("OperationLogLine.time", { time: { seconds: 1790000000n, nanos: 999600000 } }, { ...empty.OperationLogLine(), time: new Date(1790000000999) });
  m.reads("OperationLogLine.text", { text: "text" }, { ...empty.OperationLogLine(), text: "text" });
}

{
  const m = reading(w.QueryHttpTrafficResponseSchema, (leaf: Init<typeof w.QueryHttpTrafficResponseSchema>): Init<typeof w.QueryHttpTrafficResponseSchema> => (leaf), async (api) => (await api.queryHttpTraffic({})));
  m.reads("QueryHttpTrafficResponse: nothing set", {}, empty.QueryHttpTrafficResponse());
  m.reads("QueryHttpTrafficResponse: a field newer than the SDK", newer(w.QueryHttpTrafficResponseSchema), empty.QueryHttpTrafficResponse());
  m.reads("QueryHttpTrafficResponse.start_time", { startTime: { seconds: 1790000000n, nanos: 999600000 } }, { ...empty.QueryHttpTrafficResponse(), startTime: new Date(1790000000999) });
  m.reads("QueryHttpTrafficResponse.end_time", { endTime: { seconds: 1790000000n, nanos: 999600000 } }, { ...empty.QueryHttpTrafficResponse(), endTime: new Date(1790000000999) });
  m.reads("QueryHttpTrafficResponse.oldest_kept_time", { oldestKeptTime: { seconds: 1790000000n, nanos: 999600000 } }, { ...empty.QueryHttpTrafficResponse(), oldestKeptTime: new Date(1790000000999) });
  m.reads("QueryHttpTrafficResponse.summary", { summary: {} }, { ...empty.QueryHttpTrafficResponse(), summary: empty.HttpTrafficSummary() });
  m.reads("QueryHttpTrafficResponse.buckets", { buckets: [{}] }, { ...empty.QueryHttpTrafficResponse(), buckets: [empty.HttpTrafficBucket()] });
  m.reads("QueryHttpTrafficResponse.top_paths", { topPaths: [{}] }, { ...empty.QueryHttpTrafficResponse(), topPaths: [empty.HttpPathTraffic()] });
  m.reads("QueryHttpTrafficResponse.newest_sequence", { newestSequence: 9007199254740993n }, { ...empty.QueryHttpTrafficResponse(), newestSequence: 9007199254740993n });
  m.reads("QueryHttpTrafficResponse.requests", { requests: [{}] }, { ...empty.QueryHttpTrafficResponse(), requests: [empty.HttpRequest()] });
  m.reads("QueryHttpTrafficResponse.next_page_token", { nextPageToken: "next_page_token" }, { ...empty.QueryHttpTrafficResponse(), nextPageToken: "next_page_token" });
  m.reads("QueryHttpTrafficResponse.tail_sequence", { tailSequence: 9007199254740993n }, { ...empty.QueryHttpTrafficResponse(), tailSequence: 9007199254740993n });
}

{
  const m = reading(w.QueryHttpTrafficResponseSchema, (leaf: Init<typeof w.HttpTrafficBucketSchema>): Init<typeof w.QueryHttpTrafficResponseSchema> => ({ buckets: [leaf] }), async (api) => (await api.queryHttpTraffic({}))?.buckets?.[0]);
  m.reads("HttpTrafficBucket: nothing set", {}, empty.HttpTrafficBucket());
  m.reads("HttpTrafficBucket: a field newer than the SDK", newer(w.HttpTrafficBucketSchema), empty.HttpTrafficBucket());
  m.reads("HttpTrafficBucket.start_time", { startTime: { seconds: 1790000000n, nanos: 999600000 } }, { ...empty.HttpTrafficBucket(), startTime: new Date(1790000000999) });
  m.reads("HttpTrafficBucket.summary", { summary: {} }, { ...empty.HttpTrafficBucket(), summary: empty.HttpTrafficSummary() });
}

{
  const m = reading(w.QueryHttpTrafficResponseSchema, (leaf: Init<typeof w.HttpPathTrafficSchema>): Init<typeof w.QueryHttpTrafficResponseSchema> => ({ topPaths: [leaf] }), async (api) => (await api.queryHttpTraffic({}))?.topPaths?.[0]);
  m.reads("HttpPathTraffic: nothing set", {}, empty.HttpPathTraffic());
  m.reads("HttpPathTraffic: a field newer than the SDK", newer(w.HttpPathTrafficSchema), empty.HttpPathTraffic());
  m.reads("HttpPathTraffic.method", { method: "method" }, { ...empty.HttpPathTraffic(), method: "method" });
  m.reads("HttpPathTraffic.path_pattern", { pathPattern: "path_pattern" }, { ...empty.HttpPathTraffic(), pathPattern: "path_pattern" });
  m.reads("HttpPathTraffic.summary", { summary: {} }, { ...empty.HttpPathTraffic(), summary: empty.HttpTrafficSummary() });
}

{
  const m = reading(w.QueryHttpTrafficResponseSchema, (leaf: Init<typeof w.HttpRequestSchema>): Init<typeof w.QueryHttpTrafficResponseSchema> => ({ requests: [leaf] }), async (api) => (await api.queryHttpTraffic({}))?.requests?.[0]);
  m.reads("HttpRequest: nothing set", {}, empty.HttpRequest());
  m.reads("HttpRequest: a field newer than the SDK", newer(w.HttpRequestSchema), empty.HttpRequest());
  m.reads("HttpRequest.sequence", { sequence: 9007199254740993n }, { ...empty.HttpRequest(), sequence: 9007199254740993n });
  m.reads("HttpRequest.finish_time", { finishTime: { seconds: 1790000000n, nanos: 999600000 } }, { ...empty.HttpRequest(), finishTime: new Date(1790000000999) });
  m.reads("HttpRequest.host", { host: "host" }, { ...empty.HttpRequest(), host: "host" });
  m.reads("HttpRequest.method", { method: "method" }, { ...empty.HttpRequest(), method: "method" });
  m.reads("HttpRequest.path", { path: "path" }, { ...empty.HttpRequest(), path: "path" });
  m.reads("HttpRequest.path_pattern", { pathPattern: "path_pattern" }, { ...empty.HttpRequest(), pathPattern: "path_pattern" });
  m.reads("HttpRequest.route_path", { routePath: "route_path" }, { ...empty.HttpRequest(), routePath: "route_path" });
  m.reads("HttpRequest.service", { service: "service" }, { ...empty.HttpRequest(), service: "service" });
  m.reads("HttpRequest.port", { port: 1009 }, { ...empty.HttpRequest(), port: 1009 });
  m.reads("HttpRequest.status_code", { statusCode: 1010 }, { ...empty.HttpRequest(), statusCode: 1010 });
  m.reads("HttpRequest.response_size_bytes", { responseSizeBytes: 9007199254740993n }, { ...empty.HttpRequest(), responseSizeBytes: 9007199254740993n });
  m.reads("HttpRequest.duration_ms", { durationMs: 1012 }, { ...empty.HttpRequest(), durationMs: 1012 });
  m.reads("HttpRequest.service_duration_ms", { serviceDurationMs: 1013 }, { ...empty.HttpRequest(), serviceDurationMs: 1013 });
  m.reads("HttpRequest.client_ip_address", { clientIpAddress: "client_ip_address" }, { ...empty.HttpRequest(), clientIpAddress: "client_ip_address" });
  m.reads("HttpRequest.user_agent", { userAgent: "user_agent" }, { ...empty.HttpRequest(), userAgent: "user_agent" });
}

{
  const m = reading(w.QueryContainerLogsResponseSchema, (leaf: Init<typeof w.QueryContainerLogsResponseSchema>): Init<typeof w.QueryContainerLogsResponseSchema> => (leaf), async (api) => (await api.queryContainerLogs({})));
  m.reads("QueryContainerLogsResponse: nothing set", {}, empty.QueryContainerLogsResponse());
  m.reads("QueryContainerLogsResponse: a field newer than the SDK", newer(w.QueryContainerLogsResponseSchema), empty.QueryContainerLogsResponse());
  m.reads("QueryContainerLogsResponse.start_time", { startTime: { seconds: 1790000000n, nanos: 999600000 } }, { ...empty.QueryContainerLogsResponse(), startTime: new Date(1790000000999) });
  m.reads("QueryContainerLogsResponse.end_time", { endTime: { seconds: 1790000000n, nanos: 999600000 } }, { ...empty.QueryContainerLogsResponse(), endTime: new Date(1790000000999) });
  m.reads("QueryContainerLogsResponse.oldest_kept_time", { oldestKeptTime: { seconds: 1790000000n, nanos: 999600000 } }, { ...empty.QueryContainerLogsResponse(), oldestKeptTime: new Date(1790000000999) });
  m.reads("QueryContainerLogsResponse.lines", { lines: [{}] }, { ...empty.QueryContainerLogsResponse(), lines: [empty.LogLine()] });
  m.reads("QueryContainerLogsResponse.next_page_token", { nextPageToken: "next_page_token" }, { ...empty.QueryContainerLogsResponse(), nextPageToken: "next_page_token" });
  m.reads("QueryContainerLogsResponse.tail_cursor", { tailCursor: "tail_cursor" }, { ...empty.QueryContainerLogsResponse(), tailCursor: "tail_cursor" });
}

{
  const m = reading(w.QueryContainerLogsResponseSchema, (leaf: Init<typeof w.LogLineSchema>): Init<typeof w.QueryContainerLogsResponseSchema> => ({ lines: [leaf] }), async (api) => (await api.queryContainerLogs({}))?.lines?.[0]);
  m.reads("LogLine: nothing set", {}, empty.LogLine());
  m.reads("LogLine: a field newer than the SDK", newer(w.LogLineSchema), empty.LogLine());
  m.reads("LogLine.time", { time: { seconds: 1790000000n, nanos: 999600000 } }, { ...empty.LogLine(), time: new Date(1790000000999) });
  m.reads("LogLine.service", { service: "service" }, { ...empty.LogLine(), service: "service" });
  m.reads("LogLine.stream: STDOUT", { stream: w.OutputStream.STDOUT }, { ...empty.LogLine(), stream: "STDOUT" });
  m.reads("LogLine.stream: STDERR", { stream: w.OutputStream.STDERR }, { ...empty.LogLine(), stream: "STDERR" });
  m.reads("LogLine.stream: a value newer than the SDK", { stream: 9999 as w.OutputStream }, { ...empty.LogLine(), stream: 9999 });
  m.reads("LogLine.text", { text: "text" }, { ...empty.LogLine(), text: "text" });
}

{
  const m = reading(w.RunServiceCommandResponseSchema, (leaf: Init<typeof w.RunServiceCommandResponseSchema>): Init<typeof w.RunServiceCommandResponseSchema> => (leaf), async (api) => (await api.runServiceCommand({})));
  m.reads("RunServiceCommandResponse: nothing set", {}, empty.RunServiceCommandResponse());
  m.reads("RunServiceCommandResponse: a field newer than the SDK", newer(w.RunServiceCommandResponseSchema), empty.RunServiceCommandResponse());
  m.reads("RunServiceCommandResponse.exit_code", { exitCode: -1001 }, { ...empty.RunServiceCommandResponse(), exitCode: -1001 });
  m.reads("RunServiceCommandResponse.timed_out", { timedOut: true }, { ...empty.RunServiceCommandResponse(), timedOut: true });
  m.reads("RunServiceCommandResponse.stdout", { stdout: "stdout" }, { ...empty.RunServiceCommandResponse(), stdout: "stdout" });
  m.reads("RunServiceCommandResponse.stderr", { stderr: "stderr" }, { ...empty.RunServiceCommandResponse(), stderr: "stderr" });
  m.reads("RunServiceCommandResponse.output_truncated", { outputTruncated: true }, { ...empty.RunServiceCommandResponse(), outputTruncated: true });
}

{
  const m = reading(w.ReadPathResponseSchema, (leaf: Init<typeof w.FileEntrySchema>): Init<typeof w.ReadPathResponseSchema> => ({ entry: leaf }), async (api) => (await api.readPath({}))?.entry);
  m.reads("FileEntry: nothing set", {}, empty.FileEntry());
  m.reads("FileEntry: a field newer than the SDK", newer(w.FileEntrySchema), empty.FileEntry());
  m.reads("FileEntry.name", { name: "name" }, { ...empty.FileEntry(), name: "name" });
  m.reads("FileEntry.type: FILE", { type: w.FileType.FILE }, { ...empty.FileEntry(), type: "FILE" });
  m.reads("FileEntry.type: DIRECTORY", { type: w.FileType.DIRECTORY }, { ...empty.FileEntry(), type: "DIRECTORY" });
  m.reads("FileEntry.type: SYMLINK", { type: w.FileType.SYMLINK }, { ...empty.FileEntry(), type: "SYMLINK" });
  m.reads("FileEntry.type: OTHER", { type: w.FileType.OTHER }, { ...empty.FileEntry(), type: "OTHER" });
  m.reads("FileEntry.type: a value newer than the SDK", { type: 9999 as w.FileType }, { ...empty.FileEntry(), type: 9999 });
  m.reads("FileEntry.size_bytes", { sizeBytes: 9007199254740993n }, { ...empty.FileEntry(), sizeBytes: 9007199254740993n });
  m.reads("FileEntry.modify_time", { modifyTime: { seconds: 1790000000n, nanos: 999600000 } }, { ...empty.FileEntry(), modifyTime: new Date(1790000000999) });
  m.reads("FileEntry.mode", { mode: "mode" }, { ...empty.FileEntry(), mode: "mode" });
  m.reads("FileEntry.owner_uid", { ownerUid: 1006 }, { ...empty.FileEntry(), ownerUid: 1006 });
  m.reads("FileEntry.owner_gid", { ownerGid: 1007 }, { ...empty.FileEntry(), ownerGid: 1007 });
  m.reads("FileEntry.symlink_target", { symlinkTarget: "symlink_target" }, { ...empty.FileEntry(), symlinkTarget: "symlink_target" });
}

{
  const m = reading(w.ReadPathResponseSchema, (leaf: Init<typeof w.ReadPathResponseSchema>): Init<typeof w.ReadPathResponseSchema> => (leaf), async (api) => (await api.readPath({})));
  m.reads("ReadPathResponse: nothing set", {}, empty.ReadPathResponse());
  m.reads("ReadPathResponse: a field newer than the SDK", newer(w.ReadPathResponseSchema), empty.ReadPathResponse());
  m.reads("ReadPathResponse.entry", { entry: {} }, { ...empty.ReadPathResponse(), entry: empty.FileEntry() });
  m.reads("ReadPathResponse.location: CONTAINER", { location: w.FileLocation.CONTAINER }, { ...empty.ReadPathResponse(), location: "CONTAINER" });
  m.reads("ReadPathResponse.location: VOLUME", { location: w.FileLocation.VOLUME }, { ...empty.ReadPathResponse(), location: "VOLUME" });
  m.reads("ReadPathResponse.location: PROJECT_FILES", { location: w.FileLocation.PROJECT_FILES }, { ...empty.ReadPathResponse(), location: "PROJECT_FILES" });
  m.reads("ReadPathResponse.location: a value newer than the SDK", { location: 9999 as w.FileLocation }, { ...empty.ReadPathResponse(), location: 9999 });
  m.reads("ReadPathResponse.volume", { volume: "volume" }, { ...empty.ReadPathResponse(), volume: "volume" });
  m.reads("ReadPathResponse.entries", { entries: [{}] }, { ...empty.ReadPathResponse(), entries: [empty.FileEntry()] });
  m.reads("ReadPathResponse.entry_count", { entryCount: 1004 }, { ...empty.ReadPathResponse(), entryCount: 1004 });
  m.reads("ReadPathResponse.next_entry_page_token", { nextEntryPageToken: "next_entry_page_token" }, { ...empty.ReadPathResponse(), nextEntryPageToken: "next_entry_page_token" });
  m.reads("ReadPathResponse.text", { text: "text" }, { ...empty.ReadPathResponse(), text: "text" });
  m.reads("ReadPathResponse.binary", { binary: true }, { ...empty.ReadPathResponse(), binary: true });
  m.reads("ReadPathResponse.next_offset_bytes", { nextOffsetBytes: 9007199254740993n }, { ...empty.ReadPathResponse(), nextOffsetBytes: 9007199254740993n });
  m.reads("ReadPathResponse.deploy_id", { deployId: "deploy_id" }, { ...empty.ReadPathResponse(), deployId: "deploy_id" });
}

{
  const m = reading(w.CreateTransferResponseSchema, (leaf: Init<typeof w.CreateTransferResponseSchema>): Init<typeof w.CreateTransferResponseSchema> => (leaf), async (api) => (await api.createTransfer({})));
  m.reads("CreateTransferResponse: nothing set", {}, empty.CreateTransferResponse());
  m.reads("CreateTransferResponse: a field newer than the SDK", newer(w.CreateTransferResponseSchema), empty.CreateTransferResponse());
  m.reads("CreateTransferResponse.url", { url: "url" }, { ...empty.CreateTransferResponse(), url: "url" });
  m.reads("CreateTransferResponse.http_method", { httpMethod: "http_method" }, { ...empty.CreateTransferResponse(), httpMethod: "http_method" });
  m.reads("CreateTransferResponse.expire_time", { expireTime: { seconds: 1790000000n, nanos: 999600000 } }, { ...empty.CreateTransferResponse(), expireTime: new Date(1790000000999) });
  m.reads("CreateTransferResponse.command", { command: "command" }, { ...empty.CreateTransferResponse(), command: "command" });
  m.reads("CreateTransferResponse.upload_id", { uploadId: "upload_id" }, { ...empty.CreateTransferResponse(), uploadId: "upload_id" });
  m.reads("CreateTransferResponse.replaces", { replaces: true }, { ...empty.CreateTransferResponse(), replaces: true });
  m.reads("CreateTransferResponse.file_name", { fileName: "file_name" }, { ...empty.CreateTransferResponse(), fileName: "file_name" });
  m.reads("CreateTransferResponse.exclude_names", { excludeNames: ["exclude_names", ""] }, { ...empty.CreateTransferResponse(), excludeNames: ["exclude_names", ""] });
}

{
  const m = readingDetail(w.ProjectBusySchema, (leaf: Init<typeof w.ProjectBusySchema>): Init<typeof w.ProjectBusySchema> => (leaf), anyCall, (error) => error.projectBusy);
  m.reads("ProjectBusy: nothing set", {}, empty.ProjectBusy());
  m.reads("ProjectBusy: a field newer than the SDK", newer(w.ProjectBusySchema), empty.ProjectBusy());
  m.reads("ProjectBusy.operation_id", { operationId: "operation_id" }, { ...empty.ProjectBusy(), operationId: "operation_id" });
  m.reads("ProjectBusy.kind: DEPLOY", { kind: w.OperationKind.DEPLOY }, { ...empty.ProjectBusy(), kind: "DEPLOY" });
  m.reads("ProjectBusy.kind: RECREATE_SERVICE", { kind: w.OperationKind.RECREATE_SERVICE }, { ...empty.ProjectBusy(), kind: "RECREATE_SERVICE" });
  m.reads("ProjectBusy.kind: BACKUP", { kind: w.OperationKind.BACKUP }, { ...empty.ProjectBusy(), kind: "BACKUP" });
  m.reads("ProjectBusy.kind: RESTORE", { kind: w.OperationKind.RESTORE }, { ...empty.ProjectBusy(), kind: "RESTORE" });
  m.reads("ProjectBusy.kind: DELETE", { kind: w.OperationKind.DELETE }, { ...empty.ProjectBusy(), kind: "DELETE" });
  m.reads("ProjectBusy.kind: a value newer than the SDK", { kind: 9999 as w.OperationKind }, { ...empty.ProjectBusy(), kind: 9999 });
  m.reads("ProjectBusy.start_time", { startTime: { seconds: 1790000000n, nanos: 999600000 } }, { ...empty.ProjectBusy(), startTime: new Date(1790000000999) });
}

{
  const m = readingDetail(w.ProjectChangedSchema, (leaf: Init<typeof w.ProjectChangedSchema>): Init<typeof w.ProjectChangedSchema> => (leaf), anyCall, (error) => error.projectChanged);
  m.reads("ProjectChanged: nothing set", {}, empty.ProjectChanged());
  m.reads("ProjectChanged: a field newer than the SDK", newer(w.ProjectChangedSchema), empty.ProjectChanged());
}

{
  const m = readingDetail(w.MachineUnreachableSchema, (leaf: Init<typeof w.MachineUnreachableSchema>): Init<typeof w.MachineUnreachableSchema> => (leaf), anyCall, (error) => error.machineUnreachable);
  m.reads("MachineUnreachable: nothing set", {}, empty.MachineUnreachable());
  m.reads("MachineUnreachable: a field newer than the SDK", newer(w.MachineUnreachableSchema), empty.MachineUnreachable());
}

{
  const m = readingDetail(w.NoMachineSchema, (leaf: Init<typeof w.NoMachineSchema>): Init<typeof w.NoMachineSchema> => (leaf), anyCall, (error) => error.noMachine);
  m.reads("NoMachine: nothing set", {}, empty.NoMachine());
  m.reads("NoMachine: a field newer than the SDK", newer(w.NoMachineSchema), empty.NoMachine());
  m.reads("NoMachine.reason: NO_PLAN", { reason: w.NoMachineReason.NO_PLAN }, { ...empty.NoMachine(), reason: "NO_PLAN" });
  m.reads("NoMachine.reason: BEING_PREPARED", { reason: w.NoMachineReason.BEING_PREPARED }, { ...empty.NoMachine(), reason: "BEING_PREPARED" });
  m.reads("NoMachine.reason: a value newer than the SDK", { reason: 9999 as w.NoMachineReason }, { ...empty.NoMachine(), reason: 9999 });
  m.reads("NoMachine.url", { url: "url" }, { ...empty.NoMachine(), url: "url" });
}

{
  const m = reading(w.WatchOperationResponseSchema, (leaf: Init<typeof w.WatchOperationResponseSchema>): Init<typeof w.WatchOperationResponseSchema> => (leaf), async (api) => (await first(api.watchOperation({}))));
  m.reads("WatchOperationResponse: a field or a oneof's member newer than the SDK", newer(w.WatchOperationResponseSchema), empty.WatchOperationResponse());
  m.reads("WatchOperationResponse.log", { message: { case: "log", value: {} } }, { ...empty.WatchOperationResponse(), message: "log", log: empty.OperationLogLine() });
  m.reads("WatchOperationResponse.finished_operation", { message: { case: "finishedOperation", value: {} } }, { ...empty.WatchOperationResponse(), message: "finishedOperation", finishedOperation: empty.Operation() });
}

{
  const m = reading(w.TailContainerLogsResponseSchema, (leaf: Init<typeof w.TailContainerLogsResponseSchema>): Init<typeof w.TailContainerLogsResponseSchema> => (leaf), async (api) => (await first(api.tailContainerLogs({}))));
  m.reads("TailContainerLogsResponse: a field newer than the SDK", newer(w.TailContainerLogsResponseSchema), empty.TailContainerLogsResponse());
  m.reads("TailContainerLogsResponse.line", { line: {} }, { ...empty.TailContainerLogsResponse(), line: empty.LogLine() });
  m.reads("TailContainerLogsResponse.cursor", { cursor: "cursor" }, { ...empty.TailContainerLogsResponse(), cursor: "cursor" });
}

{
  const m = reading(w.TailHttpTrafficResponseSchema, (leaf: Init<typeof w.TailHttpTrafficResponseSchema>): Init<typeof w.TailHttpTrafficResponseSchema> => (leaf), async (api) => (await first(api.tailHttpTraffic({}))));
  m.reads("TailHttpTrafficResponse: a field newer than the SDK", newer(w.TailHttpTrafficResponseSchema), empty.TailHttpTrafficResponse());
  m.reads("TailHttpTrafficResponse.request", { request: {} }, { ...empty.TailHttpTrafficResponse(), request: empty.HttpRequest() });
}

