// Code generated by protoc-gen-panel-typescript from v1/panel.proto. DO NOT EDIT.
//
// What the types say, checked by compiling this file (`tsc -p test`); it is never run. Which
// keys of each message may be absent; that two members of a oneof do not compile; that a
// response's member is there only once its tag says so; that a message read from a response
// is one a request takes. An `@ts-expect-error` that finds no error is itself one.
import type * as p from "pethost";

/** Takes, for every key of T, whether it may be absent. */
declare function optional<T>(keys: { [K in keyof T]-?: {} extends Pick<T, K> ? true : false }): void;
/** Takes a T. */
declare function accepts<T>(value: T): void;
/** Gives a T. */
declare function a<T>(): T;

optional<p.GetMachineResponse>({ machine: true, projects: false, deletedProjects: false, github: true });
optional<p.Machine>({ name: false, location: false, sampleTime: true, cpuUsedCores: false, cpuTotalCores: false, memoryUsedBytes: false, memoryTotalBytes: false, diskUsedBytes: false, diskTotalBytes: false, diskUsage: true, hostname: false, sshHostKeyFingerprint: false, sshKeys: false, backupsEnabled: false, snapshotListTime: true, snapshotListFailureMessage: false, backupRetentionHours: false, acmeEnabled: false, appsDomain: false, daemonVersion: false, dockerVersion: false, bootTime: true, restartRequiredTime: true, scheduledRestartTime: true, sessions: false });
optional<p.MachineSession>({ sessionId: false, kind: true, projectId: false, service: false, port: false, startTime: true, clientAddress: false, sshKeyLabel: false, sshKeyFingerprint: false });
optional<p.DiskUsage>({ imagesBytes: false, buildCacheBytes: true, volumesBytes: false, containerLayersBytes: false, projectFilesBytes: false, containerLogsBytes: false, httpTrafficBytes: false });
accepts<p.SshKeyInput>(a<p.SshKey>());
optional<p.SshKey>({ publicKey: false, label: false, fingerprint: false });
optional<p.SshKeyInput>({ publicKey: true, label: true, fingerprint: true });
optional<p.GithubConnection>({ appName: false, installUrl: false, repositories: false, repositoryCount: false, webhooksEnabled: false });
optional<p.GithubRepository>({ repository: false, defaultBranch: false, private: false, pushTime: true });
optional<p.DeletedProject>({ projectId: false, newestSnapshot: true, snapshotCount: false });
// @ts-expect-error two members of pethost.panel.v1.RunMachineActionRequest.action
accepts<p.RunMachineActionRequest>({ addSshKey: {}, removeSshKeyFingerprint: "remove_ssh_key_fingerprint" });
optional<p.RestartMachineActionInput>({ restartTime: true, atMaintenanceWindow: true, interruptOperations: true });
optional<p.RunMachineActionResponse>({ machine: true });
accepts<p.ProjectMetadataInput>(a<p.ProjectMetadata>());
optional<p.ProjectMetadata>({ name: true, emoji: true, description: true, notes: true });
optional<p.ProjectMetadataInput>({ name: true, emoji: true, description: true, notes: true });
optional<p.ProjectSummary>({ projectId: false, metadata: true, problems: false, services: false, url: false, hosts: false, httpTrafficLastDay: true, cpuUsedCores: false, memoryUsedBytes: false, deployTime: true, runningOperations: false, pinned: false, diskUsedBytes: false });
optional<p.ServiceSummary>({ service: false, state: true });
optional<p.ProjectProblem>({ kind: true, service: false, operationId: false, sinceTime: true, problemMessage: false });
optional<p.GetProjectRequest>({ projectId: true, includeSecretValues: true, snapshotsBefore: true, snapshotsVolume: true });
optional<p.GetProjectResponse>({ project: true });
optional<p.Project>({ projectId: false, metadata: true, problems: false, url: false, cpuUsedCores: false, memoryUsedBytes: false, deployId: false, deployStatus: true, deployTime: true, xPethostAppliesAtOnce: false, services: false, volumes: false, routes: false, hosts: false, passwordProtected: false, operations: false, snapshots: false, snapshotCount: false, snapshotListTime: true, httpTrafficLastDay: true, source: true, runningServicesAction: true });
optional<p.RunningServicesAction>({ kind: true, services: false, startTime: true });
accepts<p.ProjectSourceInput>(a<p.ProjectSource>());
{
  const read = a<p.ProjectSource>();
  if (read.kind === "files") accepts<boolean>(read.files);
  // @ts-expect-error files is there only when kind says so
  accepts<boolean>(read.files);
}
{
  const read = a<p.ProjectSource>();
  if (read.kind === "github") accepts<p.GithubSource>(read.github);
  // @ts-expect-error github is there only when kind says so
  accepts<p.GithubSource>(read.github);
}
// @ts-expect-error two members of pethost.panel.v1.ProjectSource.kind
accepts<p.ProjectSourceInput>({ files: true, github: {} });
accepts<p.GithubSourceInput>(a<p.GithubSource>());
optional<p.GithubSource>({ repository: true, branch: true, directory: true, autoDeploy: true, newestCommit: true, deployedCommit: true, pinned: false, autoDeployPending: false });
optional<p.GithubSourceInput>({ repository: true, branch: true, directory: true, autoDeploy: true, newestCommit: true, deployedCommit: true, pinned: true, autoDeployPending: true });
accepts<p.GithubCommitInput>(a<p.GithubCommit>());
optional<p.GithubCommit>({ sha: false, title: false, url: false });
optional<p.GithubCommitInput>({ sha: true, title: true, url: true });
optional<p.Service>({ service: false, state: true, containerRunning: false, image: false, buildsImage: false, imageDigest: false, imageSizeBytes: false, command: false, runAsUser: false, startTime: true, finishTime: true, exitCode: true, outOfMemory: false, restartCount: false, cpuUsedCores: false, memoryUsedBytes: false, memoryLimitBytes: false, cpuLimitCores: false, writableLayerBytes: false, ports: false, listeningPorts: false, publishedPorts: false, volumeMounts: false, restartPolicy: true, healthCheck: true, environment: false, envFiles: false, sshCommand: false });
optional<p.PublishedPort>({ machinePort: false, containerPort: false, protocol: false, machineOnly: false });
optional<p.VolumeMount>({ volume: false, containerPath: false });
optional<p.HealthCheck>({ command: false, intervalSeconds: false, status: true, consecutiveFailureCount: false, recentResultsPassed: false, lastFailureOutput: false });
optional<p.EnvironmentVariable>({ name: false, value: false, secret: false, sourceFile: false, fromEnvFileVariables: false, valueLeftOut: false });
optional<p.Volume>({ volume: false, sizeBytes: false, mountedBy: false, lastBackupTime: true, snapshotCount: false, declared: false });
optional<p.VolumeMountedBy>({ service: false, containerPath: false });
optional<p.Host>({ host: false, url: false, certificateSource: true, certificateExpireTime: true, unavailableMessage: false });
accepts<p.RouteInput>(a<p.Route>());
optional<p.Route>({ host: false, path: false, service: false, port: false, stripPath: false });
optional<p.RouteInput>({ host: true, path: true, service: true, port: true, stripPath: true });
optional<p.Operation>({ operationId: false, kind: true, status: true, startTime: true, finishTime: true, failureMessage: false, deployFailureReason: true, madeCurrent: false, service: false, failedExitCode: false, snapshotId: false, restoredVolumes: false, undoSnapshotId: false, githubCommit: true, archiveName: false, adjustments: false, changedPaths: false, changedPathCount: false, filesKept: false });
optional<p.Snapshot>({ snapshotId: false, createTime: true, sizeBytes: false, volumes: false });
optional<p.HttpTrafficSummary>({ requestCount: false, serverErrorCount: false, latencyP50Ms: false, latencyP95Ms: false });
optional<p.CreateProjectRequest>({ projectId: true, source: true, uploadId: true, files: true, xPethost: true, timeoutSeconds: true, operationId: true, waitSeconds: true });
optional<p.CreateProjectResponse>({ operation: true, violations: false, adjustments: false, project: true, log: false });
// @ts-expect-error two members of pethost.panel.v1.DeployProjectRequest.version
accepts<p.DeployProjectRequest>({ uploadId: "upload_id", commit: "commit" });
optional<p.MountVolumeInput>({ service: true, volume: true, containerPath: true });
optional<p.ProjectExtensionInput>({ metadata: true, routes: true, removeRoutes: true, password: true, removePassword: true });
// @ts-expect-error two members of pethost.panel.v1.FileChange.change
accepts<p.FileChangeInput>({ text: "text", data: new Uint8Array([0, 255, 3]) });
optional<p.DeployProjectResponse>({ operation: true, violations: false, adjustments: false, project: true, log: false });
optional<p.SpecViolation>({ service: false, location: false, violationMessage: false });
optional<p.ListCommitsRequest>({ projectId: true, beforeCommit: true });
optional<p.ListCommitsResponse>({ commits: false, more: false });
optional<p.BranchCommit>({ commit: true, author: false, commitTime: true, deployed: false, lastDeploy: true, newest: false });
// @ts-expect-error two members of pethost.panel.v1.RunProjectActionRequest.action
accepts<p.RunProjectActionRequest>({ startServices: {}, stopServices: {} });
optional<p.ServicesActionInput>({ services: true });
optional<p.RecreateServiceActionInput>({ service: true, pullLatestImage: true });
optional<p.RestoreSnapshotActionInput>({ snapshotId: true, volumes: true });
optional<p.CancelOperationActionInput>({ operationId: true });
optional<p.DeleteProjectActionInput>({ skipFinalBackup: true });
optional<p.RunProjectActionResponse>({ operation: true, project: true, log: false });
optional<p.GetOperationRequest>({ projectId: true, operationId: true, waitSeconds: true, afterLogLine: true, logLineLimit: true });
optional<p.GetOperationResponse>({ operation: true, project: true, log: false, logLineCount: false, nextAfterLogLine: false });
optional<p.OperationLogLine>({ time: true, text: false });
optional<p.HttpTrafficFilterInput>({ host: true, method: true, pathContains: true, pathPattern: true, statusClass: true });
optional<p.QueryHttpTrafficRequest>({ projectId: true, filter: true, startTime: true, endTime: true, lastSeconds: true, bucketWidthSeconds: true, requestLimit: true, pageToken: true });
optional<p.QueryHttpTrafficResponse>({ startTime: true, endTime: true, oldestKeptTime: true, summary: true, buckets: false, topPaths: false, newestSequence: false, requests: false, nextPageToken: false, tailSequence: false });
optional<p.HttpTrafficBucket>({ startTime: true, summary: true });
optional<p.HttpPathTraffic>({ method: false, pathPattern: false, summary: true });
optional<p.HttpRequest>({ sequence: false, finishTime: true, host: false, method: false, path: false, pathPattern: false, routePath: false, service: false, port: false, statusCode: false, responseSizeBytes: false, durationMs: false, serviceDurationMs: false, clientIpAddress: false, userAgent: false });
optional<p.ContainerLogFilterInput>({ service: true, stream: true, textContains: true });
optional<p.QueryContainerLogsRequest>({ projectId: true, filter: true, startTime: true, endTime: true, lastSeconds: true, limit: true, fromStart: true, pageToken: true });
optional<p.QueryContainerLogsResponse>({ startTime: true, endTime: true, oldestKeptTime: true, lines: false, nextPageToken: false, tailCursor: false });
optional<p.LogLine>({ time: true, service: false, stream: true, text: false });
optional<p.RunServiceCommandRequest>({ projectId: true, service: true, command: true, stdin: true, runAsUser: true, workingDirectory: true, timeoutSeconds: true });
optional<p.RunServiceCommandResponse>({ exitCode: false, timedOut: false, stdout: false, stderr: false, outputTruncated: false });
optional<p.FileEntry>({ name: false, type: true, sizeBytes: false, modifyTime: true, mode: false, ownerUid: false, ownerGid: false, symlinkTarget: false });
// @ts-expect-error two members of pethost.panel.v1.ReadPathRequest.root
accepts<p.ReadPathRequest>({ service: "service", volume: "volume" });
optional<p.ReadPathResponse>({ entry: true, location: true, volume: false, entries: false, entryCount: false, nextEntryPageToken: false, text: false, binary: false, nextOffsetBytes: false, deployId: false });
// @ts-expect-error two members of pethost.panel.v1.CreateTransferRequest.transfer
accepts<p.CreateTransferRequest>({ uploadArchive: {}, uploadFile: {} });
optional<p.ArchiveUploadInput>({ fileName: true });
// @ts-expect-error two members of pethost.panel.v1.FileUpload.root
accepts<p.FileUploadInput>({ service: "service", volume: "volume" });
// @ts-expect-error two members of pethost.panel.v1.PathDownload.root
accepts<p.PathDownloadInput>({ service: "service", volume: "volume" });
optional<p.CreateTransferResponse>({ url: false, httpMethod: false, expireTime: true, command: false, uploadId: false, replaces: false, fileName: false });
optional<p.ProjectBusy>({ operationId: false, kind: true, startTime: true });
optional<p.NoMachine>({ reason: true, url: false });

