// Code generated by protoc-gen-panel-go from v1/panel.proto. DO NOT EDIT.

package pethost

import (
	"github.com/pethost-dev/sdk/go/internal/panelv1"
)

func toWireGetMachineRequest(v GetMachineRequest) *panelv1.GetMachineRequest {
	b := panelv1.GetMachineRequest_builder{}
	return b.Build()
}

func fromWireGetMachineResponse(w *panelv1.GetMachineResponse) GetMachineResponse {
	return GetMachineResponse{
		pointerFromWire(w.GetMachine(), fromWireMachine),
		sliceFromWire(w.GetProjects(), fromWireProjectSummary),
		sliceFromWire(w.GetDeletedProjects(), fromWireDeletedProject),
		pointerFromWire(w.GetGithub(), fromWireGithubConnection),
	}
}

func fromWireMachine(w *panelv1.Machine) Machine {
	return Machine{
		w.GetName(),
		w.GetLocation(),
		timeFromWire(w.GetSampleTime()),
		w.GetCpuUsedCores(),
		w.GetCpuTotalCores(),
		w.GetMemoryUsedBytes(),
		w.GetMemoryTotalBytes(),
		w.GetDiskUsedBytes(),
		w.GetDiskTotalBytes(),
		pointerFromWire(w.GetDiskUsage(), fromWireDiskUsage),
		w.GetHostname(),
		w.GetSshHostKeyFingerprint(),
		sliceFromWire(w.GetSshKeys(), fromWireSSHKey),
		w.GetBackupsEnabled(),
		timeFromWire(w.GetSnapshotListTime()),
		w.GetSnapshotListFailureMessage(),
		w.GetBackupRetentionHours(),
		w.GetAcmeEnabled(),
		w.GetAppsDomain(),
		w.GetDaemonVersion(),
		w.GetDockerVersion(),
		timeFromWire(w.GetBootTime()),
		timeFromWire(w.GetRestartRequiredTime()),
		timeFromWire(w.GetScheduledRestartTime()),
		sliceFromWire(w.GetSessions(), fromWireMachineSession),
	}
}

func fromWireMachineSession(w *panelv1.MachineSession) MachineSession {
	return MachineSession{
		w.GetSessionId(),
		fromWireMachineSessionKind(w.GetKind()),
		w.GetProjectId(),
		w.GetService(),
		w.GetPort(),
		timeFromWire(w.GetStartTime()),
		w.GetClientAddress(),
		w.GetSshKeyLabel(),
		w.GetSshKeyFingerprint(),
	}
}

func fromWireDiskUsage(w *panelv1.DiskUsage) DiskUsage {
	return DiskUsage{
		w.GetImagesBytes(),
		optional(w.HasBuildCacheBytes(), w.GetBuildCacheBytes()),
		w.GetVolumesBytes(),
		w.GetContainerLayersBytes(),
		w.GetProjectFilesBytes(),
		w.GetContainerLogsBytes(),
		w.GetHttpTrafficBytes(),
	}
}

func fromWireSSHKey(w *panelv1.SshKey) SSHKey {
	return SSHKey{
		w.GetPublicKey(),
		w.GetLabel(),
		w.GetFingerprint(),
		unknownOf(w),
	}
}

func toWireSSHKey(v SSHKey) *panelv1.SshKey {
	b := panelv1.SshKey_builder{
		PublicKey:   nonZero(v.PublicKey),
		Label:       nonZero(v.Label),
		Fingerprint: nonZero(v.Fingerprint),
	}
	return withUnknown(b.Build(), v.unknown)
}

func fromWireGithubConnection(w *panelv1.GithubConnection) GithubConnection {
	return GithubConnection{
		w.GetAppName(),
		w.GetInstallUrl(),
		sliceFromWire(w.GetRepositories(), fromWireGithubRepository),
		w.GetRepositoryCount(),
		w.GetWebhooksEnabled(),
	}
}

func fromWireGithubRepository(w *panelv1.GithubRepository) GithubRepository {
	return GithubRepository{
		w.GetRepository(),
		w.GetDefaultBranch(),
		w.GetPrivate(),
		timeFromWire(w.GetPushTime()),
	}
}

func fromWireDeletedProject(w *panelv1.DeletedProject) DeletedProject {
	return DeletedProject{
		w.GetProjectId(),
		pointerFromWire(w.GetNewestSnapshot(), fromWireSnapshot),
		w.GetSnapshotCount(),
	}
}

func toWireRunMachineActionRequest(v RunMachineActionRequest) *panelv1.RunMachineActionRequest {
	b := panelv1.RunMachineActionRequest_builder{}
	if v.Action != nil {
		v.Action.toRunMachineActionAction(&b)
	}
	return b.Build()
}

func (v RunMachineActionAddSSHKey) toRunMachineActionAction(b *panelv1.RunMachineActionRequest_builder) {
	b.AddSshKey = toWireSSHKey(SSHKey(v))
}

func (v RunMachineActionRemoveSSHKeyFingerprint) toRunMachineActionAction(b *panelv1.RunMachineActionRequest_builder) {
	b.RemoveSshKeyFingerprint = new(string(v))
}

func (v RunMachineActionRestartMachine) toRunMachineActionAction(b *panelv1.RunMachineActionRequest_builder) {
	b.RestartMachine = toWireRestartMachineAction(RestartMachineAction(v))
}

func (v RunMachineActionCancelRestart) toRunMachineActionAction(b *panelv1.RunMachineActionRequest_builder) {
	b.CancelRestart = new(bool(v))
}

func (v RunMachineActionEndSessionID) toRunMachineActionAction(b *panelv1.RunMachineActionRequest_builder) {
	b.EndSessionId = new(string(v))
}

var (
	_ RunMachineActionAction = RunMachineActionAddSSHKey{}
	_ RunMachineActionAction = RunMachineActionRemoveSSHKeyFingerprint("")
	_ RunMachineActionAction = RunMachineActionRestartMachine{}
	_ RunMachineActionAction = RunMachineActionCancelRestart(false)
	_ RunMachineActionAction = RunMachineActionEndSessionID("")
)

func toWireRestartMachineAction(v RestartMachineAction) *panelv1.RestartMachineAction {
	b := panelv1.RestartMachineAction_builder{
		RestartTime:         timeToWire(v.RestartTime),
		AtMaintenanceWindow: nonZero(v.AtMaintenanceWindow),
		InterruptOperations: nonZero(v.InterruptOperations),
	}
	return b.Build()
}

func fromWireRunMachineActionResponse(w *panelv1.RunMachineActionResponse) RunMachineActionResponse {
	return RunMachineActionResponse{
		pointerFromWire(w.GetMachine(), fromWireMachine),
	}
}

func fromWireProjectMetadata(w *panelv1.ProjectMetadata) ProjectMetadata {
	return ProjectMetadata{
		optional(w.HasName(), w.GetName()),
		optional(w.HasEmoji(), w.GetEmoji()),
		optional(w.HasDescription(), w.GetDescription()),
		optional(w.HasNotes(), w.GetNotes()),
		unknownOf(w),
	}
}

func toWireProjectMetadata(v ProjectMetadata) *panelv1.ProjectMetadata {
	b := panelv1.ProjectMetadata_builder{
		Name:        v.Name,
		Emoji:       v.Emoji,
		Description: v.Description,
		Notes:       v.Notes,
	}
	return withUnknown(b.Build(), v.unknown)
}

func fromWireProjectSummary(w *panelv1.ProjectSummary) ProjectSummary {
	return ProjectSummary{
		w.GetProjectId(),
		pointerFromWire(w.GetMetadata(), fromWireProjectMetadata),
		sliceFromWire(w.GetProblems(), fromWireProjectProblem),
		sliceFromWire(w.GetServices(), fromWireServiceSummary),
		w.GetUrl(),
		w.GetHosts(),
		pointerFromWire(w.GetHttpTrafficLastDay(), fromWireHTTPTrafficSummary),
		w.GetCpuUsedCores(),
		w.GetMemoryUsedBytes(),
		timeFromWire(w.GetDeployTime()),
		sliceFromWire(w.GetRunningOperations(), fromWireOperation),
		w.GetPinned(),
		w.GetDiskUsedBytes(),
	}
}

func fromWireServiceSummary(w *panelv1.ServiceSummary) ServiceSummary {
	return ServiceSummary{
		w.GetService(),
		fromWireServiceState(w.GetState()),
	}
}

func fromWireProjectProblem(w *panelv1.ProjectProblem) ProjectProblem {
	return ProjectProblem{
		fromWireProjectProblemKind(w.GetKind()),
		w.GetService(),
		w.GetOperationId(),
		timeFromWire(w.GetSinceTime()),
		w.GetProblemMessage(),
	}
}

func toWireGetProjectRequest(v GetProjectRequest) *panelv1.GetProjectRequest {
	b := panelv1.GetProjectRequest_builder{
		ProjectId:           nonZero(v.ProjectID),
		IncludeSecretValues: nonZero(v.IncludeSecretValues),
		SnapshotsBefore:     timeToWire(v.SnapshotsBefore),
		SnapshotsVolume:     nonZero(v.SnapshotsVolume),
	}
	return b.Build()
}

func fromWireGetProjectResponse(w *panelv1.GetProjectResponse) GetProjectResponse {
	return GetProjectResponse{
		pointerFromWire(w.GetProject(), fromWireProject),
	}
}

func fromWireProject(w *panelv1.Project) Project {
	return Project{
		w.GetProjectId(),
		pointerFromWire(w.GetMetadata(), fromWireProjectMetadata),
		sliceFromWire(w.GetProblems(), fromWireProjectProblem),
		w.GetUrl(),
		w.GetCpuUsedCores(),
		w.GetMemoryUsedBytes(),
		w.GetDeployId(),
		fromWireOperationStatus(w.GetDeployStatus()),
		timeFromWire(w.GetDeployTime()),
		w.GetXPethostAppliesAtOnce(),
		sliceFromWire(w.GetServices(), fromWireService),
		sliceFromWire(w.GetVolumes(), fromWireVolume),
		sliceFromWire(w.GetRoutes(), fromWireRoute),
		sliceFromWire(w.GetHosts(), fromWireHost),
		w.GetPasswordProtected(),
		sliceFromWire(w.GetOperations(), fromWireOperation),
		sliceFromWire(w.GetSnapshots(), fromWireSnapshot),
		w.GetSnapshotCount(),
		timeFromWire(w.GetSnapshotListTime()),
		pointerFromWire(w.GetHttpTrafficLastDay(), fromWireHTTPTrafficSummary),
		pointerFromWire(w.GetSource(), fromWireProjectSource),
		pointerFromWire(w.GetRunningServicesAction(), fromWireRunningServicesAction),
	}
}

func fromWireRunningServicesAction(w *panelv1.RunningServicesAction) RunningServicesAction {
	return RunningServicesAction{
		fromWireServicesActionKind(w.GetKind()),
		w.GetServices(),
		timeFromWire(w.GetStartTime()),
	}
}

func fromWireProjectSource(w *panelv1.ProjectSource) ProjectSource {
	return ProjectSource{
		fromWireProjectSourceKind(w),
		unknownOf(w),
	}
}

func toWireProjectSource(v ProjectSource) *panelv1.ProjectSource {
	b := panelv1.ProjectSource_builder{}
	if v.Kind != nil {
		v.Kind.toProjectSourceKind(&b)
	}
	if v.Kind == nil {
		return withUnknown(b.Build(), v.unknown)
	}
	return b.Build()
}

func fromWireProjectSourceKind(w *panelv1.ProjectSource) ProjectSourceKind {
	switch w.WhichKind() {
	case panelv1.ProjectSource_Files_case:
		return ProjectSourceFiles(w.GetFiles())
	case panelv1.ProjectSource_Github_case:
		return ProjectSourceGithub(fromWireGithubSource(w.GetGithub()))
	}
	return nil
}

func (v ProjectSourceFiles) toProjectSourceKind(b *panelv1.ProjectSource_builder) {
	b.Files = new(bool(v))
}

func (v ProjectSourceGithub) toProjectSourceKind(b *panelv1.ProjectSource_builder) {
	b.Github = toWireGithubSource(GithubSource(v))
}

var (
	_ ProjectSourceKind = ProjectSourceFiles(false)
	_ ProjectSourceKind = ProjectSourceGithub{}
)

func fromWireGithubSource(w *panelv1.GithubSource) GithubSource {
	return GithubSource{
		optional(w.HasRepository(), w.GetRepository()),
		optional(w.HasBranch(), w.GetBranch()),
		optional(w.HasDirectory(), w.GetDirectory()),
		optional(w.HasAutoDeploy(), w.GetAutoDeploy()),
		pointerFromWire(w.GetNewestCommit(), fromWireGithubCommit),
		pointerFromWire(w.GetDeployedCommit(), fromWireGithubCommit),
		w.GetPinned(),
		w.GetAutoDeployPending(),
		unknownOf(w),
	}
}

func toWireGithubSource(v GithubSource) *panelv1.GithubSource {
	b := panelv1.GithubSource_builder{
		Repository:        v.Repository,
		Branch:            v.Branch,
		Directory:         v.Directory,
		AutoDeploy:        v.AutoDeploy,
		NewestCommit:      pointerToWire(v.NewestCommit, toWireGithubCommit),
		DeployedCommit:    pointerToWire(v.DeployedCommit, toWireGithubCommit),
		Pinned:            nonZero(v.Pinned),
		AutoDeployPending: nonZero(v.AutoDeployPending),
	}
	return withUnknown(b.Build(), v.unknown)
}

func fromWireGithubCommit(w *panelv1.GithubCommit) GithubCommit {
	return GithubCommit{
		w.GetSha(),
		w.GetTitle(),
		w.GetUrl(),
		unknownOf(w),
	}
}

func toWireGithubCommit(v GithubCommit) *panelv1.GithubCommit {
	b := panelv1.GithubCommit_builder{
		Sha:   nonZero(v.Sha),
		Title: nonZero(v.Title),
		Url:   nonZero(v.URL),
	}
	return withUnknown(b.Build(), v.unknown)
}

func fromWireService(w *panelv1.Service) Service {
	return Service{
		w.GetService(),
		fromWireServiceState(w.GetState()),
		w.GetContainerRunning(),
		w.GetImage(),
		w.GetBuildsImage(),
		w.GetImageDigest(),
		w.GetImageSizeBytes(),
		w.GetCommand(),
		w.GetRunAsUser(),
		timeFromWire(w.GetStartTime()),
		timeFromWire(w.GetFinishTime()),
		optional(w.HasExitCode(), w.GetExitCode()),
		w.GetOutOfMemory(),
		w.GetRestartCount(),
		w.GetCpuUsedCores(),
		w.GetMemoryUsedBytes(),
		w.GetMemoryLimitBytes(),
		w.GetCpuLimitCores(),
		w.GetWritableLayerBytes(),
		w.GetPorts(),
		w.GetListeningPorts(),
		sliceFromWire(w.GetPublishedPorts(), fromWirePublishedPort),
		sliceFromWire(w.GetVolumeMounts(), fromWireVolumeMount),
		fromWireRestartPolicy(w.GetRestartPolicy()),
		pointerFromWire(w.GetHealthCheck(), fromWireHealthCheck),
		sliceFromWire(w.GetEnvironment(), fromWireEnvironmentVariable),
		w.GetEnvFiles(),
		w.GetSshCommand(),
	}
}

func fromWirePublishedPort(w *panelv1.PublishedPort) PublishedPort {
	return PublishedPort{
		w.GetMachinePort(),
		w.GetContainerPort(),
		w.GetProtocol(),
		w.GetMachineOnly(),
	}
}

func fromWireVolumeMount(w *panelv1.VolumeMount) VolumeMount {
	return VolumeMount{
		w.GetVolume(),
		w.GetContainerPath(),
	}
}

func fromWireHealthCheck(w *panelv1.HealthCheck) HealthCheck {
	return HealthCheck{
		w.GetCommand(),
		w.GetIntervalSeconds(),
		fromWireHealthStatus(w.GetStatus()),
		w.GetConsecutiveFailureCount(),
		w.GetRecentResultsPassed(),
		w.GetLastFailureOutput(),
	}
}

func fromWireEnvironmentVariable(w *panelv1.EnvironmentVariable) EnvironmentVariable {
	return EnvironmentVariable{
		w.GetName(),
		w.GetValue(),
		w.GetSecret(),
		w.GetSourceFile(),
		w.GetFromEnvFileVariables(),
		w.GetValueLeftOut(),
	}
}

func fromWireVolume(w *panelv1.Volume) Volume {
	return Volume{
		w.GetVolume(),
		w.GetSizeBytes(),
		sliceFromWire(w.GetMountedBy(), fromWireVolumeMountedBy),
		timeFromWire(w.GetLastBackupTime()),
		w.GetSnapshotCount(),
		w.GetDeclared(),
	}
}

func fromWireVolumeMountedBy(w *panelv1.VolumeMountedBy) VolumeMountedBy {
	return VolumeMountedBy{
		w.GetService(),
		w.GetContainerPath(),
	}
}

func fromWireHost(w *panelv1.Host) Host {
	return Host{
		w.GetHost(),
		w.GetUrl(),
		fromWireCertificateSource(w.GetCertificateSource()),
		timeFromWire(w.GetCertificateExpireTime()),
		w.GetUnavailableMessage(),
	}
}

func fromWireRoute(w *panelv1.Route) Route {
	return Route{
		w.GetHost(),
		w.GetPath(),
		w.GetService(),
		w.GetPort(),
		w.GetStripPath(),
		unknownOf(w),
	}
}

func toWireRoute(v Route) *panelv1.Route {
	b := panelv1.Route_builder{
		Host:      nonZero(v.Host),
		Path:      nonZero(v.Path),
		Service:   nonZero(v.Service),
		Port:      nonZero(v.Port),
		StripPath: nonZero(v.StripPath),
	}
	return withUnknown(b.Build(), v.unknown)
}

func fromWireOperation(w *panelv1.Operation) Operation {
	return Operation{
		w.GetOperationId(),
		fromWireOperationKind(w.GetKind()),
		fromWireOperationStatus(w.GetStatus()),
		timeFromWire(w.GetStartTime()),
		timeFromWire(w.GetFinishTime()),
		w.GetFailureMessage(),
		fromWireDeployFailureReason(w.GetDeployFailureReason()),
		w.GetMadeCurrent(),
		w.GetService(),
		w.GetFailedExitCode(),
		w.GetSnapshotId(),
		w.GetRestoredVolumes(),
		w.GetUndoSnapshotId(),
		pointerFromWire(w.GetGithubCommit(), fromWireGithubCommit),
		w.GetArchiveName(),
		w.GetAdjustments(),
		w.GetChangedPaths(),
		w.GetChangedPathCount(),
		w.GetFilesKept(),
	}
}

func fromWireSnapshot(w *panelv1.Snapshot) Snapshot {
	return Snapshot{
		w.GetSnapshotId(),
		timeFromWire(w.GetCreateTime()),
		w.GetSizeBytes(),
		w.GetVolumes(),
	}
}

func fromWireHTTPTrafficSummary(w *panelv1.HttpTrafficSummary) HTTPTrafficSummary {
	return HTTPTrafficSummary{
		w.GetRequestCount(),
		w.GetServerErrorCount(),
		w.GetLatencyP50Ms(),
		w.GetLatencyP95Ms(),
	}
}

func toWireCreateProjectRequest(v CreateProjectRequest) *panelv1.CreateProjectRequest {
	b := panelv1.CreateProjectRequest_builder{
		ProjectId:      nonZero(v.ProjectID),
		Source:         pointerToWire(v.Source, toWireProjectSource),
		UploadId:       nonZero(v.UploadID),
		Files:          sliceToWire(v.Files, toWireFileChange),
		XPethost:       pointerToWire(v.XPethost, toWireProjectExtension),
		TimeoutSeconds: nonZero(v.TimeoutSeconds),
		OperationId:    nonZero(v.OperationID),
		WaitSeconds:    v.WaitSeconds,
	}
	return b.Build()
}

func fromWireCreateProjectResponse(w *panelv1.CreateProjectResponse) CreateProjectResponse {
	return CreateProjectResponse{
		pointerFromWire(w.GetOperation(), fromWireOperation),
		sliceFromWire(w.GetViolations(), fromWireSpecViolation),
		w.GetAdjustments(),
		pointerFromWire(w.GetProject(), fromWireProject),
		sliceFromWire(w.GetLog(), fromWireOperationLogLine),
	}
}

func toWireDeployProjectRequest(v DeployProjectRequest) *panelv1.DeployProjectRequest {
	b := panelv1.DeployProjectRequest_builder{
		ProjectId:      nonZero(v.ProjectID),
		BaseDeployId:   nonZero(v.BaseDeployID),
		Files:          sliceToWire(v.Files, toWireFileChange),
		XPethost:       pointerToWire(v.XPethost, toWireProjectExtension),
		MountVolume:    pointerToWire(v.MountVolume, toWireMountVolume),
		TimeoutSeconds: nonZero(v.TimeoutSeconds),
		OperationId:    nonZero(v.OperationID),
		WaitSeconds:    v.WaitSeconds,
	}
	if v.Version != nil {
		v.Version.toDeployProjectVersion(&b)
	}
	return b.Build()
}

func (v DeployProjectUploadID) toDeployProjectVersion(b *panelv1.DeployProjectRequest_builder) {
	b.UploadId = new(string(v))
}

func (v DeployProjectCommit) toDeployProjectVersion(b *panelv1.DeployProjectRequest_builder) {
	b.Commit = new(string(v))
}

func (v DeployProjectNewestCommit) toDeployProjectVersion(b *panelv1.DeployProjectRequest_builder) {
	b.NewestCommit = new(bool(v))
}

func (v DeployProjectRollbackDeployID) toDeployProjectVersion(b *panelv1.DeployProjectRequest_builder) {
	b.RollbackDeployId = new(string(v))
}

var (
	_ DeployProjectVersion = DeployProjectUploadID("")
	_ DeployProjectVersion = DeployProjectCommit("")
	_ DeployProjectVersion = DeployProjectNewestCommit(false)
	_ DeployProjectVersion = DeployProjectRollbackDeployID("")
)

func toWireMountVolume(v MountVolume) *panelv1.MountVolume {
	b := panelv1.MountVolume_builder{
		Service:       nonZero(v.Service),
		Volume:        nonZero(v.Volume),
		ContainerPath: nonZero(v.ContainerPath),
	}
	return b.Build()
}

func toWireProjectExtension(v ProjectExtension) *panelv1.ProjectExtension {
	b := panelv1.ProjectExtension_builder{
		Metadata:       pointerToWire(v.Metadata, toWireProjectMetadata),
		Routes:         sliceToWire(v.Routes, toWireRoute),
		RemoveRoutes:   nonZero(v.RemoveRoutes),
		Password:       nonZero(v.Password),
		RemovePassword: nonZero(v.RemovePassword),
	}
	return b.Build()
}

func toWireFileChange(v FileChange) *panelv1.FileChange {
	b := panelv1.FileChange_builder{
		Path:       nonZero(v.Path),
		Executable: nonZero(v.Executable),
	}
	if v.Change != nil {
		v.Change.toFileChangeChange(&b)
	}
	return b.Build()
}

func (v FileChangeText) toFileChangeChange(b *panelv1.FileChange_builder) {
	b.Text = new(string(v))
}

func (v FileChangeData) toFileChangeChange(b *panelv1.FileChange_builder) {
	b.Data = presentBytes(v)
}

func (v FileChangeMakeDirectory) toFileChangeChange(b *panelv1.FileChange_builder) {
	b.MakeDirectory = new(bool(v))
}

func (v FileChangeDelete) toFileChangeChange(b *panelv1.FileChange_builder) {
	b.Delete = new(bool(v))
}

func (v FileChangeDeleteTree) toFileChangeChange(b *panelv1.FileChange_builder) {
	b.DeleteTree = new(bool(v))
}

func (v FileChangeRenameTo) toFileChangeChange(b *panelv1.FileChange_builder) {
	b.RenameTo = new(string(v))
}

var (
	_ FileChangeChange = FileChangeText("")
	_ FileChangeChange = FileChangeData(nil)
	_ FileChangeChange = FileChangeMakeDirectory(false)
	_ FileChangeChange = FileChangeDelete(false)
	_ FileChangeChange = FileChangeDeleteTree(false)
	_ FileChangeChange = FileChangeRenameTo("")
)

func fromWireDeployProjectResponse(w *panelv1.DeployProjectResponse) DeployProjectResponse {
	return DeployProjectResponse{
		pointerFromWire(w.GetOperation(), fromWireOperation),
		sliceFromWire(w.GetViolations(), fromWireSpecViolation),
		w.GetAdjustments(),
		pointerFromWire(w.GetProject(), fromWireProject),
		sliceFromWire(w.GetLog(), fromWireOperationLogLine),
	}
}

func fromWireSpecViolation(w *panelv1.SpecViolation) SpecViolation {
	return SpecViolation{
		w.GetService(),
		w.GetLocation(),
		w.GetViolationMessage(),
	}
}

func toWireListCommitsRequest(v ListCommitsRequest) *panelv1.ListCommitsRequest {
	b := panelv1.ListCommitsRequest_builder{
		ProjectId:    nonZero(v.ProjectID),
		BeforeCommit: nonZero(v.BeforeCommit),
	}
	return b.Build()
}

func fromWireListCommitsResponse(w *panelv1.ListCommitsResponse) ListCommitsResponse {
	return ListCommitsResponse{
		sliceFromWire(w.GetCommits(), fromWireBranchCommit),
		w.GetMore(),
	}
}

func fromWireBranchCommit(w *panelv1.BranchCommit) BranchCommit {
	return BranchCommit{
		pointerFromWire(w.GetCommit(), fromWireGithubCommit),
		w.GetAuthor(),
		timeFromWire(w.GetCommitTime()),
		w.GetDeployed(),
		pointerFromWire(w.GetLastDeploy(), fromWireOperation),
		w.GetNewest(),
	}
}

func toWireRunProjectActionRequest(v RunProjectActionRequest) *panelv1.RunProjectActionRequest {
	b := panelv1.RunProjectActionRequest_builder{
		ProjectId:   nonZero(v.ProjectID),
		OperationId: nonZero(v.OperationID),
		WaitSeconds: v.WaitSeconds,
	}
	if v.Action != nil {
		v.Action.toRunProjectActionAction(&b)
	}
	return b.Build()
}

func (v RunProjectActionStartServices) toRunProjectActionAction(b *panelv1.RunProjectActionRequest_builder) {
	b.StartServices = toWireServicesAction(ServicesAction(v))
}

func (v RunProjectActionStopServices) toRunProjectActionAction(b *panelv1.RunProjectActionRequest_builder) {
	b.StopServices = toWireServicesAction(ServicesAction(v))
}

func (v RunProjectActionRestartServices) toRunProjectActionAction(b *panelv1.RunProjectActionRequest_builder) {
	b.RestartServices = toWireServicesAction(ServicesAction(v))
}

func (v RunProjectActionRecreateService) toRunProjectActionAction(b *panelv1.RunProjectActionRequest_builder) {
	b.RecreateService = toWireRecreateServiceAction(RecreateServiceAction(v))
}

func (v RunProjectActionBackUp) toRunProjectActionAction(b *panelv1.RunProjectActionRequest_builder) {
	b.BackUp = toWireBackUpAction(BackUpAction(v))
}

func (v RunProjectActionRestoreSnapshot) toRunProjectActionAction(b *panelv1.RunProjectActionRequest_builder) {
	b.RestoreSnapshot = toWireRestoreSnapshotAction(RestoreSnapshotAction(v))
}

func (v RunProjectActionCancelOperation) toRunProjectActionAction(b *panelv1.RunProjectActionRequest_builder) {
	b.CancelOperation = toWireCancelOperationAction(CancelOperationAction(v))
}

func (v RunProjectActionDeleteProject) toRunProjectActionAction(b *panelv1.RunProjectActionRequest_builder) {
	b.DeleteProject = toWireDeleteProjectAction(DeleteProjectAction(v))
}

func (v RunProjectActionSetSource) toRunProjectActionAction(b *panelv1.RunProjectActionRequest_builder) {
	b.SetSource = toWireProjectSource(ProjectSource(v))
}

func (v RunProjectActionDeleteVolume) toRunProjectActionAction(b *panelv1.RunProjectActionRequest_builder) {
	b.DeleteVolume = new(string(v))
}

var (
	_ RunProjectActionAction = RunProjectActionStartServices{}
	_ RunProjectActionAction = RunProjectActionStopServices{}
	_ RunProjectActionAction = RunProjectActionRestartServices{}
	_ RunProjectActionAction = RunProjectActionRecreateService{}
	_ RunProjectActionAction = RunProjectActionBackUp{}
	_ RunProjectActionAction = RunProjectActionRestoreSnapshot{}
	_ RunProjectActionAction = RunProjectActionCancelOperation{}
	_ RunProjectActionAction = RunProjectActionDeleteProject{}
	_ RunProjectActionAction = RunProjectActionSetSource{}
	_ RunProjectActionAction = RunProjectActionDeleteVolume("")
)

func toWireServicesAction(v ServicesAction) *panelv1.ServicesAction {
	b := panelv1.ServicesAction_builder{
		Services: v.Services,
	}
	return b.Build()
}

func toWireRecreateServiceAction(v RecreateServiceAction) *panelv1.RecreateServiceAction {
	b := panelv1.RecreateServiceAction_builder{
		Service:         nonZero(v.Service),
		PullLatestImage: nonZero(v.PullLatestImage),
	}
	return b.Build()
}

func toWireBackUpAction(v BackUpAction) *panelv1.BackUpAction {
	b := panelv1.BackUpAction_builder{}
	return b.Build()
}

func toWireRestoreSnapshotAction(v RestoreSnapshotAction) *panelv1.RestoreSnapshotAction {
	b := panelv1.RestoreSnapshotAction_builder{
		SnapshotId: nonZero(v.SnapshotID),
		Volumes:    v.Volumes,
	}
	return b.Build()
}

func toWireCancelOperationAction(v CancelOperationAction) *panelv1.CancelOperationAction {
	b := panelv1.CancelOperationAction_builder{
		OperationId: nonZero(v.OperationID),
	}
	return b.Build()
}

func toWireDeleteProjectAction(v DeleteProjectAction) *panelv1.DeleteProjectAction {
	b := panelv1.DeleteProjectAction_builder{
		SkipFinalBackup: nonZero(v.SkipFinalBackup),
	}
	return b.Build()
}

func fromWireRunProjectActionResponse(w *panelv1.RunProjectActionResponse) RunProjectActionResponse {
	return RunProjectActionResponse{
		pointerFromWire(w.GetOperation(), fromWireOperation),
		pointerFromWire(w.GetProject(), fromWireProject),
		sliceFromWire(w.GetLog(), fromWireOperationLogLine),
	}
}

func toWireGetOperationRequest(v GetOperationRequest) *panelv1.GetOperationRequest {
	b := panelv1.GetOperationRequest_builder{
		ProjectId:    nonZero(v.ProjectID),
		OperationId:  nonZero(v.OperationID),
		WaitSeconds:  v.WaitSeconds,
		AfterLogLine: v.AfterLogLine,
		LogLineLimit: v.LogLineLimit,
	}
	return b.Build()
}

func fromWireGetOperationResponse(w *panelv1.GetOperationResponse) GetOperationResponse {
	return GetOperationResponse{
		pointerFromWire(w.GetOperation(), fromWireOperation),
		pointerFromWire(w.GetProject(), fromWireProject),
		sliceFromWire(w.GetLog(), fromWireOperationLogLine),
		w.GetLogLineCount(),
		w.GetNextAfterLogLine(),
	}
}

func fromWireOperationLogLine(w *panelv1.OperationLogLine) OperationLogLine {
	return OperationLogLine{
		timeFromWire(w.GetTime()),
		w.GetText(),
	}
}

func toWireHTTPTrafficFilter(v HTTPTrafficFilter) *panelv1.HttpTrafficFilter {
	b := panelv1.HttpTrafficFilter_builder{
		Host:         nonZero(v.Host),
		Method:       nonZero(v.Method),
		PathContains: nonZero(v.PathContains),
		PathPattern:  nonZero(v.PathPattern),
		StatusClass:  nonZero(v.StatusClass),
	}
	return b.Build()
}

func toWireQueryHTTPTrafficRequest(v QueryHTTPTrafficRequest) *panelv1.QueryHttpTrafficRequest {
	b := panelv1.QueryHttpTrafficRequest_builder{
		ProjectId:          nonZero(v.ProjectID),
		Filter:             pointerToWire(v.Filter, toWireHTTPTrafficFilter),
		StartTime:          timeToWire(v.StartTime),
		EndTime:            timeToWire(v.EndTime),
		LastSeconds:        nonZero(v.LastSeconds),
		BucketWidthSeconds: nonZero(v.BucketWidthSeconds),
		RequestLimit:       nonZero(v.RequestLimit),
		PageToken:          nonZero(v.PageToken),
	}
	return b.Build()
}

func fromWireQueryHTTPTrafficResponse(w *panelv1.QueryHttpTrafficResponse) QueryHTTPTrafficResponse {
	return QueryHTTPTrafficResponse{
		timeFromWire(w.GetStartTime()),
		timeFromWire(w.GetEndTime()),
		timeFromWire(w.GetOldestKeptTime()),
		pointerFromWire(w.GetSummary(), fromWireHTTPTrafficSummary),
		sliceFromWire(w.GetBuckets(), fromWireHTTPTrafficBucket),
		sliceFromWire(w.GetTopPaths(), fromWireHTTPPathTraffic),
		w.GetNewestSequence(),
		sliceFromWire(w.GetRequests(), fromWireHTTPRequest),
		w.GetNextPageToken(),
		w.GetTailSequence(),
	}
}

func fromWireHTTPTrafficBucket(w *panelv1.HttpTrafficBucket) HTTPTrafficBucket {
	return HTTPTrafficBucket{
		timeFromWire(w.GetStartTime()),
		pointerFromWire(w.GetSummary(), fromWireHTTPTrafficSummary),
	}
}

func fromWireHTTPPathTraffic(w *panelv1.HttpPathTraffic) HTTPPathTraffic {
	return HTTPPathTraffic{
		w.GetMethod(),
		w.GetPathPattern(),
		pointerFromWire(w.GetSummary(), fromWireHTTPTrafficSummary),
	}
}

func fromWireHTTPRequest(w *panelv1.HttpRequest) HTTPRequest {
	return HTTPRequest{
		w.GetSequence(),
		timeFromWire(w.GetFinishTime()),
		w.GetHost(),
		w.GetMethod(),
		w.GetPath(),
		w.GetPathPattern(),
		w.GetRoutePath(),
		w.GetService(),
		w.GetPort(),
		w.GetStatusCode(),
		w.GetResponseSizeBytes(),
		w.GetDurationMs(),
		w.GetServiceDurationMs(),
		w.GetClientIpAddress(),
		w.GetUserAgent(),
	}
}

func toWireContainerLogFilter(v ContainerLogFilter) *panelv1.ContainerLogFilter {
	b := panelv1.ContainerLogFilter_builder{
		Service:      nonZero(v.Service),
		Stream:       nonZero(toWireOutputStream(v.Stream)),
		TextContains: nonZero(v.TextContains),
	}
	return b.Build()
}

func toWireQueryContainerLogsRequest(v QueryContainerLogsRequest) *panelv1.QueryContainerLogsRequest {
	b := panelv1.QueryContainerLogsRequest_builder{
		ProjectId:   nonZero(v.ProjectID),
		Filter:      pointerToWire(v.Filter, toWireContainerLogFilter),
		StartTime:   timeToWire(v.StartTime),
		EndTime:     timeToWire(v.EndTime),
		LastSeconds: nonZero(v.LastSeconds),
		Limit:       nonZero(v.Limit),
		FromStart:   nonZero(v.FromStart),
		PageToken:   nonZero(v.PageToken),
	}
	return b.Build()
}

func fromWireQueryContainerLogsResponse(w *panelv1.QueryContainerLogsResponse) QueryContainerLogsResponse {
	return QueryContainerLogsResponse{
		timeFromWire(w.GetStartTime()),
		timeFromWire(w.GetEndTime()),
		timeFromWire(w.GetOldestKeptTime()),
		sliceFromWire(w.GetLines(), fromWireLogLine),
		w.GetNextPageToken(),
		w.GetTailCursor(),
	}
}

func fromWireLogLine(w *panelv1.LogLine) LogLine {
	return LogLine{
		timeFromWire(w.GetTime()),
		w.GetService(),
		fromWireOutputStream(w.GetStream()),
		w.GetText(),
	}
}

func toWireRunServiceCommandRequest(v RunServiceCommandRequest) *panelv1.RunServiceCommandRequest {
	b := panelv1.RunServiceCommandRequest_builder{
		ProjectId:        nonZero(v.ProjectID),
		Service:          nonZero(v.Service),
		Command:          v.Command,
		Stdin:            nonZero(v.Stdin),
		RunAsUser:        nonZero(v.RunAsUser),
		WorkingDirectory: nonZero(v.WorkingDirectory),
		TimeoutSeconds:   nonZero(v.TimeoutSeconds),
	}
	return b.Build()
}

func fromWireRunServiceCommandResponse(w *panelv1.RunServiceCommandResponse) RunServiceCommandResponse {
	return RunServiceCommandResponse{
		w.GetExitCode(),
		w.GetTimedOut(),
		w.GetStdout(),
		w.GetStderr(),
		w.GetOutputTruncated(),
	}
}

func fromWireFileEntry(w *panelv1.FileEntry) FileEntry {
	return FileEntry{
		w.GetName(),
		fromWireFileType(w.GetType()),
		w.GetSizeBytes(),
		timeFromWire(w.GetModifyTime()),
		w.GetMode(),
		w.GetOwnerUid(),
		w.GetOwnerGid(),
		w.GetSymlinkTarget(),
	}
}

func toWireReadPathRequest(v ReadPathRequest) *panelv1.ReadPathRequest {
	b := panelv1.ReadPathRequest_builder{
		ProjectId:      nonZero(v.ProjectID),
		Path:           nonZero(v.Path),
		EntryLimit:     nonZero(v.EntryLimit),
		OffsetBytes:    nonZero(v.OffsetBytes),
		LengthBytes:    nonZero(v.LengthBytes),
		EntryPageToken: nonZero(v.EntryPageToken),
	}
	if v.Root != nil {
		v.Root.toReadPathRoot(&b)
	}
	return b.Build()
}

func (v ReadPathService) toReadPathRoot(b *panelv1.ReadPathRequest_builder) {
	b.Service = new(string(v))
}

func (v ReadPathVolume) toReadPathRoot(b *panelv1.ReadPathRequest_builder) {
	b.Volume = new(string(v))
}

var (
	_ ReadPathRoot = ReadPathService("")
	_ ReadPathRoot = ReadPathVolume("")
)

func fromWireReadPathResponse(w *panelv1.ReadPathResponse) ReadPathResponse {
	return ReadPathResponse{
		pointerFromWire(w.GetEntry(), fromWireFileEntry),
		fromWireFileLocation(w.GetLocation()),
		w.GetVolume(),
		sliceFromWire(w.GetEntries(), fromWireFileEntry),
		w.GetEntryCount(),
		w.GetNextEntryPageToken(),
		w.GetText(),
		w.GetBinary(),
		w.GetNextOffsetBytes(),
		w.GetDeployId(),
	}
}

func toWireCreateTransferRequest(v CreateTransferRequest) *panelv1.CreateTransferRequest {
	b := panelv1.CreateTransferRequest_builder{}
	if v.Transfer != nil {
		v.Transfer.toCreateTransferTransfer(&b)
	}
	return b.Build()
}

func (v CreateTransferUploadArchive) toCreateTransferTransfer(b *panelv1.CreateTransferRequest_builder) {
	b.UploadArchive = toWireArchiveUpload(ArchiveUpload(v))
}

func (v CreateTransferUploadFile) toCreateTransferTransfer(b *panelv1.CreateTransferRequest_builder) {
	b.UploadFile = toWireFileUpload(FileUpload(v))
}

func (v CreateTransferDownload) toCreateTransferTransfer(b *panelv1.CreateTransferRequest_builder) {
	b.Download = toWirePathDownload(PathDownload(v))
}

var (
	_ CreateTransferTransfer = CreateTransferUploadArchive{}
	_ CreateTransferTransfer = CreateTransferUploadFile{}
	_ CreateTransferTransfer = CreateTransferDownload{}
)

func toWireArchiveUpload(v ArchiveUpload) *panelv1.ArchiveUpload {
	b := panelv1.ArchiveUpload_builder{
		FileName: nonZero(v.FileName),
	}
	return b.Build()
}

func toWireFileUpload(v FileUpload) *panelv1.FileUpload {
	b := panelv1.FileUpload_builder{
		ProjectId: nonZero(v.ProjectID),
		Path:      nonZero(v.Path),
	}
	if v.Root != nil {
		v.Root.toFileUploadRoot(&b)
	}
	return b.Build()
}

func (v FileUploadService) toFileUploadRoot(b *panelv1.FileUpload_builder) {
	b.Service = new(string(v))
}

func (v FileUploadVolume) toFileUploadRoot(b *panelv1.FileUpload_builder) {
	b.Volume = new(string(v))
}

var (
	_ FileUploadRoot = FileUploadService("")
	_ FileUploadRoot = FileUploadVolume("")
)

func toWirePathDownload(v PathDownload) *panelv1.PathDownload {
	b := panelv1.PathDownload_builder{
		ProjectId: nonZero(v.ProjectID),
		Path:      nonZero(v.Path),
	}
	if v.Root != nil {
		v.Root.toPathDownloadRoot(&b)
	}
	return b.Build()
}

func (v PathDownloadService) toPathDownloadRoot(b *panelv1.PathDownload_builder) {
	b.Service = new(string(v))
}

func (v PathDownloadVolume) toPathDownloadRoot(b *panelv1.PathDownload_builder) {
	b.Volume = new(string(v))
}

var (
	_ PathDownloadRoot = PathDownloadService("")
	_ PathDownloadRoot = PathDownloadVolume("")
)

func fromWireCreateTransferResponse(w *panelv1.CreateTransferResponse) CreateTransferResponse {
	return CreateTransferResponse{
		w.GetUrl(),
		w.GetHttpMethod(),
		timeFromWire(w.GetExpireTime()),
		w.GetCommand(),
		w.GetUploadId(),
		w.GetReplaces(),
		w.GetFileName(),
	}
}

func fromWireProjectBusy(w *panelv1.ProjectBusy) ProjectBusy {
	return ProjectBusy{
		w.GetOperationId(),
		fromWireOperationKind(w.GetKind()),
		timeFromWire(w.GetStartTime()),
	}
}

func fromWireProjectChanged(w *panelv1.ProjectChanged) ProjectChanged {
	return ProjectChanged{}
}

func fromWireMachineUnreachable(w *panelv1.MachineUnreachable) MachineUnreachable {
	return MachineUnreachable{}
}

func fromWireNoMachine(w *panelv1.NoMachine) NoMachine {
	return NoMachine{
		fromWireNoMachineReason(w.GetReason()),
		w.GetUrl(),
	}
}

func fromWireMachineSessionKind(w panelv1.MachineSessionKind) MachineSessionKind {
	return MachineSessionKind(w)
}

func fromWireProjectProblemKind(w panelv1.ProjectProblemKind) ProjectProblemKind {
	return ProjectProblemKind(w)
}

func fromWireServicesActionKind(w panelv1.ServicesActionKind) ServicesActionKind {
	return ServicesActionKind(w)
}

func fromWireServiceState(w panelv1.ServiceState) ServiceState { return ServiceState(w) }

func fromWireRestartPolicy(w panelv1.RestartPolicy) RestartPolicy { return RestartPolicy(w) }

func fromWireHealthStatus(w panelv1.HealthStatus) HealthStatus { return HealthStatus(w) }

func fromWireCertificateSource(w panelv1.CertificateSource) CertificateSource {
	return CertificateSource(w)
}

func fromWireOperationKind(w panelv1.OperationKind) OperationKind { return OperationKind(w) }

func fromWireOperationStatus(w panelv1.OperationStatus) OperationStatus { return OperationStatus(w) }

func fromWireDeployFailureReason(w panelv1.DeployFailureReason) DeployFailureReason {
	return DeployFailureReason(w)
}

func fromWireOutputStream(w panelv1.OutputStream) OutputStream { return OutputStream(w) }

func toWireOutputStream(v OutputStream) panelv1.OutputStream { return panelv1.OutputStream(v) }

func fromWireFileType(w panelv1.FileType) FileType { return FileType(w) }

func fromWireFileLocation(w panelv1.FileLocation) FileLocation { return FileLocation(w) }

func fromWireNoMachineReason(w panelv1.NoMachineReason) NoMachineReason { return NoMachineReason(w) }

// Each constant of the package is the wire layer's number: one that differs does not compile.
func _() {
	var same [1]struct{}
	_ = same[MachineSessionKindUnspecified-MachineSessionKind(panelv1.MachineSessionKind_MACHINE_SESSION_KIND_UNSPECIFIED)]
	_ = same[MachineSessionKindWebTerminal-MachineSessionKind(panelv1.MachineSessionKind_MACHINE_SESSION_KIND_WEB_TERMINAL)]
	_ = same[MachineSessionKindSSHTerminal-MachineSessionKind(panelv1.MachineSessionKind_MACHINE_SESSION_KIND_SSH_TERMINAL)]
	_ = same[MachineSessionKindSSHCommand-MachineSessionKind(panelv1.MachineSessionKind_MACHINE_SESSION_KIND_SSH_COMMAND)]
	_ = same[MachineSessionKindSftp-MachineSessionKind(panelv1.MachineSessionKind_MACHINE_SESSION_KIND_SFTP)]
	_ = same[MachineSessionKindTunnel-MachineSessionKind(panelv1.MachineSessionKind_MACHINE_SESSION_KIND_TUNNEL)]
	_ = same[ProjectProblemKindUnspecified-ProjectProblemKind(panelv1.ProjectProblemKind_PROJECT_PROBLEM_KIND_UNSPECIFIED)]
	_ = same[ProjectProblemKindDeployFailed-ProjectProblemKind(panelv1.ProjectProblemKind_PROJECT_PROBLEM_KIND_DEPLOY_FAILED)]
	_ = same[ProjectProblemKindServiceUnhealthy-ProjectProblemKind(panelv1.ProjectProblemKind_PROJECT_PROBLEM_KIND_SERVICE_UNHEALTHY)]
	_ = same[ProjectProblemKindServiceRestarting-ProjectProblemKind(panelv1.ProjectProblemKind_PROJECT_PROBLEM_KIND_SERVICE_RESTARTING)]
	_ = same[ProjectProblemKindServiceOutOfMemory-ProjectProblemKind(panelv1.ProjectProblemKind_PROJECT_PROBLEM_KIND_SERVICE_OUT_OF_MEMORY)]
	_ = same[ProjectProblemKindBackupFailed-ProjectProblemKind(panelv1.ProjectProblemKind_PROJECT_PROBLEM_KIND_BACKUP_FAILED)]
	_ = same[ProjectProblemKindDeployCancelled-ProjectProblemKind(panelv1.ProjectProblemKind_PROJECT_PROBLEM_KIND_DEPLOY_CANCELLED)]
	_ = same[ProjectProblemKindServiceExited-ProjectProblemKind(panelv1.ProjectProblemKind_PROJECT_PROBLEM_KIND_SERVICE_EXITED)]
	_ = same[ProjectProblemKindRestoreFailed-ProjectProblemKind(panelv1.ProjectProblemKind_PROJECT_PROBLEM_KIND_RESTORE_FAILED)]
	_ = same[ProjectProblemKindAutoDeployRefused-ProjectProblemKind(panelv1.ProjectProblemKind_PROJECT_PROBLEM_KIND_AUTO_DEPLOY_REFUSED)]
	_ = same[ProjectProblemKindServicePortClosed-ProjectProblemKind(panelv1.ProjectProblemKind_PROJECT_PROBLEM_KIND_SERVICE_PORT_CLOSED)]
	_ = same[ServicesActionKindUnspecified-ServicesActionKind(panelv1.ServicesActionKind_SERVICES_ACTION_KIND_UNSPECIFIED)]
	_ = same[ServicesActionKindStart-ServicesActionKind(panelv1.ServicesActionKind_SERVICES_ACTION_KIND_START)]
	_ = same[ServicesActionKindStop-ServicesActionKind(panelv1.ServicesActionKind_SERVICES_ACTION_KIND_STOP)]
	_ = same[ServicesActionKindRestart-ServicesActionKind(panelv1.ServicesActionKind_SERVICES_ACTION_KIND_RESTART)]
	_ = same[ServiceStateUnspecified-ServiceState(panelv1.ServiceState_SERVICE_STATE_UNSPECIFIED)]
	_ = same[ServiceStateNotCreated-ServiceState(panelv1.ServiceState_SERVICE_STATE_NOT_CREATED)]
	_ = same[ServiceStateStarting-ServiceState(panelv1.ServiceState_SERVICE_STATE_STARTING)]
	_ = same[ServiceStateRunning-ServiceState(panelv1.ServiceState_SERVICE_STATE_RUNNING)]
	_ = same[ServiceStateHealthy-ServiceState(panelv1.ServiceState_SERVICE_STATE_HEALTHY)]
	_ = same[ServiceStateUnhealthy-ServiceState(panelv1.ServiceState_SERVICE_STATE_UNHEALTHY)]
	_ = same[ServiceStateRestarting-ServiceState(panelv1.ServiceState_SERVICE_STATE_RESTARTING)]
	_ = same[ServiceStateStopped-ServiceState(panelv1.ServiceState_SERVICE_STATE_STOPPED)]
	_ = same[ServiceStateExited-ServiceState(panelv1.ServiceState_SERVICE_STATE_EXITED)]
	_ = same[RestartPolicyUnspecified-RestartPolicy(panelv1.RestartPolicy_RESTART_POLICY_UNSPECIFIED)]
	_ = same[RestartPolicyNo-RestartPolicy(panelv1.RestartPolicy_RESTART_POLICY_NO)]
	_ = same[RestartPolicyOnFailure-RestartPolicy(panelv1.RestartPolicy_RESTART_POLICY_ON_FAILURE)]
	_ = same[RestartPolicyUnlessStopped-RestartPolicy(panelv1.RestartPolicy_RESTART_POLICY_UNLESS_STOPPED)]
	_ = same[RestartPolicyAlways-RestartPolicy(panelv1.RestartPolicy_RESTART_POLICY_ALWAYS)]
	_ = same[HealthStatusUnspecified-HealthStatus(panelv1.HealthStatus_HEALTH_STATUS_UNSPECIFIED)]
	_ = same[HealthStatusStarting-HealthStatus(panelv1.HealthStatus_HEALTH_STATUS_STARTING)]
	_ = same[HealthStatusHealthy-HealthStatus(panelv1.HealthStatus_HEALTH_STATUS_HEALTHY)]
	_ = same[HealthStatusUnhealthy-HealthStatus(panelv1.HealthStatus_HEALTH_STATUS_UNHEALTHY)]
	_ = same[CertificateSourceUnspecified-CertificateSource(panelv1.CertificateSource_CERTIFICATE_SOURCE_UNSPECIFIED)]
	_ = same[CertificateSourceNone-CertificateSource(panelv1.CertificateSource_CERTIFICATE_SOURCE_NONE)]
	_ = same[CertificateSourceInstalled-CertificateSource(panelv1.CertificateSource_CERTIFICATE_SOURCE_INSTALLED)]
	_ = same[CertificateSourceAutomatic-CertificateSource(panelv1.CertificateSource_CERTIFICATE_SOURCE_AUTOMATIC)]
	_ = same[OperationKindUnspecified-OperationKind(panelv1.OperationKind_OPERATION_KIND_UNSPECIFIED)]
	_ = same[OperationKindDeploy-OperationKind(panelv1.OperationKind_OPERATION_KIND_DEPLOY)]
	_ = same[OperationKindRecreateService-OperationKind(panelv1.OperationKind_OPERATION_KIND_RECREATE_SERVICE)]
	_ = same[OperationKindBackup-OperationKind(panelv1.OperationKind_OPERATION_KIND_BACKUP)]
	_ = same[OperationKindRestore-OperationKind(panelv1.OperationKind_OPERATION_KIND_RESTORE)]
	_ = same[OperationKindDelete-OperationKind(panelv1.OperationKind_OPERATION_KIND_DELETE)]
	_ = same[OperationStatusUnspecified-OperationStatus(panelv1.OperationStatus_OPERATION_STATUS_UNSPECIFIED)]
	_ = same[OperationStatusInProgress-OperationStatus(panelv1.OperationStatus_OPERATION_STATUS_IN_PROGRESS)]
	_ = same[OperationStatusSucceeded-OperationStatus(panelv1.OperationStatus_OPERATION_STATUS_SUCCEEDED)]
	_ = same[OperationStatusFailed-OperationStatus(panelv1.OperationStatus_OPERATION_STATUS_FAILED)]
	_ = same[OperationStatusCancelled-OperationStatus(panelv1.OperationStatus_OPERATION_STATUS_CANCELLED)]
	_ = same[DeployFailureReasonUnspecified-DeployFailureReason(panelv1.DeployFailureReason_DEPLOY_FAILURE_REASON_UNSPECIFIED)]
	_ = same[DeployFailureReasonImagePullFailed-DeployFailureReason(panelv1.DeployFailureReason_DEPLOY_FAILURE_REASON_IMAGE_PULL_FAILED)]
	_ = same[DeployFailureReasonImageBuildFailed-DeployFailureReason(panelv1.DeployFailureReason_DEPLOY_FAILURE_REASON_IMAGE_BUILD_FAILED)]
	_ = same[DeployFailureReasonContainerStartFailed-DeployFailureReason(panelv1.DeployFailureReason_DEPLOY_FAILURE_REASON_CONTAINER_START_FAILED)]
	_ = same[DeployFailureReasonDiskFull-DeployFailureReason(panelv1.DeployFailureReason_DEPLOY_FAILURE_REASON_DISK_FULL)]
	_ = same[DeployFailureReasonInternal-DeployFailureReason(panelv1.DeployFailureReason_DEPLOY_FAILURE_REASON_INTERNAL)]
	_ = same[DeployFailureReasonPortUnavailable-DeployFailureReason(panelv1.DeployFailureReason_DEPLOY_FAILURE_REASON_PORT_UNAVAILABLE)]
	_ = same[DeployFailureReasonContainerExited-DeployFailureReason(panelv1.DeployFailureReason_DEPLOY_FAILURE_REASON_CONTAINER_EXITED)]
	_ = same[DeployFailureReasonContainerUnhealthy-DeployFailureReason(panelv1.DeployFailureReason_DEPLOY_FAILURE_REASON_CONTAINER_UNHEALTHY)]
	_ = same[DeployFailureReasonTimedOut-DeployFailureReason(panelv1.DeployFailureReason_DEPLOY_FAILURE_REASON_TIMED_OUT)]
	_ = same[DeployFailureReasonUncoveredImageVolume-DeployFailureReason(panelv1.DeployFailureReason_DEPLOY_FAILURE_REASON_UNCOVERED_IMAGE_VOLUME)]
	_ = same[DeployFailureReasonBuildMemoryUnavailable-DeployFailureReason(panelv1.DeployFailureReason_DEPLOY_FAILURE_REASON_BUILD_MEMORY_UNAVAILABLE)]
	_ = same[OutputStreamUnspecified-OutputStream(panelv1.OutputStream_OUTPUT_STREAM_UNSPECIFIED)]
	_ = same[OutputStreamStdout-OutputStream(panelv1.OutputStream_OUTPUT_STREAM_STDOUT)]
	_ = same[OutputStreamStderr-OutputStream(panelv1.OutputStream_OUTPUT_STREAM_STDERR)]
	_ = same[FileTypeUnspecified-FileType(panelv1.FileType_FILE_TYPE_UNSPECIFIED)]
	_ = same[FileTypeFile-FileType(panelv1.FileType_FILE_TYPE_FILE)]
	_ = same[FileTypeDirectory-FileType(panelv1.FileType_FILE_TYPE_DIRECTORY)]
	_ = same[FileTypeSymlink-FileType(panelv1.FileType_FILE_TYPE_SYMLINK)]
	_ = same[FileTypeOther-FileType(panelv1.FileType_FILE_TYPE_OTHER)]
	_ = same[FileLocationUnspecified-FileLocation(panelv1.FileLocation_FILE_LOCATION_UNSPECIFIED)]
	_ = same[FileLocationContainer-FileLocation(panelv1.FileLocation_FILE_LOCATION_CONTAINER)]
	_ = same[FileLocationVolume-FileLocation(panelv1.FileLocation_FILE_LOCATION_VOLUME)]
	_ = same[FileLocationProjectFiles-FileLocation(panelv1.FileLocation_FILE_LOCATION_PROJECT_FILES)]
	_ = same[NoMachineReasonUnspecified-NoMachineReason(panelv1.NoMachineReason_NO_MACHINE_REASON_UNSPECIFIED)]
	_ = same[NoMachineReasonNoPlan-NoMachineReason(panelv1.NoMachineReason_NO_MACHINE_REASON_NO_PLAN)]
	_ = same[NoMachineReasonBeingPrepared-NoMachineReason(panelv1.NoMachineReason_NO_MACHINE_REASON_BEING_PREPARED)]
}
