// Code generated by protoc-gen-panel-go from v1/panel.proto. DO NOT EDIT.

package pethost

import (
	"errors"

	"connectrpc.com/connect/v2"
	"connectrpc.com/connect/v2/connectproto"
	"github.com/pethost-dev/sdk/go/internal/panelv1"
)

// An Error is a call that failed: the API's refusal, or the failure to reach it. Every error
// a method of [Client] returns is an *Error:
//
//	if e, ok := errors.AsType[*pethost.Error](err); ok && e.Code == pethost.CodeNotFound {
//
// A detail is set when the API sent it; one that this version of the package does not know
// is left out, and Code and Message say the rest.
type Error struct {
	// The kind of failure: branch on it. The methods' comments say what each code means there.
	Code Code
	// What failed and what to do, for people.
	Message string

	// Detail of a [CodeUnavailable] error: an operation, or a short action, holds the project. The
	// message says the same in words.
	//
	// nil = the API sent no such detail.
	ProjectBusy *ProjectBusy

	// Detail of a [CodeAborted] error: [DeployProjectRequest.BaseDeployID] is not the current
	// deploy: the project was deployed since you read it. Read it again ([Project.DeployID]) and
	// redo your change on its files.
	//
	// nil = the API sent no such detail.
	ProjectChanged *ProjectChanged

	// Detail of a [CodeUnavailable] error: the machine does not answer now, as while it restarts.
	// Call again later.
	//
	// nil = the API sent no such detail.
	MachineUnreachable *MachineUnreachable

	// Detail of a [CodeFailedPrecondition] error: the account has no machine to run projects on
	// yet.
	//
	// nil = the API sent no such detail.
	NoMachine *NoMachine

	cause error // What failed below the API, for Unwrap.
}

// fromWireError is the wire layer's error as the package's: its code, its message and the
// details the package has a type for.
func fromWireError(err error) error {
	wire, ok := errors.AsType[*connect.Error](err)
	if !ok {
		return &Error{Code: CodeUnknown, Message: err.Error(), cause: err}
	}

	e := &Error{Code: Code(wire.Code()), Message: wire.Message(), cause: wire.Unwrap()}
	for _, detail := range wire.Details() {
		message, err := connectproto.UnmarshalErrorDetail(detail)
		if err != nil {
			continue
		}
		switch w := message.(type) {
		case *panelv1.ProjectBusy:
			e.ProjectBusy = new(fromWireProjectBusy(w))
		case *panelv1.ProjectChanged:
			e.ProjectChanged = new(fromWireProjectChanged(w))
		case *panelv1.MachineUnreachable:
			e.MachineUnreachable = new(fromWireMachineUnreachable(w))
		case *panelv1.NoMachine:
			e.NoMachine = new(fromWireNoMachine(w))
		}
	}
	return e
}
