// Code generated by protoc-gen-panel-go from v1/panel.proto. DO NOT EDIT.

package pethost

import (
	"bytes"
	"encoding/json"
	"fmt"
	"reflect"
	"regexp"
	"strings"
	"testing"
	"time"

	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// The checks of the package's JSON: what encoding/json writes of every message is what the
// wire layer writes of the same sample as the API does, and what the API writes reads back as
// the sample. The wire message is filled from its own descriptor (wire_test.go), so a field
// that a converter or a method here gets wrong shows as a difference.

// apiJSON is a wire message as the API answers it over HTTP: the checks' own statement of the
// form, with the fields named as the API's definition names them.
func apiJSON(t *testing.T, wire proto.Message) []byte {
	data, err := protojson.MarshalOptions{UseProtoNames: true}.Marshal(wire)
	if err != nil {
		t.Fatal(err)
	}
	return data
}

// compact is JSON as encoding/json writes what a MarshalJSON returns: without spaces, which
// the wire layer's codec puts in at random.
func compact(t *testing.T, data []byte) []byte {
	out, err := json.Marshal(json.RawMessage(data))
	if err != nil {
		t.Fatal(err)
	}
	return out
}

// TestJSON writes and reads samples of every message, until every field of it has been set,
// zero and absent and every member of every oneof set: an enum's number without a name too.
func TestJSON(t *testing.T) {
	bothWays := bothWaysOf()

	for _, shape := range shapes {
		name := string(shape.wire.ProtoReflect().Descriptor().Name())
		t.Run(name, func(t *testing.T) {
			sent := &wireSample{sent: true, bothWays: bothWays, had: map[string]bool{}}
			received := &wireSample{bothWays: bothWays, had: map[string]bool{}}

			for n := seed(0); ; n++ {
				lacks := append(sent.lacks(shape.wire), received.lacks(shape.wire)...)
				if len(lacks) == 0 {
					return
				}
				if n == mostSamples {
					t.Fatalf("%d samples had no:\n%s", n, strings.Join(lacks, "\n"))
				}
				sample := n.at(name)
				written(t, shape, sent.message(shape.wire, sample), sample)
				read(t, shape, received.message(shape.wire, sample), sample)
			}
		})
	}
}

// written: a sample of the struct is, to encoding/json, the wire layer's JSON of the sample as
// the package sends it; and so is each member in it that has a message's fields, alone.
func written(t *testing.T, shape shape, wire proto.Message, sample seed) {
	public := shape.sample(sample)

	got, err := json.Marshal(public)
	if err != nil {
		t.Fatal(err)
	}
	if want := compact(t, apiJSON(t, wire)); !bytes.Equal(got, want) {
		t.Fatalf("the sample is written as\n%s\nand the wire layer writes it as\n%s", got, want)
	}

	for _, member := range structMembers(reflect.ValueOf(public), nil) {
		memberAlone(t, member)
	}
}

// bare matches a JSON string of digits alone, which in a sample is a 64-bit integer: a text
// starts with a letter, and so does the base64 of one.
var bare = regexp.MustCompile(`"([0-9]+)"`)

// read: the sample as the API answers it reads back as the struct's sample, but for a later
// API's fields, which JSON has no names for. So it does with its 64-bit integers as numbers,
// and with its fields under the names JSON gives them by default, as the API takes both.
func read(t *testing.T, shape shape, wire proto.Message, sample seed) {
	answer := apiJSON(t, wire)
	camelCase, err := protojson.Marshal(wire)
	if err != nil {
		t.Fatal(err)
	}

	for _, data := range [][]byte{answer, bare.ReplaceAll(answer, []byte("$1")), camelCase} {
		got, err := shape.read(data)
		if err != nil {
			t.Fatalf("%v, reading\n%s", err, data)
		}
		if where := differIn(reflect.ValueOf(got), reflect.ValueOf(shape.sample(sample)), "the struct", false); where != "" {
			t.Fatalf("%s, reading\n%s", where, data)
		}
	}
}

// structMembers adds to found the values in v that a oneof holds and that are structs: the
// members with a message's fields.
func structMembers(v reflect.Value, found []reflect.Value) []reflect.Value {
	switch v.Kind() {
	case reflect.Interface:
		if !v.IsNil() && v.Elem().Kind() == reflect.Struct {
			found = append(found, v.Elem())
		}
		return structMembers(v.Elem(), found)
	case reflect.Pointer:
		return structMembers(v.Elem(), found)
	case reflect.Slice:
		for i := range v.Len() {
			found = structMembers(v.Index(i), found)
		}
	case reflect.Struct:
		for i := range v.NumField() {
			if v.Type() != reflect.TypeFor[time.Time]() {
				found = structMembers(v.Field(i), found)
			}
		}
	}
	return found
}

// memberAlone: a member with a message's fields is written alone as that message is, and read
// back from it. Its message is the struct of the same fields: two with the same fields are
// written alike.
func memberAlone(t *testing.T, member reflect.Value) {
	for _, shape := range shapes {
		message := reflect.TypeOf(shape.public)
		if !member.Type().ConvertibleTo(message) {
			continue
		}

		got, err := json.Marshal(member.Interface())
		if err != nil {
			t.Fatal(err)
		}
		want, err := json.Marshal(member.Convert(message).Interface())
		if err != nil {
			t.Fatal(err)
		}
		if !bytes.Equal(got, want) {
			t.Fatalf("a %s alone is written as\n%s\nand its %s as\n%s", member.Type(), got, message, want)
		}

		back := reflect.New(member.Type())
		if err := json.Unmarshal(got, back.Interface()); err != nil {
			t.Fatal(err)
		}
		if where := differIn(back.Elem(), member, member.Type().String(), false); where != "" {
			t.Fatalf("%s, reading\n%s", where, got)
		}
		return
	}
	t.Fatalf("no message of the package has the fields of %s", member.Type())
}

// TestJSONRefuses: a field the API does not have is refused in every message, whatever else
// the JSON holds; and null leaves a value as it is, as encoding/json asks of an UnmarshalJSON.
func TestJSONRefuses(t *testing.T) {
	for _, shape := range shapes {
		name := reflect.TypeOf(shape.public).Name()

		for _, data := range []string{`{"no_such_field": 1}`, `{"noSuchField": null}`, `[]`, `""`} {
			if got, err := shape.read([]byte(data)); err == nil {
				t.Errorf("a %s read %s as %v", name, data, got)
			}
		}

		held := reflect.New(reflect.TypeOf(shape.public))
		held.Elem().Set(reflect.ValueOf(shape.sample(seed(1).at(name))))
		if err := json.Unmarshal([]byte("null"), held.Interface()); err != nil {
			t.Errorf("a %s read null: %v", name, err)
		}
		if where := differ(held.Elem(), reflect.ValueOf(shape.sample(seed(1).at(name))), name); where != "" {
			t.Errorf("after null, %s", where)
		}
	}
}

// TestJSONEnums holds each enum alone, as it is in a struct of the program's, against the wire
// layer's names: a value is written as its whole name and read from it and from its number; a
// number without a name, a later API's, is written as the number and read from it; a name the
// enum does not have is refused.
func TestJSONEnums(t *testing.T) {
	for _, enum := range enums {
		values := enum.wire.Values()
		later := protoreflect.EnumNumber(1)

		for i := range values.Len() {
			value := values.Get(i)
			later = max(later, value.Number()+1)

			name := fmt.Sprintf("%q", value.Name())
			if got, err := enum.write(value.Number()); err != nil || string(got) != name {
				t.Errorf("%s(%d) is written as %s, %v: want %s", enum.name, value.Number(), got, err, name)
			}
			for _, data := range []string{name, fmt.Sprint(value.Number())} {
				if got, err := enum.read([]byte(data)); err != nil || got != value.Number() {
					t.Errorf("%s read %s as %d, %v: want %d", enum.name, data, got, err, value.Number())
				}
			}
		}

		number := fmt.Sprint(later)
		if got, err := enum.write(later); err != nil || string(got) != number {
			t.Errorf("a value of a later API is written as %s, %v: want %s", got, err, number)
		}
		if got, err := enum.read([]byte(number)); err != nil || got != later {
			t.Errorf("%s read %s as %d, %v", enum.name, number, got, err)
		}
		for _, data := range []string{`"NO_SUCH_VALUE"`, `{}`, `1.5`} {
			if got, err := enum.read([]byte(data)); err == nil {
				t.Errorf("%s read %s as %d", enum.name, data, got)
			}
		}
	}
}
