// Code generated by protoc-gen-panel-go from v1/panel.proto. DO NOT EDIT.

package pethost

import (
	"context"
	"errors"
	"io"
	"iter"
	"net/http"
	"strconv"
	"time"

	"connectrpc.com/connect/v2"
	"connectrpc.com/connect/v2/connecthttp"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// This file is the part of the package that no proto file decides: the client's configuration,
// the status codes, how a stream is ranged over and the helpers of the generated converters. It
// names nothing of the API.

// Config is what a [Client] is made of.
type Config struct {
	// The account's API token, "pth_...": every call carries it.
	Token string
	// Where the API is served. Empty = "https://console.pethost.dev".
	BaseURL string
	// What sends the requests. nil = [http.DefaultClient]. A Timeout of it bounds each call
	// whole, so it ends a stream too.
	HTTPClient *http.Client
}

const defaultBaseURL = "https://console.pethost.dev"

// userAgent says which client calls, and of which release.
const userAgent = "pethost-go/0.1.1"

// newTransport is the wire layer's client for config: the Connect protocol over HTTP, by POST
// with binary protobuf, a stream's responses in the one answer.
func newTransport(config Config) *connect.Client {
	baseURL := config.BaseURL
	if baseURL == "" {
		baseURL = defaultBaseURL
	}
	httpClient := config.HTTPClient
	if httpClient == nil {
		httpClient = http.DefaultClient
	}
	return connect.NewClient(connecthttp.NewTransport(caller{httpClient, config.Token}, baseURL))
}

// caller says on each request who calls: the account, by its token, and this package.
type caller struct {
	next  *http.Client
	token string
}

func (c caller) Do(request *http.Request) (*http.Response, error) {
	request = request.Clone(request.Context())
	request.Header.Set("User-Agent", userAgent)
	if c.token != "" {
		request.Header.Set("Authorization", "Bearer "+c.token)
	}
	return c.next.Do(request)
}

// A Code is the kind of an [Error]. The API's comments name the codes as String writes them:
// "NOT_FOUND" is [CodeNotFound], and the package's documentation says what each means.
//
// The API may add codes: one that this version of the package does not know keeps its number
// and prints as "Code(42)".
type Code uint32

const (
	CodeCanceled           Code = 1 // The context was cancelled.
	CodeUnknown            Code = 2 // The failure has no code, as when the answer is not the API's.
	CodeInvalidArgument    Code = 3
	CodeDeadlineExceeded   Code = 4 // The context's deadline passed.
	CodeNotFound           Code = 5
	CodeAlreadyExists      Code = 6
	CodePermissionDenied   Code = 7
	CodeResourceExhausted  Code = 8
	CodeFailedPrecondition Code = 9
	CodeAborted            Code = 10
	CodeOutOfRange         Code = 11
	CodeUnimplemented      Code = 12
	CodeInternal           Code = 13
	CodeUnavailable        Code = 14 // Also when the API could not be reached.
	CodeDataLoss           Code = 15
	CodeUnauthenticated    Code = 16
)

// String is the code as the API's documentation writes it: "NOT_FOUND" for [CodeNotFound].
func (c Code) String() string {
	switch c {
	case CodeCanceled:
		return "CANCELED"
	case CodeUnknown:
		return "UNKNOWN"
	case CodeInvalidArgument:
		return "INVALID_ARGUMENT"
	case CodeDeadlineExceeded:
		return "DEADLINE_EXCEEDED"
	case CodeNotFound:
		return "NOT_FOUND"
	case CodeAlreadyExists:
		return "ALREADY_EXISTS"
	case CodePermissionDenied:
		return "PERMISSION_DENIED"
	case CodeResourceExhausted:
		return "RESOURCE_EXHAUSTED"
	case CodeFailedPrecondition:
		return "FAILED_PRECONDITION"
	case CodeAborted:
		return "ABORTED"
	case CodeOutOfRange:
		return "OUT_OF_RANGE"
	case CodeUnimplemented:
		return "UNIMPLEMENTED"
	case CodeInternal:
		return "INTERNAL"
	case CodeUnavailable:
		return "UNAVAILABLE"
	case CodeDataLoss:
		return "DATA_LOSS"
	case CodeUnauthenticated:
		return "UNAUTHENTICATED"
	}
	return "Code(" + strconv.Itoa(int(c)) + ")"
}

// Each code is the wire layer's number: one that differs does not compile.
func _() {
	var same [1]struct{}
	_ = same[CodeCanceled-Code(connect.CodeCanceled)]
	_ = same[CodeUnknown-Code(connect.CodeUnknown)]
	_ = same[CodeInvalidArgument-Code(connect.CodeInvalidArgument)]
	_ = same[CodeDeadlineExceeded-Code(connect.CodeDeadlineExceeded)]
	_ = same[CodeNotFound-Code(connect.CodeNotFound)]
	_ = same[CodeAlreadyExists-Code(connect.CodeAlreadyExists)]
	_ = same[CodePermissionDenied-Code(connect.CodePermissionDenied)]
	_ = same[CodeResourceExhausted-Code(connect.CodeResourceExhausted)]
	_ = same[CodeFailedPrecondition-Code(connect.CodeFailedPrecondition)]
	_ = same[CodeAborted-Code(connect.CodeAborted)]
	_ = same[CodeOutOfRange-Code(connect.CodeOutOfRange)]
	_ = same[CodeUnimplemented-Code(connect.CodeUnimplemented)]
	_ = same[CodeInternal-Code(connect.CodeInternal)]
	_ = same[CodeUnavailable-Code(connect.CodeUnavailable)]
	_ = same[CodeDataLoss-Code(connect.CodeDataLoss)]
	_ = same[CodeUnauthenticated-Code(connect.CodeUnauthenticated)]
}

// Error is the failure as text: "pethost: NOT_FOUND: no project \"shop\"".
func (e *Error) Error() string {
	if e.Message == "" {
		return "pethost: " + e.Code.String()
	}
	return "pethost: " + e.Code.String() + ": " + e.Message
}

// Unwrap is what failed below the API, such as [context.Canceled] or a network error; nil for
// a failure the API itself answered with.
func (e *Error) Unwrap() error {
	return e.cause
}

// ── Streams ────────────────────────────────────────────────────────────────

// wireStream is a server stream of the wire layer, whose every RPC has a type of its own for it.
type wireStream[W proto.Message] interface {
	Receive() (W, error)
	Close() error
}

// responses is a server stream as its method returns it: the call is made when the loop starts,
// each response is yielded as it arrives, and an error, the call's or the stream's, is yielded
// once and ends the loop. The stream's own end is no error, and a pulse is passed over. However
// the loop ends, the stream is closed, which ends the call.
func responses[Q any, W proto.Message, R any, S wireStream[W]](ctx context.Context, call func(context.Context, *Q) (S, error), request *Q, fromWire func(W) R) iter.Seq2[*R, error] {
	return func(yield func(*R, error) bool) {
		stream, err := call(ctx, request)
		if err != nil {
			yield(nil, fromWireError(err))
			return
		}
		defer stream.Close()

		for {
			response, err := stream.Receive()
			if errors.Is(err, io.EOF) {
				return
			}
			if err != nil {
				yield(nil, fromWireError(err))
				return
			}
			if isPulse(response) {
				continue
			}
			if !yield(new(fromWire(response)), nil) {
				return
			}
		}
	}
}

// isPulse reports whether a stream's response is the API's pulse: the response with nothing set
// that it sends after a while with nothing to send, so that no proxy on the way ends the stream
// as dead. Such a response is no bytes on the wire, and one that says anything is some.
func isPulse(response proto.Message) bool {
	return proto.Size(response) == 0
}

// ── The converters' helpers ────────────────────────────────────────────────

// orZero is a request as its method takes it: a nil one is the empty one.
func orZero[T any](request *T) T {
	if request == nil {
		var empty T
		return empty
	}
	return *request
}

// unknownOf is what a wire message holds that the wire layer has no field for.
func unknownOf(wire proto.Message) string {
	return string(wire.ProtoReflect().GetUnknown())
}

// withUnknown is a wire message with what unknownOf read from the one it was made after.
func withUnknown[M proto.Message](wire M, unknown string) M {
	if unknown != "" {
		wire.ProtoReflect().SetUnknown(protoreflect.RawFields(unknown))
	}
	return wire
}

// nonZero is a plain field for the wire: left out when it is zero.
func nonZero[T comparable](value T) *T {
	var zero T
	if value == zero {
		return nil
	}
	return &value
}

// nonEmpty is a plain bytes field for the wire: left out when it is empty.
func nonEmpty(value []byte) []byte {
	if len(value) == 0 {
		return nil
	}
	return value
}

// presentBytes is a bytes member of a oneof for the wire: set even when it is empty.
func presentBytes[B ~[]byte](value B) []byte {
	if value == nil {
		return []byte{}
	}
	return value
}

// optional is a field marked (optional) from the wire: nil when it is absent.
func optional[T any](has bool, value T) *T {
	if !has {
		return nil
	}
	return &value
}

func pointerFromWire[W, P any](wire *W, convert func(*W) P) *P {
	if wire == nil {
		return nil
	}
	return new(convert(wire))
}

func pointerToWire[P, W any](value *P, convert func(P) *W) *W {
	if value == nil {
		return nil
	}
	return convert(*value)
}

func sliceFromWire[W, P any](wire []W, convert func(W) P) []P {
	if len(wire) == 0 {
		return nil
	}
	values := make([]P, len(wire))
	for i, item := range wire {
		values[i] = convert(item)
	}
	return values
}

func sliceToWire[P, W any](values []P, convert func(P) W) []W {
	if len(values) == 0 {
		return nil
	}
	wire := make([]W, len(values))
	for i, value := range values {
		wire[i] = convert(value)
	}
	return wire
}

// timeFromWire is a Timestamp as a time: the zero time when it is absent.
func timeFromWire(wire *timestamppb.Timestamp) time.Time {
	if wire == nil {
		return time.Time{}
	}
	return wire.AsTime()
}

// timeToWire is a time for the wire: left out when it is the zero time.
func timeToWire(value time.Time) *timestamppb.Timestamp {
	if value.IsZero() {
		return nil
	}
	return timestamppb.New(value)
}
