// Code generated by protoc-gen-panel-go from v1/panel.proto. DO NOT EDIT.

package pethost

import (
	"context"
	"net/http"

	"connectrpc.com/connect/v2"
	"connectrpc.com/connect/v2/connecthttp"
	"github.com/pethost-dev/sdk/go/internal/panelv1"
	"github.com/pethost-dev/sdk/go/internal/panelv1/panelv1connect"
)

// fake is the API as the checks need it: it keeps the request of each call and answers with
// what the check prepared.
type fake struct {
	panelv1connect.UnimplementedPanelServiceHandler
	exchange
}

// handler serves the fake as the API is served.
func (f *fake) handler() http.Handler {
	server := connect.NewServer()
	panelv1connect.RegisterPanelServiceHandler(server, f)
	mux := http.NewServeMux()
	connecthttp.Mount(mux, server)
	return mux
}

func (f *fake) GetMachine(_ context.Context, request *panelv1.GetMachineRequest) (*panelv1.GetMachineResponse, error) {
	return answer[*panelv1.GetMachineResponse](&f.exchange, request)
}

func (f *fake) RunMachineAction(_ context.Context, request *panelv1.RunMachineActionRequest) (*panelv1.RunMachineActionResponse, error) {
	return answer[*panelv1.RunMachineActionResponse](&f.exchange, request)
}

func (f *fake) GetProject(_ context.Context, request *panelv1.GetProjectRequest) (*panelv1.GetProjectResponse, error) {
	return answer[*panelv1.GetProjectResponse](&f.exchange, request)
}

func (f *fake) CreateProject(_ context.Context, request *panelv1.CreateProjectRequest) (*panelv1.CreateProjectResponse, error) {
	return answer[*panelv1.CreateProjectResponse](&f.exchange, request)
}

func (f *fake) DeployProject(_ context.Context, request *panelv1.DeployProjectRequest) (*panelv1.DeployProjectResponse, error) {
	return answer[*panelv1.DeployProjectResponse](&f.exchange, request)
}

func (f *fake) ListCommits(_ context.Context, request *panelv1.ListCommitsRequest) (*panelv1.ListCommitsResponse, error) {
	return answer[*panelv1.ListCommitsResponse](&f.exchange, request)
}

func (f *fake) RunProjectAction(_ context.Context, request *panelv1.RunProjectActionRequest) (*panelv1.RunProjectActionResponse, error) {
	return answer[*panelv1.RunProjectActionResponse](&f.exchange, request)
}

func (f *fake) GetOperation(_ context.Context, request *panelv1.GetOperationRequest) (*panelv1.GetOperationResponse, error) {
	return answer[*panelv1.GetOperationResponse](&f.exchange, request)
}

func (f *fake) QueryHttpTraffic(_ context.Context, request *panelv1.QueryHttpTrafficRequest) (*panelv1.QueryHttpTrafficResponse, error) {
	return answer[*panelv1.QueryHttpTrafficResponse](&f.exchange, request)
}

func (f *fake) QueryContainerLogs(_ context.Context, request *panelv1.QueryContainerLogsRequest) (*panelv1.QueryContainerLogsResponse, error) {
	return answer[*panelv1.QueryContainerLogsResponse](&f.exchange, request)
}

func (f *fake) RunServiceCommand(_ context.Context, request *panelv1.RunServiceCommandRequest) (*panelv1.RunServiceCommandResponse, error) {
	return answer[*panelv1.RunServiceCommandResponse](&f.exchange, request)
}

func (f *fake) ReadPath(_ context.Context, request *panelv1.ReadPathRequest) (*panelv1.ReadPathResponse, error) {
	return answer[*panelv1.ReadPathResponse](&f.exchange, request)
}

func (f *fake) CreateTransfer(_ context.Context, request *panelv1.CreateTransferRequest) (*panelv1.CreateTransferResponse, error) {
	return answer[*panelv1.CreateTransferResponse](&f.exchange, request)
}

// calls are the package's methods.
var calls = []call{
	callOf("GetMachine", (*Client).GetMachine, sampleGetMachineRequest, sampleGetMachineResponse, &panelv1.GetMachineRequest{}, &panelv1.GetMachineResponse{}),
	callOf("RunMachineAction", (*Client).RunMachineAction, sampleRunMachineActionRequest, sampleRunMachineActionResponse, &panelv1.RunMachineActionRequest{}, &panelv1.RunMachineActionResponse{}),
	callOf("GetProject", (*Client).GetProject, sampleGetProjectRequest, sampleGetProjectResponse, &panelv1.GetProjectRequest{}, &panelv1.GetProjectResponse{}),
	callOf("CreateProject", (*Client).CreateProject, sampleCreateProjectRequest, sampleCreateProjectResponse, &panelv1.CreateProjectRequest{}, &panelv1.CreateProjectResponse{}),
	callOf("DeployProject", (*Client).DeployProject, sampleDeployProjectRequest, sampleDeployProjectResponse, &panelv1.DeployProjectRequest{}, &panelv1.DeployProjectResponse{}),
	callOf("ListCommits", (*Client).ListCommits, sampleListCommitsRequest, sampleListCommitsResponse, &panelv1.ListCommitsRequest{}, &panelv1.ListCommitsResponse{}),
	callOf("RunProjectAction", (*Client).RunProjectAction, sampleRunProjectActionRequest, sampleRunProjectActionResponse, &panelv1.RunProjectActionRequest{}, &panelv1.RunProjectActionResponse{}),
	callOf("GetOperation", (*Client).GetOperation, sampleGetOperationRequest, sampleGetOperationResponse, &panelv1.GetOperationRequest{}, &panelv1.GetOperationResponse{}),
	callOf("QueryHTTPTraffic", (*Client).QueryHTTPTraffic, sampleQueryHTTPTrafficRequest, sampleQueryHTTPTrafficResponse, &panelv1.QueryHttpTrafficRequest{}, &panelv1.QueryHttpTrafficResponse{}),
	callOf("QueryContainerLogs", (*Client).QueryContainerLogs, sampleQueryContainerLogsRequest, sampleQueryContainerLogsResponse, &panelv1.QueryContainerLogsRequest{}, &panelv1.QueryContainerLogsResponse{}),
	callOf("RunServiceCommand", (*Client).RunServiceCommand, sampleRunServiceCommandRequest, sampleRunServiceCommandResponse, &panelv1.RunServiceCommandRequest{}, &panelv1.RunServiceCommandResponse{}),
	callOf("ReadPath", (*Client).ReadPath, sampleReadPathRequest, sampleReadPathResponse, &panelv1.ReadPathRequest{}, &panelv1.ReadPathResponse{}),
	callOf("CreateTransfer", (*Client).CreateTransfer, sampleCreateTransferRequest, sampleCreateTransferResponse, &panelv1.CreateTransferRequest{}, &panelv1.CreateTransferResponse{}),
}

// details are the error details.
var details = []detail{
	{&panelv1.ProjectBusy{}, func(s seed) Error { return Error{ProjectBusy: new(sampleProjectBusy(s))} }},
	{&panelv1.ProjectChanged{}, func(s seed) Error { return Error{ProjectChanged: new(sampleProjectChanged(s))} }},
	{&panelv1.MachineUnreachable{}, func(s seed) Error { return Error{MachineUnreachable: new(sampleMachineUnreachable(s))} }},
	{&panelv1.NoMachine{}, func(s seed) Error { return Error{NoMachine: new(sampleNoMachine(s))} }},
}

// shapes are the package's structs, each beside its wire message.
var shapes = []shape{
	{GetMachineRequest{}, &panelv1.GetMachineRequest{}},
	{GetMachineResponse{}, &panelv1.GetMachineResponse{}},
	{Machine{}, &panelv1.Machine{}},
	{MachineSession{}, &panelv1.MachineSession{}},
	{DiskUsage{}, &panelv1.DiskUsage{}},
	{SSHKey{}, &panelv1.SshKey{}},
	{GithubConnection{}, &panelv1.GithubConnection{}},
	{GithubRepository{}, &panelv1.GithubRepository{}},
	{DeletedProject{}, &panelv1.DeletedProject{}},
	{RunMachineActionRequest{}, &panelv1.RunMachineActionRequest{}},
	{RestartMachineAction{}, &panelv1.RestartMachineAction{}},
	{RunMachineActionResponse{}, &panelv1.RunMachineActionResponse{}},
	{ProjectMetadata{}, &panelv1.ProjectMetadata{}},
	{ProjectSummary{}, &panelv1.ProjectSummary{}},
	{ServiceSummary{}, &panelv1.ServiceSummary{}},
	{ProjectProblem{}, &panelv1.ProjectProblem{}},
	{GetProjectRequest{}, &panelv1.GetProjectRequest{}},
	{GetProjectResponse{}, &panelv1.GetProjectResponse{}},
	{Project{}, &panelv1.Project{}},
	{RunningServicesAction{}, &panelv1.RunningServicesAction{}},
	{ProjectSource{}, &panelv1.ProjectSource{}},
	{GithubSource{}, &panelv1.GithubSource{}},
	{GithubCommit{}, &panelv1.GithubCommit{}},
	{Service{}, &panelv1.Service{}},
	{PublishedPort{}, &panelv1.PublishedPort{}},
	{VolumeMount{}, &panelv1.VolumeMount{}},
	{HealthCheck{}, &panelv1.HealthCheck{}},
	{EnvironmentVariable{}, &panelv1.EnvironmentVariable{}},
	{Volume{}, &panelv1.Volume{}},
	{VolumeMountedBy{}, &panelv1.VolumeMountedBy{}},
	{Host{}, &panelv1.Host{}},
	{Route{}, &panelv1.Route{}},
	{Operation{}, &panelv1.Operation{}},
	{Snapshot{}, &panelv1.Snapshot{}},
	{HTTPTrafficSummary{}, &panelv1.HttpTrafficSummary{}},
	{CreateProjectRequest{}, &panelv1.CreateProjectRequest{}},
	{CreateProjectResponse{}, &panelv1.CreateProjectResponse{}},
	{DeployProjectRequest{}, &panelv1.DeployProjectRequest{}},
	{MountVolume{}, &panelv1.MountVolume{}},
	{ProjectExtension{}, &panelv1.ProjectExtension{}},
	{FileChange{}, &panelv1.FileChange{}},
	{DeployProjectResponse{}, &panelv1.DeployProjectResponse{}},
	{SpecViolation{}, &panelv1.SpecViolation{}},
	{ListCommitsRequest{}, &panelv1.ListCommitsRequest{}},
	{ListCommitsResponse{}, &panelv1.ListCommitsResponse{}},
	{BranchCommit{}, &panelv1.BranchCommit{}},
	{RunProjectActionRequest{}, &panelv1.RunProjectActionRequest{}},
	{ServicesAction{}, &panelv1.ServicesAction{}},
	{RecreateServiceAction{}, &panelv1.RecreateServiceAction{}},
	{BackUpAction{}, &panelv1.BackUpAction{}},
	{RestoreSnapshotAction{}, &panelv1.RestoreSnapshotAction{}},
	{CancelOperationAction{}, &panelv1.CancelOperationAction{}},
	{DeleteProjectAction{}, &panelv1.DeleteProjectAction{}},
	{RunProjectActionResponse{}, &panelv1.RunProjectActionResponse{}},
	{GetOperationRequest{}, &panelv1.GetOperationRequest{}},
	{GetOperationResponse{}, &panelv1.GetOperationResponse{}},
	{OperationLogLine{}, &panelv1.OperationLogLine{}},
	{HTTPTrafficFilter{}, &panelv1.HttpTrafficFilter{}},
	{QueryHTTPTrafficRequest{}, &panelv1.QueryHttpTrafficRequest{}},
	{QueryHTTPTrafficResponse{}, &panelv1.QueryHttpTrafficResponse{}},
	{HTTPTrafficBucket{}, &panelv1.HttpTrafficBucket{}},
	{HTTPPathTraffic{}, &panelv1.HttpPathTraffic{}},
	{HTTPRequest{}, &panelv1.HttpRequest{}},
	{ContainerLogFilter{}, &panelv1.ContainerLogFilter{}},
	{QueryContainerLogsRequest{}, &panelv1.QueryContainerLogsRequest{}},
	{QueryContainerLogsResponse{}, &panelv1.QueryContainerLogsResponse{}},
	{LogLine{}, &panelv1.LogLine{}},
	{RunServiceCommandRequest{}, &panelv1.RunServiceCommandRequest{}},
	{RunServiceCommandResponse{}, &panelv1.RunServiceCommandResponse{}},
	{FileEntry{}, &panelv1.FileEntry{}},
	{ReadPathRequest{}, &panelv1.ReadPathRequest{}},
	{ReadPathResponse{}, &panelv1.ReadPathResponse{}},
	{CreateTransferRequest{}, &panelv1.CreateTransferRequest{}},
	{ArchiveUpload{}, &panelv1.ArchiveUpload{}},
	{FileUpload{}, &panelv1.FileUpload{}},
	{PathDownload{}, &panelv1.PathDownload{}},
	{CreateTransferResponse{}, &panelv1.CreateTransferResponse{}},
	{ProjectBusy{}, &panelv1.ProjectBusy{}},
	{ProjectChanged{}, &panelv1.ProjectChanged{}},
	{MachineUnreachable{}, &panelv1.MachineUnreachable{}},
	{NoMachine{}, &panelv1.NoMachine{}},
}

// enums are the package's enums, each beside the wire layer's.
var enums = []enum{
	enumOf[MachineSessionKind, panelv1.MachineSessionKind]("MachineSessionKind"),
	enumOf[ProjectProblemKind, panelv1.ProjectProblemKind]("ProjectProblemKind"),
	enumOf[ServicesActionKind, panelv1.ServicesActionKind]("ServicesActionKind"),
	enumOf[ServiceState, panelv1.ServiceState]("ServiceState"),
	enumOf[RestartPolicy, panelv1.RestartPolicy]("RestartPolicy"),
	enumOf[HealthStatus, panelv1.HealthStatus]("HealthStatus"),
	enumOf[CertificateSource, panelv1.CertificateSource]("CertificateSource"),
	enumOf[OperationKind, panelv1.OperationKind]("OperationKind"),
	enumOf[OperationStatus, panelv1.OperationStatus]("OperationStatus"),
	enumOf[DeployFailureReason, panelv1.DeployFailureReason]("DeployFailureReason"),
	enumOf[OutputStream, panelv1.OutputStream]("OutputStream"),
	enumOf[FileType, panelv1.FileType]("FileType"),
	enumOf[FileLocation, panelv1.FileLocation]("FileLocation"),
	enumOf[NoMachineReason, panelv1.NoMachineReason]("NoMachineReason"),
}

func sampleGetMachineRequest(s seed) GetMachineRequest {
	return GetMachineRequest{}
}

func sampleGetMachineResponse(s seed) GetMachineResponse {
	return GetMachineResponse{
		Machine:         pointer(s.at("pethost.panel.v1.GetMachineResponse.machine"), sampleMachine),
		Projects:        list(s.at("pethost.panel.v1.GetMachineResponse.projects"), sampleProjectSummary),
		DeletedProjects: list(s.at("pethost.panel.v1.GetMachineResponse.deleted_projects"), sampleDeletedProject),
		Github:          pointer(s.at("pethost.panel.v1.GetMachineResponse.github"), sampleGithubConnection),
	}
}

func sampleMachine(s seed) Machine {
	return Machine{
		Name:                       plain[string](s.at("pethost.panel.v1.Machine.name")),
		Location:                   plain[string](s.at("pethost.panel.v1.Machine.location")),
		SampleTime:                 instant(s.at("pethost.panel.v1.Machine.sample_time")),
		CPUUsedCores:               plain[float64](s.at("pethost.panel.v1.Machine.cpu_used_cores")),
		CPUTotalCores:              plain[float64](s.at("pethost.panel.v1.Machine.cpu_total_cores")),
		MemoryUsedBytes:            plain[uint64](s.at("pethost.panel.v1.Machine.memory_used_bytes")),
		MemoryTotalBytes:           plain[uint64](s.at("pethost.panel.v1.Machine.memory_total_bytes")),
		DiskUsedBytes:              plain[uint64](s.at("pethost.panel.v1.Machine.disk_used_bytes")),
		DiskTotalBytes:             plain[uint64](s.at("pethost.panel.v1.Machine.disk_total_bytes")),
		DiskUsage:                  pointer(s.at("pethost.panel.v1.Machine.disk_usage"), sampleDiskUsage),
		Hostname:                   plain[string](s.at("pethost.panel.v1.Machine.hostname")),
		SSHHostKeyFingerprint:      plain[string](s.at("pethost.panel.v1.Machine.ssh_host_key_fingerprint")),
		SSHKeys:                    list(s.at("pethost.panel.v1.Machine.ssh_keys"), sampleSSHKey),
		BackupsEnabled:             plain[bool](s.at("pethost.panel.v1.Machine.backups_enabled")),
		SnapshotListTime:           instant(s.at("pethost.panel.v1.Machine.snapshot_list_time")),
		SnapshotListFailureMessage: plain[string](s.at("pethost.panel.v1.Machine.snapshot_list_failure_message")),
		BackupRetentionHours:       plain[uint32](s.at("pethost.panel.v1.Machine.backup_retention_hours")),
		AcmeEnabled:                plain[bool](s.at("pethost.panel.v1.Machine.acme_enabled")),
		AppsDomain:                 plain[string](s.at("pethost.panel.v1.Machine.apps_domain")),
		DaemonVersion:              plain[string](s.at("pethost.panel.v1.Machine.daemon_version")),
		DockerVersion:              plain[string](s.at("pethost.panel.v1.Machine.docker_version")),
		BootTime:                   instant(s.at("pethost.panel.v1.Machine.boot_time")),
		RestartRequiredTime:        instant(s.at("pethost.panel.v1.Machine.restart_required_time")),
		ScheduledRestartTime:       instant(s.at("pethost.panel.v1.Machine.scheduled_restart_time")),
		Sessions:                   list(s.at("pethost.panel.v1.Machine.sessions"), sampleMachineSession),
	}
}

func sampleMachineSession(s seed) MachineSession {
	return MachineSession{
		SessionID:         plain[string](s.at("pethost.panel.v1.MachineSession.session_id")),
		Kind:              plain[MachineSessionKind](s.at("pethost.panel.v1.MachineSession.kind")),
		ProjectID:         plain[string](s.at("pethost.panel.v1.MachineSession.project_id")),
		Service:           plain[string](s.at("pethost.panel.v1.MachineSession.service")),
		Port:              plain[uint32](s.at("pethost.panel.v1.MachineSession.port")),
		StartTime:         instant(s.at("pethost.panel.v1.MachineSession.start_time")),
		ClientAddress:     plain[string](s.at("pethost.panel.v1.MachineSession.client_address")),
		SSHKeyLabel:       plain[string](s.at("pethost.panel.v1.MachineSession.ssh_key_label")),
		SSHKeyFingerprint: plain[string](s.at("pethost.panel.v1.MachineSession.ssh_key_fingerprint")),
	}
}

func sampleDiskUsage(s seed) DiskUsage {
	return DiskUsage{
		ImagesBytes:          plain[uint64](s.at("pethost.panel.v1.DiskUsage.images_bytes")),
		BuildCacheBytes:      marked[uint64](s.at("pethost.panel.v1.DiskUsage.build_cache_bytes")),
		VolumesBytes:         plain[uint64](s.at("pethost.panel.v1.DiskUsage.volumes_bytes")),
		ContainerLayersBytes: plain[uint64](s.at("pethost.panel.v1.DiskUsage.container_layers_bytes")),
		ProjectFilesBytes:    plain[uint64](s.at("pethost.panel.v1.DiskUsage.project_files_bytes")),
		ContainerLogsBytes:   plain[uint64](s.at("pethost.panel.v1.DiskUsage.container_logs_bytes")),
		HTTPTrafficBytes:     plain[uint64](s.at("pethost.panel.v1.DiskUsage.http_traffic_bytes")),
	}
}

func sampleSSHKey(s seed) SSHKey {
	return SSHKey{
		PublicKey:   plain[string](s.at("pethost.panel.v1.SshKey.public_key")),
		Label:       plain[string](s.at("pethost.panel.v1.SshKey.label")),
		Fingerprint: plain[string](s.at("pethost.panel.v1.SshKey.fingerprint")),
		unknown:     later(s),
	}
}

func sampleGithubConnection(s seed) GithubConnection {
	return GithubConnection{
		AppName:         plain[string](s.at("pethost.panel.v1.GithubConnection.app_name")),
		InstallURL:      plain[string](s.at("pethost.panel.v1.GithubConnection.install_url")),
		Repositories:    list(s.at("pethost.panel.v1.GithubConnection.repositories"), sampleGithubRepository),
		RepositoryCount: plain[uint32](s.at("pethost.panel.v1.GithubConnection.repository_count")),
		WebhooksEnabled: plain[bool](s.at("pethost.panel.v1.GithubConnection.webhooks_enabled")),
	}
}

func sampleGithubRepository(s seed) GithubRepository {
	return GithubRepository{
		Repository:    plain[string](s.at("pethost.panel.v1.GithubRepository.repository")),
		DefaultBranch: plain[string](s.at("pethost.panel.v1.GithubRepository.default_branch")),
		Private:       plain[bool](s.at("pethost.panel.v1.GithubRepository.private")),
		PushTime:      instant(s.at("pethost.panel.v1.GithubRepository.push_time")),
	}
}

func sampleDeletedProject(s seed) DeletedProject {
	return DeletedProject{
		ProjectID:      plain[string](s.at("pethost.panel.v1.DeletedProject.project_id")),
		NewestSnapshot: pointer(s.at("pethost.panel.v1.DeletedProject.newest_snapshot"), sampleSnapshot),
		SnapshotCount:  plain[uint32](s.at("pethost.panel.v1.DeletedProject.snapshot_count")),
	}
}

func sampleRunMachineActionRequest(s seed) RunMachineActionRequest {
	return RunMachineActionRequest{
		Action: sampleRunMachineActionAction(s.at("pethost.panel.v1.RunMachineActionRequest.action")),
	}
}

func sampleRunMachineActionAction(s seed) RunMachineActionAction {
	switch s.member(5) {
	case 0:
		return RunMachineActionAddSSHKey(member(s, sampleSSHKey))
	case 1:
		return RunMachineActionRemoveSSHKeyFingerprint(plain[string](s))
	case 2:
		return RunMachineActionRestartMachine(member(s, sampleRestartMachineAction))
	case 3:
		return RunMachineActionCancelRestart(plain[bool](s))
	case 4:
		return RunMachineActionEndSessionID(plain[string](s))
	}
	return nil
}

func sampleRestartMachineAction(s seed) RestartMachineAction {
	return RestartMachineAction{
		RestartTime:         instant(s.at("pethost.panel.v1.RestartMachineAction.restart_time")),
		AtMaintenanceWindow: plain[bool](s.at("pethost.panel.v1.RestartMachineAction.at_maintenance_window")),
		InterruptOperations: plain[bool](s.at("pethost.panel.v1.RestartMachineAction.interrupt_operations")),
	}
}

func sampleRunMachineActionResponse(s seed) RunMachineActionResponse {
	return RunMachineActionResponse{
		Machine: pointer(s.at("pethost.panel.v1.RunMachineActionResponse.machine"), sampleMachine),
	}
}

func sampleProjectMetadata(s seed) ProjectMetadata {
	return ProjectMetadata{
		Name:        marked[string](s.at("pethost.panel.v1.ProjectMetadata.name")),
		Emoji:       marked[string](s.at("pethost.panel.v1.ProjectMetadata.emoji")),
		Description: marked[string](s.at("pethost.panel.v1.ProjectMetadata.description")),
		Notes:       marked[string](s.at("pethost.panel.v1.ProjectMetadata.notes")),
		unknown:     later(s),
	}
}

func sampleProjectSummary(s seed) ProjectSummary {
	return ProjectSummary{
		ProjectID:          plain[string](s.at("pethost.panel.v1.ProjectSummary.project_id")),
		Metadata:           pointer(s.at("pethost.panel.v1.ProjectSummary.metadata"), sampleProjectMetadata),
		Problems:           list(s.at("pethost.panel.v1.ProjectSummary.problems"), sampleProjectProblem),
		Services:           list(s.at("pethost.panel.v1.ProjectSummary.services"), sampleServiceSummary),
		URL:                plain[string](s.at("pethost.panel.v1.ProjectSummary.url")),
		Hosts:              list(s.at("pethost.panel.v1.ProjectSummary.hosts"), scalar[string]),
		HTTPTrafficLastDay: pointer(s.at("pethost.panel.v1.ProjectSummary.http_traffic_last_day"), sampleHTTPTrafficSummary),
		CPUUsedCores:       plain[float64](s.at("pethost.panel.v1.ProjectSummary.cpu_used_cores")),
		MemoryUsedBytes:    plain[uint64](s.at("pethost.panel.v1.ProjectSummary.memory_used_bytes")),
		DeployTime:         instant(s.at("pethost.panel.v1.ProjectSummary.deploy_time")),
		RunningOperations:  list(s.at("pethost.panel.v1.ProjectSummary.running_operations"), sampleOperation),
		Pinned:             plain[bool](s.at("pethost.panel.v1.ProjectSummary.pinned")),
		DiskUsedBytes:      plain[uint64](s.at("pethost.panel.v1.ProjectSummary.disk_used_bytes")),
	}
}

func sampleServiceSummary(s seed) ServiceSummary {
	return ServiceSummary{
		Service: plain[string](s.at("pethost.panel.v1.ServiceSummary.service")),
		State:   plain[ServiceState](s.at("pethost.panel.v1.ServiceSummary.state")),
	}
}

func sampleProjectProblem(s seed) ProjectProblem {
	return ProjectProblem{
		Kind:           plain[ProjectProblemKind](s.at("pethost.panel.v1.ProjectProblem.kind")),
		Service:        plain[string](s.at("pethost.panel.v1.ProjectProblem.service")),
		OperationID:    plain[string](s.at("pethost.panel.v1.ProjectProblem.operation_id")),
		SinceTime:      instant(s.at("pethost.panel.v1.ProjectProblem.since_time")),
		ProblemMessage: plain[string](s.at("pethost.panel.v1.ProjectProblem.problem_message")),
	}
}

func sampleGetProjectRequest(s seed) GetProjectRequest {
	return GetProjectRequest{
		ProjectID:           plain[string](s.at("pethost.panel.v1.GetProjectRequest.project_id")),
		IncludeSecretValues: plain[bool](s.at("pethost.panel.v1.GetProjectRequest.include_secret_values")),
		SnapshotsBefore:     instant(s.at("pethost.panel.v1.GetProjectRequest.snapshots_before")),
		SnapshotsVolume:     plain[string](s.at("pethost.panel.v1.GetProjectRequest.snapshots_volume")),
	}
}

func sampleGetProjectResponse(s seed) GetProjectResponse {
	return GetProjectResponse{
		Project: pointer(s.at("pethost.panel.v1.GetProjectResponse.project"), sampleProject),
	}
}

func sampleProject(s seed) Project {
	return Project{
		ProjectID:             plain[string](s.at("pethost.panel.v1.Project.project_id")),
		Metadata:              pointer(s.at("pethost.panel.v1.Project.metadata"), sampleProjectMetadata),
		Problems:              list(s.at("pethost.panel.v1.Project.problems"), sampleProjectProblem),
		URL:                   plain[string](s.at("pethost.panel.v1.Project.url")),
		CPUUsedCores:          plain[float64](s.at("pethost.panel.v1.Project.cpu_used_cores")),
		MemoryUsedBytes:       plain[uint64](s.at("pethost.panel.v1.Project.memory_used_bytes")),
		DeployID:              plain[string](s.at("pethost.panel.v1.Project.deploy_id")),
		DeployStatus:          plain[OperationStatus](s.at("pethost.panel.v1.Project.deploy_status")),
		DeployTime:            instant(s.at("pethost.panel.v1.Project.deploy_time")),
		XPethostAppliesAtOnce: plain[bool](s.at("pethost.panel.v1.Project.x_pethost_applies_at_once")),
		Services:              list(s.at("pethost.panel.v1.Project.services"), sampleService),
		Volumes:               list(s.at("pethost.panel.v1.Project.volumes"), sampleVolume),
		Routes:                list(s.at("pethost.panel.v1.Project.routes"), sampleRoute),
		Hosts:                 list(s.at("pethost.panel.v1.Project.hosts"), sampleHost),
		PasswordProtected:     plain[bool](s.at("pethost.panel.v1.Project.password_protected")),
		Operations:            list(s.at("pethost.panel.v1.Project.operations"), sampleOperation),
		Snapshots:             list(s.at("pethost.panel.v1.Project.snapshots"), sampleSnapshot),
		SnapshotCount:         plain[uint32](s.at("pethost.panel.v1.Project.snapshot_count")),
		SnapshotListTime:      instant(s.at("pethost.panel.v1.Project.snapshot_list_time")),
		HTTPTrafficLastDay:    pointer(s.at("pethost.panel.v1.Project.http_traffic_last_day"), sampleHTTPTrafficSummary),
		Source:                pointer(s.at("pethost.panel.v1.Project.source"), sampleProjectSource),
		RunningServicesAction: pointer(s.at("pethost.panel.v1.Project.running_services_action"), sampleRunningServicesAction),
	}
}

func sampleRunningServicesAction(s seed) RunningServicesAction {
	return RunningServicesAction{
		Kind:      plain[ServicesActionKind](s.at("pethost.panel.v1.RunningServicesAction.kind")),
		Services:  list(s.at("pethost.panel.v1.RunningServicesAction.services"), scalar[string]),
		StartTime: instant(s.at("pethost.panel.v1.RunningServicesAction.start_time")),
	}
}

func sampleProjectSource(s seed) ProjectSource {
	return ProjectSource{
		Kind:    sampleProjectSourceKind(s.at("pethost.panel.v1.ProjectSource.kind")),
		unknown: later(s),
	}
}

func sampleProjectSourceKind(s seed) ProjectSourceKind {
	switch s.member(2) {
	case 0:
		return ProjectSourceFiles(plain[bool](s))
	case 1:
		return ProjectSourceGithub(member(s, sampleGithubSource))
	}
	return nil
}

func sampleGithubSource(s seed) GithubSource {
	return GithubSource{
		Repository:        marked[string](s.at("pethost.panel.v1.GithubSource.repository")),
		Branch:            marked[string](s.at("pethost.panel.v1.GithubSource.branch")),
		Directory:         marked[string](s.at("pethost.panel.v1.GithubSource.directory")),
		AutoDeploy:        marked[bool](s.at("pethost.panel.v1.GithubSource.auto_deploy")),
		NewestCommit:      pointer(s.at("pethost.panel.v1.GithubSource.newest_commit"), sampleGithubCommit),
		DeployedCommit:    pointer(s.at("pethost.panel.v1.GithubSource.deployed_commit"), sampleGithubCommit),
		Pinned:            plain[bool](s.at("pethost.panel.v1.GithubSource.pinned")),
		AutoDeployPending: plain[bool](s.at("pethost.panel.v1.GithubSource.auto_deploy_pending")),
		unknown:           later(s),
	}
}

func sampleGithubCommit(s seed) GithubCommit {
	return GithubCommit{
		Sha:     plain[string](s.at("pethost.panel.v1.GithubCommit.sha")),
		Title:   plain[string](s.at("pethost.panel.v1.GithubCommit.title")),
		URL:     plain[string](s.at("pethost.panel.v1.GithubCommit.url")),
		unknown: later(s),
	}
}

func sampleService(s seed) Service {
	return Service{
		Service:            plain[string](s.at("pethost.panel.v1.Service.service")),
		State:              plain[ServiceState](s.at("pethost.panel.v1.Service.state")),
		ContainerRunning:   plain[bool](s.at("pethost.panel.v1.Service.container_running")),
		Image:              plain[string](s.at("pethost.panel.v1.Service.image")),
		BuildsImage:        plain[bool](s.at("pethost.panel.v1.Service.builds_image")),
		ImageDigest:        plain[string](s.at("pethost.panel.v1.Service.image_digest")),
		ImageSizeBytes:     plain[uint64](s.at("pethost.panel.v1.Service.image_size_bytes")),
		Command:            list(s.at("pethost.panel.v1.Service.command"), scalar[string]),
		RunAsUser:          plain[string](s.at("pethost.panel.v1.Service.run_as_user")),
		StartTime:          instant(s.at("pethost.panel.v1.Service.start_time")),
		FinishTime:         instant(s.at("pethost.panel.v1.Service.finish_time")),
		ExitCode:           marked[int32](s.at("pethost.panel.v1.Service.exit_code")),
		OutOfMemory:        plain[bool](s.at("pethost.panel.v1.Service.out_of_memory")),
		RestartCount:       plain[uint32](s.at("pethost.panel.v1.Service.restart_count")),
		CPUUsedCores:       plain[float64](s.at("pethost.panel.v1.Service.cpu_used_cores")),
		MemoryUsedBytes:    plain[uint64](s.at("pethost.panel.v1.Service.memory_used_bytes")),
		MemoryLimitBytes:   plain[uint64](s.at("pethost.panel.v1.Service.memory_limit_bytes")),
		CPULimitCores:      plain[float64](s.at("pethost.panel.v1.Service.cpu_limit_cores")),
		WritableLayerBytes: plain[uint64](s.at("pethost.panel.v1.Service.writable_layer_bytes")),
		Ports:              list(s.at("pethost.panel.v1.Service.ports"), scalar[uint32]),
		ListeningPorts:     list(s.at("pethost.panel.v1.Service.listening_ports"), scalar[uint32]),
		PublishedPorts:     list(s.at("pethost.panel.v1.Service.published_ports"), samplePublishedPort),
		VolumeMounts:       list(s.at("pethost.panel.v1.Service.volume_mounts"), sampleVolumeMount),
		RestartPolicy:      plain[RestartPolicy](s.at("pethost.panel.v1.Service.restart_policy")),
		HealthCheck:        pointer(s.at("pethost.panel.v1.Service.health_check"), sampleHealthCheck),
		Environment:        list(s.at("pethost.panel.v1.Service.environment"), sampleEnvironmentVariable),
		EnvFiles:           list(s.at("pethost.panel.v1.Service.env_files"), scalar[string]),
		SSHCommand:         plain[string](s.at("pethost.panel.v1.Service.ssh_command")),
	}
}

func samplePublishedPort(s seed) PublishedPort {
	return PublishedPort{
		MachinePort:   plain[uint32](s.at("pethost.panel.v1.PublishedPort.machine_port")),
		ContainerPort: plain[uint32](s.at("pethost.panel.v1.PublishedPort.container_port")),
		Protocol:      plain[string](s.at("pethost.panel.v1.PublishedPort.protocol")),
		MachineOnly:   plain[bool](s.at("pethost.panel.v1.PublishedPort.machine_only")),
	}
}

func sampleVolumeMount(s seed) VolumeMount {
	return VolumeMount{
		Volume:        plain[string](s.at("pethost.panel.v1.VolumeMount.volume")),
		ContainerPath: plain[string](s.at("pethost.panel.v1.VolumeMount.container_path")),
	}
}

func sampleHealthCheck(s seed) HealthCheck {
	return HealthCheck{
		Command:                 list(s.at("pethost.panel.v1.HealthCheck.command"), scalar[string]),
		IntervalSeconds:         plain[uint32](s.at("pethost.panel.v1.HealthCheck.interval_seconds")),
		Status:                  plain[HealthStatus](s.at("pethost.panel.v1.HealthCheck.status")),
		ConsecutiveFailureCount: plain[uint32](s.at("pethost.panel.v1.HealthCheck.consecutive_failure_count")),
		RecentResultsPassed:     list(s.at("pethost.panel.v1.HealthCheck.recent_results_passed"), scalar[bool]),
		LastFailureOutput:       plain[string](s.at("pethost.panel.v1.HealthCheck.last_failure_output")),
	}
}

func sampleEnvironmentVariable(s seed) EnvironmentVariable {
	return EnvironmentVariable{
		Name:                 plain[string](s.at("pethost.panel.v1.EnvironmentVariable.name")),
		Value:                plain[string](s.at("pethost.panel.v1.EnvironmentVariable.value")),
		Secret:               plain[bool](s.at("pethost.panel.v1.EnvironmentVariable.secret")),
		SourceFile:           plain[string](s.at("pethost.panel.v1.EnvironmentVariable.source_file")),
		FromEnvFileVariables: list(s.at("pethost.panel.v1.EnvironmentVariable.from_env_file_variables"), scalar[string]),
		ValueLeftOut:         plain[bool](s.at("pethost.panel.v1.EnvironmentVariable.value_left_out")),
	}
}

func sampleVolume(s seed) Volume {
	return Volume{
		Volume:         plain[string](s.at("pethost.panel.v1.Volume.volume")),
		SizeBytes:      plain[uint64](s.at("pethost.panel.v1.Volume.size_bytes")),
		MountedBy:      list(s.at("pethost.panel.v1.Volume.mounted_by"), sampleVolumeMountedBy),
		LastBackupTime: instant(s.at("pethost.panel.v1.Volume.last_backup_time")),
		SnapshotCount:  plain[uint32](s.at("pethost.panel.v1.Volume.snapshot_count")),
		Declared:       plain[bool](s.at("pethost.panel.v1.Volume.declared")),
	}
}

func sampleVolumeMountedBy(s seed) VolumeMountedBy {
	return VolumeMountedBy{
		Service:       plain[string](s.at("pethost.panel.v1.VolumeMountedBy.service")),
		ContainerPath: plain[string](s.at("pethost.panel.v1.VolumeMountedBy.container_path")),
	}
}

func sampleHost(s seed) Host {
	return Host{
		Host:                  plain[string](s.at("pethost.panel.v1.Host.host")),
		URL:                   plain[string](s.at("pethost.panel.v1.Host.url")),
		CertificateSource:     plain[CertificateSource](s.at("pethost.panel.v1.Host.certificate_source")),
		CertificateExpireTime: instant(s.at("pethost.panel.v1.Host.certificate_expire_time")),
		UnavailableMessage:    plain[string](s.at("pethost.panel.v1.Host.unavailable_message")),
	}
}

func sampleRoute(s seed) Route {
	return Route{
		Host:      plain[string](s.at("pethost.panel.v1.Route.host")),
		Path:      plain[string](s.at("pethost.panel.v1.Route.path")),
		Service:   plain[string](s.at("pethost.panel.v1.Route.service")),
		Port:      plain[uint32](s.at("pethost.panel.v1.Route.port")),
		StripPath: plain[bool](s.at("pethost.panel.v1.Route.strip_path")),
		unknown:   later(s),
	}
}

func sampleOperation(s seed) Operation {
	return Operation{
		OperationID:         plain[string](s.at("pethost.panel.v1.Operation.operation_id")),
		Kind:                plain[OperationKind](s.at("pethost.panel.v1.Operation.kind")),
		Status:              plain[OperationStatus](s.at("pethost.panel.v1.Operation.status")),
		StartTime:           instant(s.at("pethost.panel.v1.Operation.start_time")),
		FinishTime:          instant(s.at("pethost.panel.v1.Operation.finish_time")),
		FailureMessage:      plain[string](s.at("pethost.panel.v1.Operation.failure_message")),
		DeployFailureReason: plain[DeployFailureReason](s.at("pethost.panel.v1.Operation.deploy_failure_reason")),
		MadeCurrent:         plain[bool](s.at("pethost.panel.v1.Operation.made_current")),
		Service:             plain[string](s.at("pethost.panel.v1.Operation.service")),
		FailedExitCode:      plain[int32](s.at("pethost.panel.v1.Operation.failed_exit_code")),
		SnapshotID:          plain[string](s.at("pethost.panel.v1.Operation.snapshot_id")),
		RestoredVolumes:     list(s.at("pethost.panel.v1.Operation.restored_volumes"), scalar[string]),
		UndoSnapshotID:      plain[string](s.at("pethost.panel.v1.Operation.undo_snapshot_id")),
		GithubCommit:        pointer(s.at("pethost.panel.v1.Operation.github_commit"), sampleGithubCommit),
		ArchiveName:         plain[string](s.at("pethost.panel.v1.Operation.archive_name")),
		Adjustments:         list(s.at("pethost.panel.v1.Operation.adjustments"), scalar[string]),
		ChangedPaths:        list(s.at("pethost.panel.v1.Operation.changed_paths"), scalar[string]),
		ChangedPathCount:    plain[uint32](s.at("pethost.panel.v1.Operation.changed_path_count")),
		FilesKept:           plain[bool](s.at("pethost.panel.v1.Operation.files_kept")),
	}
}

func sampleSnapshot(s seed) Snapshot {
	return Snapshot{
		SnapshotID: plain[string](s.at("pethost.panel.v1.Snapshot.snapshot_id")),
		CreateTime: instant(s.at("pethost.panel.v1.Snapshot.create_time")),
		SizeBytes:  plain[uint64](s.at("pethost.panel.v1.Snapshot.size_bytes")),
		Volumes:    list(s.at("pethost.panel.v1.Snapshot.volumes"), scalar[string]),
	}
}

func sampleHTTPTrafficSummary(s seed) HTTPTrafficSummary {
	return HTTPTrafficSummary{
		RequestCount:     plain[uint64](s.at("pethost.panel.v1.HttpTrafficSummary.request_count")),
		ServerErrorCount: plain[uint64](s.at("pethost.panel.v1.HttpTrafficSummary.server_error_count")),
		LatencyP50Ms:     plain[uint32](s.at("pethost.panel.v1.HttpTrafficSummary.latency_p50_ms")),
		LatencyP95Ms:     plain[uint32](s.at("pethost.panel.v1.HttpTrafficSummary.latency_p95_ms")),
	}
}

func sampleCreateProjectRequest(s seed) CreateProjectRequest {
	return CreateProjectRequest{
		ProjectID:      plain[string](s.at("pethost.panel.v1.CreateProjectRequest.project_id")),
		Source:         pointer(s.at("pethost.panel.v1.CreateProjectRequest.source"), sampleProjectSource),
		UploadID:       plain[string](s.at("pethost.panel.v1.CreateProjectRequest.upload_id")),
		Files:          list(s.at("pethost.panel.v1.CreateProjectRequest.files"), sampleFileChange),
		XPethost:       pointer(s.at("pethost.panel.v1.CreateProjectRequest.x_pethost"), sampleProjectExtension),
		TimeoutSeconds: plain[uint32](s.at("pethost.panel.v1.CreateProjectRequest.timeout_seconds")),
		OperationID:    plain[string](s.at("pethost.panel.v1.CreateProjectRequest.operation_id")),
		WaitSeconds:    marked[uint32](s.at("pethost.panel.v1.CreateProjectRequest.wait_seconds")),
	}
}

func sampleCreateProjectResponse(s seed) CreateProjectResponse {
	return CreateProjectResponse{
		Operation:   pointer(s.at("pethost.panel.v1.CreateProjectResponse.operation"), sampleOperation),
		Violations:  list(s.at("pethost.panel.v1.CreateProjectResponse.violations"), sampleSpecViolation),
		Adjustments: list(s.at("pethost.panel.v1.CreateProjectResponse.adjustments"), scalar[string]),
		Project:     pointer(s.at("pethost.panel.v1.CreateProjectResponse.project"), sampleProject),
		Log:         list(s.at("pethost.panel.v1.CreateProjectResponse.log"), sampleOperationLogLine),
	}
}

func sampleDeployProjectRequest(s seed) DeployProjectRequest {
	return DeployProjectRequest{
		ProjectID:      plain[string](s.at("pethost.panel.v1.DeployProjectRequest.project_id")),
		BaseDeployID:   plain[string](s.at("pethost.panel.v1.DeployProjectRequest.base_deploy_id")),
		Files:          list(s.at("pethost.panel.v1.DeployProjectRequest.files"), sampleFileChange),
		XPethost:       pointer(s.at("pethost.panel.v1.DeployProjectRequest.x_pethost"), sampleProjectExtension),
		MountVolume:    pointer(s.at("pethost.panel.v1.DeployProjectRequest.mount_volume"), sampleMountVolume),
		TimeoutSeconds: plain[uint32](s.at("pethost.panel.v1.DeployProjectRequest.timeout_seconds")),
		OperationID:    plain[string](s.at("pethost.panel.v1.DeployProjectRequest.operation_id")),
		Version:        sampleDeployProjectVersion(s.at("pethost.panel.v1.DeployProjectRequest.version")),
		WaitSeconds:    marked[uint32](s.at("pethost.panel.v1.DeployProjectRequest.wait_seconds")),
	}
}

func sampleDeployProjectVersion(s seed) DeployProjectVersion {
	switch s.member(4) {
	case 0:
		return DeployProjectUploadID(plain[string](s))
	case 1:
		return DeployProjectCommit(plain[string](s))
	case 2:
		return DeployProjectNewestCommit(plain[bool](s))
	case 3:
		return DeployProjectRollbackDeployID(plain[string](s))
	}
	return nil
}

func sampleMountVolume(s seed) MountVolume {
	return MountVolume{
		Service:       plain[string](s.at("pethost.panel.v1.MountVolume.service")),
		Volume:        plain[string](s.at("pethost.panel.v1.MountVolume.volume")),
		ContainerPath: plain[string](s.at("pethost.panel.v1.MountVolume.container_path")),
	}
}

func sampleProjectExtension(s seed) ProjectExtension {
	return ProjectExtension{
		Metadata:       pointer(s.at("pethost.panel.v1.ProjectExtension.metadata"), sampleProjectMetadata),
		Routes:         list(s.at("pethost.panel.v1.ProjectExtension.routes"), sampleRoute),
		RemoveRoutes:   plain[bool](s.at("pethost.panel.v1.ProjectExtension.remove_routes")),
		Password:       plain[string](s.at("pethost.panel.v1.ProjectExtension.password")),
		RemovePassword: plain[bool](s.at("pethost.panel.v1.ProjectExtension.remove_password")),
	}
}

func sampleFileChange(s seed) FileChange {
	return FileChange{
		Path:       plain[string](s.at("pethost.panel.v1.FileChange.path")),
		Change:     sampleFileChangeChange(s.at("pethost.panel.v1.FileChange.change")),
		Executable: plain[bool](s.at("pethost.panel.v1.FileChange.executable")),
	}
}

func sampleFileChangeChange(s seed) FileChangeChange {
	switch s.member(6) {
	case 0:
		return FileChangeText(plain[string](s))
	case 1:
		return FileChangeData(plain[[]byte](s))
	case 2:
		return FileChangeMakeDirectory(plain[bool](s))
	case 3:
		return FileChangeDelete(plain[bool](s))
	case 4:
		return FileChangeDeleteTree(plain[bool](s))
	case 5:
		return FileChangeRenameTo(plain[string](s))
	}
	return nil
}

func sampleDeployProjectResponse(s seed) DeployProjectResponse {
	return DeployProjectResponse{
		Operation:   pointer(s.at("pethost.panel.v1.DeployProjectResponse.operation"), sampleOperation),
		Violations:  list(s.at("pethost.panel.v1.DeployProjectResponse.violations"), sampleSpecViolation),
		Adjustments: list(s.at("pethost.panel.v1.DeployProjectResponse.adjustments"), scalar[string]),
		Project:     pointer(s.at("pethost.panel.v1.DeployProjectResponse.project"), sampleProject),
		Log:         list(s.at("pethost.panel.v1.DeployProjectResponse.log"), sampleOperationLogLine),
	}
}

func sampleSpecViolation(s seed) SpecViolation {
	return SpecViolation{
		Service:          plain[string](s.at("pethost.panel.v1.SpecViolation.service")),
		Location:         plain[string](s.at("pethost.panel.v1.SpecViolation.location")),
		ViolationMessage: plain[string](s.at("pethost.panel.v1.SpecViolation.violation_message")),
	}
}

func sampleListCommitsRequest(s seed) ListCommitsRequest {
	return ListCommitsRequest{
		ProjectID:    plain[string](s.at("pethost.panel.v1.ListCommitsRequest.project_id")),
		BeforeCommit: plain[string](s.at("pethost.panel.v1.ListCommitsRequest.before_commit")),
	}
}

func sampleListCommitsResponse(s seed) ListCommitsResponse {
	return ListCommitsResponse{
		Commits: list(s.at("pethost.panel.v1.ListCommitsResponse.commits"), sampleBranchCommit),
		More:    plain[bool](s.at("pethost.panel.v1.ListCommitsResponse.more")),
	}
}

func sampleBranchCommit(s seed) BranchCommit {
	return BranchCommit{
		Commit:     pointer(s.at("pethost.panel.v1.BranchCommit.commit"), sampleGithubCommit),
		Author:     plain[string](s.at("pethost.panel.v1.BranchCommit.author")),
		CommitTime: instant(s.at("pethost.panel.v1.BranchCommit.commit_time")),
		Deployed:   plain[bool](s.at("pethost.panel.v1.BranchCommit.deployed")),
		LastDeploy: pointer(s.at("pethost.panel.v1.BranchCommit.last_deploy"), sampleOperation),
		Newest:     plain[bool](s.at("pethost.panel.v1.BranchCommit.newest")),
	}
}

func sampleRunProjectActionRequest(s seed) RunProjectActionRequest {
	return RunProjectActionRequest{
		ProjectID:   plain[string](s.at("pethost.panel.v1.RunProjectActionRequest.project_id")),
		Action:      sampleRunProjectActionAction(s.at("pethost.panel.v1.RunProjectActionRequest.action")),
		OperationID: plain[string](s.at("pethost.panel.v1.RunProjectActionRequest.operation_id")),
		WaitSeconds: marked[uint32](s.at("pethost.panel.v1.RunProjectActionRequest.wait_seconds")),
	}
}

func sampleRunProjectActionAction(s seed) RunProjectActionAction {
	switch s.member(10) {
	case 0:
		return RunProjectActionStartServices(member(s, sampleServicesAction))
	case 1:
		return RunProjectActionStopServices(member(s, sampleServicesAction))
	case 2:
		return RunProjectActionRestartServices(member(s, sampleServicesAction))
	case 3:
		return RunProjectActionRecreateService(member(s, sampleRecreateServiceAction))
	case 4:
		return RunProjectActionBackUp(member(s, sampleBackUpAction))
	case 5:
		return RunProjectActionRestoreSnapshot(member(s, sampleRestoreSnapshotAction))
	case 6:
		return RunProjectActionCancelOperation(member(s, sampleCancelOperationAction))
	case 7:
		return RunProjectActionDeleteProject(member(s, sampleDeleteProjectAction))
	case 8:
		return RunProjectActionSetSource(member(s, sampleProjectSource))
	case 9:
		return RunProjectActionDeleteVolume(plain[string](s))
	}
	return nil
}

func sampleServicesAction(s seed) ServicesAction {
	return ServicesAction{
		Services: list(s.at("pethost.panel.v1.ServicesAction.services"), scalar[string]),
	}
}

func sampleRecreateServiceAction(s seed) RecreateServiceAction {
	return RecreateServiceAction{
		Service:         plain[string](s.at("pethost.panel.v1.RecreateServiceAction.service")),
		PullLatestImage: plain[bool](s.at("pethost.panel.v1.RecreateServiceAction.pull_latest_image")),
	}
}

func sampleBackUpAction(s seed) BackUpAction {
	return BackUpAction{}
}

func sampleRestoreSnapshotAction(s seed) RestoreSnapshotAction {
	return RestoreSnapshotAction{
		SnapshotID: plain[string](s.at("pethost.panel.v1.RestoreSnapshotAction.snapshot_id")),
		Volumes:    list(s.at("pethost.panel.v1.RestoreSnapshotAction.volumes"), scalar[string]),
	}
}

func sampleCancelOperationAction(s seed) CancelOperationAction {
	return CancelOperationAction{
		OperationID: plain[string](s.at("pethost.panel.v1.CancelOperationAction.operation_id")),
	}
}

func sampleDeleteProjectAction(s seed) DeleteProjectAction {
	return DeleteProjectAction{
		SkipFinalBackup: plain[bool](s.at("pethost.panel.v1.DeleteProjectAction.skip_final_backup")),
	}
}

func sampleRunProjectActionResponse(s seed) RunProjectActionResponse {
	return RunProjectActionResponse{
		Operation: pointer(s.at("pethost.panel.v1.RunProjectActionResponse.operation"), sampleOperation),
		Project:   pointer(s.at("pethost.panel.v1.RunProjectActionResponse.project"), sampleProject),
		Log:       list(s.at("pethost.panel.v1.RunProjectActionResponse.log"), sampleOperationLogLine),
	}
}

func sampleGetOperationRequest(s seed) GetOperationRequest {
	return GetOperationRequest{
		ProjectID:    plain[string](s.at("pethost.panel.v1.GetOperationRequest.project_id")),
		OperationID:  plain[string](s.at("pethost.panel.v1.GetOperationRequest.operation_id")),
		WaitSeconds:  marked[uint32](s.at("pethost.panel.v1.GetOperationRequest.wait_seconds")),
		AfterLogLine: marked[uint32](s.at("pethost.panel.v1.GetOperationRequest.after_log_line")),
		LogLineLimit: marked[uint32](s.at("pethost.panel.v1.GetOperationRequest.log_line_limit")),
	}
}

func sampleGetOperationResponse(s seed) GetOperationResponse {
	return GetOperationResponse{
		Operation:        pointer(s.at("pethost.panel.v1.GetOperationResponse.operation"), sampleOperation),
		Project:          pointer(s.at("pethost.panel.v1.GetOperationResponse.project"), sampleProject),
		Log:              list(s.at("pethost.panel.v1.GetOperationResponse.log"), sampleOperationLogLine),
		LogLineCount:     plain[uint32](s.at("pethost.panel.v1.GetOperationResponse.log_line_count")),
		NextAfterLogLine: plain[uint32](s.at("pethost.panel.v1.GetOperationResponse.next_after_log_line")),
	}
}

func sampleOperationLogLine(s seed) OperationLogLine {
	return OperationLogLine{
		Time: instant(s.at("pethost.panel.v1.OperationLogLine.time")),
		Text: plain[string](s.at("pethost.panel.v1.OperationLogLine.text")),
	}
}

func sampleHTTPTrafficFilter(s seed) HTTPTrafficFilter {
	return HTTPTrafficFilter{
		Host:         plain[string](s.at("pethost.panel.v1.HttpTrafficFilter.host")),
		Method:       plain[string](s.at("pethost.panel.v1.HttpTrafficFilter.method")),
		PathContains: plain[string](s.at("pethost.panel.v1.HttpTrafficFilter.path_contains")),
		PathPattern:  plain[string](s.at("pethost.panel.v1.HttpTrafficFilter.path_pattern")),
		StatusClass:  plain[uint32](s.at("pethost.panel.v1.HttpTrafficFilter.status_class")),
	}
}

func sampleQueryHTTPTrafficRequest(s seed) QueryHTTPTrafficRequest {
	return QueryHTTPTrafficRequest{
		ProjectID:          plain[string](s.at("pethost.panel.v1.QueryHttpTrafficRequest.project_id")),
		Filter:             pointer(s.at("pethost.panel.v1.QueryHttpTrafficRequest.filter"), sampleHTTPTrafficFilter),
		StartTime:          instant(s.at("pethost.panel.v1.QueryHttpTrafficRequest.start_time")),
		EndTime:            instant(s.at("pethost.panel.v1.QueryHttpTrafficRequest.end_time")),
		LastSeconds:        plain[uint32](s.at("pethost.panel.v1.QueryHttpTrafficRequest.last_seconds")),
		BucketWidthSeconds: plain[uint32](s.at("pethost.panel.v1.QueryHttpTrafficRequest.bucket_width_seconds")),
		RequestLimit:       plain[uint32](s.at("pethost.panel.v1.QueryHttpTrafficRequest.request_limit")),
		PageToken:          plain[string](s.at("pethost.panel.v1.QueryHttpTrafficRequest.page_token")),
	}
}

func sampleQueryHTTPTrafficResponse(s seed) QueryHTTPTrafficResponse {
	return QueryHTTPTrafficResponse{
		StartTime:      instant(s.at("pethost.panel.v1.QueryHttpTrafficResponse.start_time")),
		EndTime:        instant(s.at("pethost.panel.v1.QueryHttpTrafficResponse.end_time")),
		OldestKeptTime: instant(s.at("pethost.panel.v1.QueryHttpTrafficResponse.oldest_kept_time")),
		Summary:        pointer(s.at("pethost.panel.v1.QueryHttpTrafficResponse.summary"), sampleHTTPTrafficSummary),
		Buckets:        list(s.at("pethost.panel.v1.QueryHttpTrafficResponse.buckets"), sampleHTTPTrafficBucket),
		TopPaths:       list(s.at("pethost.panel.v1.QueryHttpTrafficResponse.top_paths"), sampleHTTPPathTraffic),
		NewestSequence: plain[uint64](s.at("pethost.panel.v1.QueryHttpTrafficResponse.newest_sequence")),
		Requests:       list(s.at("pethost.panel.v1.QueryHttpTrafficResponse.requests"), sampleHTTPRequest),
		NextPageToken:  plain[string](s.at("pethost.panel.v1.QueryHttpTrafficResponse.next_page_token")),
		TailSequence:   plain[uint64](s.at("pethost.panel.v1.QueryHttpTrafficResponse.tail_sequence")),
	}
}

func sampleHTTPTrafficBucket(s seed) HTTPTrafficBucket {
	return HTTPTrafficBucket{
		StartTime: instant(s.at("pethost.panel.v1.HttpTrafficBucket.start_time")),
		Summary:   pointer(s.at("pethost.panel.v1.HttpTrafficBucket.summary"), sampleHTTPTrafficSummary),
	}
}

func sampleHTTPPathTraffic(s seed) HTTPPathTraffic {
	return HTTPPathTraffic{
		Method:      plain[string](s.at("pethost.panel.v1.HttpPathTraffic.method")),
		PathPattern: plain[string](s.at("pethost.panel.v1.HttpPathTraffic.path_pattern")),
		Summary:     pointer(s.at("pethost.panel.v1.HttpPathTraffic.summary"), sampleHTTPTrafficSummary),
	}
}

func sampleHTTPRequest(s seed) HTTPRequest {
	return HTTPRequest{
		Sequence:          plain[uint64](s.at("pethost.panel.v1.HttpRequest.sequence")),
		FinishTime:        instant(s.at("pethost.panel.v1.HttpRequest.finish_time")),
		Host:              plain[string](s.at("pethost.panel.v1.HttpRequest.host")),
		Method:            plain[string](s.at("pethost.panel.v1.HttpRequest.method")),
		Path:              plain[string](s.at("pethost.panel.v1.HttpRequest.path")),
		PathPattern:       plain[string](s.at("pethost.panel.v1.HttpRequest.path_pattern")),
		RoutePath:         plain[string](s.at("pethost.panel.v1.HttpRequest.route_path")),
		Service:           plain[string](s.at("pethost.panel.v1.HttpRequest.service")),
		Port:              plain[uint32](s.at("pethost.panel.v1.HttpRequest.port")),
		StatusCode:        plain[uint32](s.at("pethost.panel.v1.HttpRequest.status_code")),
		ResponseSizeBytes: plain[uint64](s.at("pethost.panel.v1.HttpRequest.response_size_bytes")),
		DurationMs:        plain[uint32](s.at("pethost.panel.v1.HttpRequest.duration_ms")),
		ServiceDurationMs: plain[uint32](s.at("pethost.panel.v1.HttpRequest.service_duration_ms")),
		ClientIPAddress:   plain[string](s.at("pethost.panel.v1.HttpRequest.client_ip_address")),
		UserAgent:         plain[string](s.at("pethost.panel.v1.HttpRequest.user_agent")),
	}
}

func sampleContainerLogFilter(s seed) ContainerLogFilter {
	return ContainerLogFilter{
		Service:      plain[string](s.at("pethost.panel.v1.ContainerLogFilter.service")),
		Stream:       plain[OutputStream](s.at("pethost.panel.v1.ContainerLogFilter.stream")),
		TextContains: plain[string](s.at("pethost.panel.v1.ContainerLogFilter.text_contains")),
	}
}

func sampleQueryContainerLogsRequest(s seed) QueryContainerLogsRequest {
	return QueryContainerLogsRequest{
		ProjectID:   plain[string](s.at("pethost.panel.v1.QueryContainerLogsRequest.project_id")),
		Filter:      pointer(s.at("pethost.panel.v1.QueryContainerLogsRequest.filter"), sampleContainerLogFilter),
		StartTime:   instant(s.at("pethost.panel.v1.QueryContainerLogsRequest.start_time")),
		EndTime:     instant(s.at("pethost.panel.v1.QueryContainerLogsRequest.end_time")),
		LastSeconds: plain[uint32](s.at("pethost.panel.v1.QueryContainerLogsRequest.last_seconds")),
		Limit:       plain[uint32](s.at("pethost.panel.v1.QueryContainerLogsRequest.limit")),
		FromStart:   plain[bool](s.at("pethost.panel.v1.QueryContainerLogsRequest.from_start")),
		PageToken:   plain[string](s.at("pethost.panel.v1.QueryContainerLogsRequest.page_token")),
	}
}

func sampleQueryContainerLogsResponse(s seed) QueryContainerLogsResponse {
	return QueryContainerLogsResponse{
		StartTime:      instant(s.at("pethost.panel.v1.QueryContainerLogsResponse.start_time")),
		EndTime:        instant(s.at("pethost.panel.v1.QueryContainerLogsResponse.end_time")),
		OldestKeptTime: instant(s.at("pethost.panel.v1.QueryContainerLogsResponse.oldest_kept_time")),
		Lines:          list(s.at("pethost.panel.v1.QueryContainerLogsResponse.lines"), sampleLogLine),
		NextPageToken:  plain[string](s.at("pethost.panel.v1.QueryContainerLogsResponse.next_page_token")),
		TailCursor:     plain[string](s.at("pethost.panel.v1.QueryContainerLogsResponse.tail_cursor")),
	}
}

func sampleLogLine(s seed) LogLine {
	return LogLine{
		Time:    instant(s.at("pethost.panel.v1.LogLine.time")),
		Service: plain[string](s.at("pethost.panel.v1.LogLine.service")),
		Stream:  plain[OutputStream](s.at("pethost.panel.v1.LogLine.stream")),
		Text:    plain[string](s.at("pethost.panel.v1.LogLine.text")),
	}
}

func sampleRunServiceCommandRequest(s seed) RunServiceCommandRequest {
	return RunServiceCommandRequest{
		ProjectID:        plain[string](s.at("pethost.panel.v1.RunServiceCommandRequest.project_id")),
		Service:          plain[string](s.at("pethost.panel.v1.RunServiceCommandRequest.service")),
		Command:          list(s.at("pethost.panel.v1.RunServiceCommandRequest.command"), scalar[string]),
		Stdin:            plain[string](s.at("pethost.panel.v1.RunServiceCommandRequest.stdin")),
		RunAsUser:        plain[string](s.at("pethost.panel.v1.RunServiceCommandRequest.run_as_user")),
		WorkingDirectory: plain[string](s.at("pethost.panel.v1.RunServiceCommandRequest.working_directory")),
		TimeoutSeconds:   plain[uint32](s.at("pethost.panel.v1.RunServiceCommandRequest.timeout_seconds")),
	}
}

func sampleRunServiceCommandResponse(s seed) RunServiceCommandResponse {
	return RunServiceCommandResponse{
		ExitCode:        plain[int32](s.at("pethost.panel.v1.RunServiceCommandResponse.exit_code")),
		TimedOut:        plain[bool](s.at("pethost.panel.v1.RunServiceCommandResponse.timed_out")),
		Stdout:          plain[string](s.at("pethost.panel.v1.RunServiceCommandResponse.stdout")),
		Stderr:          plain[string](s.at("pethost.panel.v1.RunServiceCommandResponse.stderr")),
		OutputTruncated: plain[bool](s.at("pethost.panel.v1.RunServiceCommandResponse.output_truncated")),
	}
}

func sampleFileEntry(s seed) FileEntry {
	return FileEntry{
		Name:          plain[string](s.at("pethost.panel.v1.FileEntry.name")),
		Type:          plain[FileType](s.at("pethost.panel.v1.FileEntry.type")),
		SizeBytes:     plain[uint64](s.at("pethost.panel.v1.FileEntry.size_bytes")),
		ModifyTime:    instant(s.at("pethost.panel.v1.FileEntry.modify_time")),
		Mode:          plain[string](s.at("pethost.panel.v1.FileEntry.mode")),
		OwnerUID:      plain[uint32](s.at("pethost.panel.v1.FileEntry.owner_uid")),
		OwnerGID:      plain[uint32](s.at("pethost.panel.v1.FileEntry.owner_gid")),
		SymlinkTarget: plain[string](s.at("pethost.panel.v1.FileEntry.symlink_target")),
	}
}

func sampleReadPathRequest(s seed) ReadPathRequest {
	return ReadPathRequest{
		ProjectID:      plain[string](s.at("pethost.panel.v1.ReadPathRequest.project_id")),
		Root:           sampleReadPathRoot(s.at("pethost.panel.v1.ReadPathRequest.root")),
		Path:           plain[string](s.at("pethost.panel.v1.ReadPathRequest.path")),
		EntryLimit:     plain[uint32](s.at("pethost.panel.v1.ReadPathRequest.entry_limit")),
		OffsetBytes:    plain[uint64](s.at("pethost.panel.v1.ReadPathRequest.offset_bytes")),
		LengthBytes:    plain[uint32](s.at("pethost.panel.v1.ReadPathRequest.length_bytes")),
		EntryPageToken: plain[string](s.at("pethost.panel.v1.ReadPathRequest.entry_page_token")),
	}
}

func sampleReadPathRoot(s seed) ReadPathRoot {
	switch s.member(2) {
	case 0:
		return ReadPathService(plain[string](s))
	case 1:
		return ReadPathVolume(plain[string](s))
	}
	return nil
}

func sampleReadPathResponse(s seed) ReadPathResponse {
	return ReadPathResponse{
		Entry:              pointer(s.at("pethost.panel.v1.ReadPathResponse.entry"), sampleFileEntry),
		Location:           plain[FileLocation](s.at("pethost.panel.v1.ReadPathResponse.location")),
		Volume:             plain[string](s.at("pethost.panel.v1.ReadPathResponse.volume")),
		Entries:            list(s.at("pethost.panel.v1.ReadPathResponse.entries"), sampleFileEntry),
		EntryCount:         plain[uint32](s.at("pethost.panel.v1.ReadPathResponse.entry_count")),
		NextEntryPageToken: plain[string](s.at("pethost.panel.v1.ReadPathResponse.next_entry_page_token")),
		Text:               plain[string](s.at("pethost.panel.v1.ReadPathResponse.text")),
		Binary:             plain[bool](s.at("pethost.panel.v1.ReadPathResponse.binary")),
		NextOffsetBytes:    plain[uint64](s.at("pethost.panel.v1.ReadPathResponse.next_offset_bytes")),
		DeployID:           plain[string](s.at("pethost.panel.v1.ReadPathResponse.deploy_id")),
	}
}

func sampleCreateTransferRequest(s seed) CreateTransferRequest {
	return CreateTransferRequest{
		Transfer: sampleCreateTransferTransfer(s.at("pethost.panel.v1.CreateTransferRequest.transfer")),
	}
}

func sampleCreateTransferTransfer(s seed) CreateTransferTransfer {
	switch s.member(3) {
	case 0:
		return CreateTransferUploadArchive(member(s, sampleArchiveUpload))
	case 1:
		return CreateTransferUploadFile(member(s, sampleFileUpload))
	case 2:
		return CreateTransferDownload(member(s, samplePathDownload))
	}
	return nil
}

func sampleArchiveUpload(s seed) ArchiveUpload {
	return ArchiveUpload{
		FileName: plain[string](s.at("pethost.panel.v1.ArchiveUpload.file_name")),
	}
}

func sampleFileUpload(s seed) FileUpload {
	return FileUpload{
		ProjectID: plain[string](s.at("pethost.panel.v1.FileUpload.project_id")),
		Root:      sampleFileUploadRoot(s.at("pethost.panel.v1.FileUpload.root")),
		Path:      plain[string](s.at("pethost.panel.v1.FileUpload.path")),
	}
}

func sampleFileUploadRoot(s seed) FileUploadRoot {
	switch s.member(2) {
	case 0:
		return FileUploadService(plain[string](s))
	case 1:
		return FileUploadVolume(plain[string](s))
	}
	return nil
}

func samplePathDownload(s seed) PathDownload {
	return PathDownload{
		ProjectID: plain[string](s.at("pethost.panel.v1.PathDownload.project_id")),
		Root:      samplePathDownloadRoot(s.at("pethost.panel.v1.PathDownload.root")),
		Path:      plain[string](s.at("pethost.panel.v1.PathDownload.path")),
	}
}

func samplePathDownloadRoot(s seed) PathDownloadRoot {
	switch s.member(2) {
	case 0:
		return PathDownloadService(plain[string](s))
	case 1:
		return PathDownloadVolume(plain[string](s))
	}
	return nil
}

func sampleCreateTransferResponse(s seed) CreateTransferResponse {
	return CreateTransferResponse{
		URL:        plain[string](s.at("pethost.panel.v1.CreateTransferResponse.url")),
		HTTPMethod: plain[string](s.at("pethost.panel.v1.CreateTransferResponse.http_method")),
		ExpireTime: instant(s.at("pethost.panel.v1.CreateTransferResponse.expire_time")),
		Command:    plain[string](s.at("pethost.panel.v1.CreateTransferResponse.command")),
		UploadID:   plain[string](s.at("pethost.panel.v1.CreateTransferResponse.upload_id")),
		Replaces:   plain[bool](s.at("pethost.panel.v1.CreateTransferResponse.replaces")),
		FileName:   plain[string](s.at("pethost.panel.v1.CreateTransferResponse.file_name")),
	}
}

func sampleProjectBusy(s seed) ProjectBusy {
	return ProjectBusy{
		OperationID: plain[string](s.at("pethost.panel.v1.ProjectBusy.operation_id")),
		Kind:        plain[OperationKind](s.at("pethost.panel.v1.ProjectBusy.kind")),
		StartTime:   instant(s.at("pethost.panel.v1.ProjectBusy.start_time")),
	}
}

func sampleProjectChanged(s seed) ProjectChanged {
	return ProjectChanged{}
}

func sampleMachineUnreachable(s seed) MachineUnreachable {
	return MachineUnreachable{}
}

func sampleNoMachine(s seed) NoMachine {
	return NoMachine{
		Reason: plain[NoMachineReason](s.at("pethost.panel.v1.NoMachine.reason")),
		URL:    plain[string](s.at("pethost.panel.v1.NoMachine.url")),
	}
}
