// Code generated by protoc-gen-panel-go from v1/panel.proto. DO NOT EDIT.

package pethost

import (
	"crypto/sha256"
	"encoding/binary"
	"reflect"
	"strconv"
	"time"

	"google.golang.org/protobuf/encoding/protowire"
)

// The samples the package's checks send through it. A seed decides one sample whole: which
// fields are set and to what, how long a list is, which member a oneof has. Each field takes
// its own seed from its message's by its proto name, so two sides agree on a sample without
// knowing of each other: a public struct's (samples_test.go, which the generator writes from
// the proto) and a wire message's, filled here from the wire layer's own descriptor. What the
// package makes of one must be the other.

type seed uint64

// at is the seed of what name names within s: a field, a oneof, an element of a list.
func (s seed) at(name string) seed {
	sum := sha256.Sum256(append(binary.LittleEndian.AppendUint64(nil, uint64(s)), name...))
	return seed(binary.LittleEndian.Uint64(sum[:]))
}

// A state is what a sample makes of one field.
type state int

const (
	set    state = iota // A value that is not zero; a list of two.
	zero                // Its zero, set: 0, "", an empty message; a list of one.
	absent              // Left out.
)

func (st state) String() string {
	return [...]string{"set", "zero", "absent"}[st]
}

// state is the field's in this sample: set in half of them, so that what a message holds
// deep inside is reached often.
func (s seed) state() state {
	return [...]state{set, set, zero, absent}[s%4]
}

// member is which of a oneof's n members this sample sets; n = none.
func (s seed) member(n int) int {
	return int(s / 4 % seed(n+1))
}

// The values a set field takes. A number is small: an enum has names for the lowest of them
// and none for the rest, which is the value of a later API.
func (s seed) text() string  { return "t" + strconv.FormatUint(uint64(s>>8), 36) }
func (s seed) number() int32 { return int32(s>>8%50) + 1 }
func (s seed) wide() uint64  { return uint64(s>>8) | 1<<40 }

func (s seed) moment() time.Time {
	return time.Unix(int64(s>>8%4_000_000_000), int64(s>>40%1_000_000_000)).UTC()
}

// scalar is a set value of a scalar or an enum, by the Go type the package gives it.
func scalar[T any](s seed) T {
	var v T
	switch r := reflect.ValueOf(&v).Elem(); r.Kind() {
	case reflect.String:
		r.SetString(s.text())
	case reflect.Slice:
		r.SetBytes([]byte(s.text()))
	case reflect.Bool:
		r.SetBool(true)
	case reflect.Int32:
		r.SetInt(int64(s.number()))
	case reflect.Uint32:
		r.SetUint(uint64(uint32(s.wide()) | 1))
	case reflect.Int64:
		r.SetInt(int64(s.wide()))
	case reflect.Uint64:
		r.SetUint(s.wide())
	case reflect.Float32, reflect.Float64:
		r.SetFloat(float64(s.number()) + 0.5)
	default:
		panic("no sample of a " + r.Type().String())
	}
	return v
}

// ── A public struct's fields, as samples_test.go writes them ───────────────

// plain is a scalar or an enum without a mark, and a scalar member of a oneof: its zero
// unless the sample sets it.
func plain[T any](s seed) T {
	if s.state() != set {
		var none T
		return none
	}
	return scalar[T](s)
}

// marked is a scalar marked (optional): a pointer to its zero when the sample sets zero.
func marked[T any](s seed) *T {
	switch s.state() {
	case set:
		return new(scalar[T](s))
	case zero:
		return new(T)
	}
	return nil
}

// pointer is a message-typed field: a pointer to the empty message when the sample sets zero.
func pointer[T any](s seed, sample func(seed) T) *T {
	switch s.state() {
	case set:
		return new(sample(s))
	case zero:
		return new(T)
	}
	return nil
}

// member is a message-typed member of a oneof, which is set: with what it holds, or empty.
func member[T any](s seed, sample func(seed) T) T {
	if s.state() != set {
		var empty T
		return empty
	}
	return sample(s)
}

// instant is a Timestamp field: the zero time is all a sample has for "not set".
func instant(s seed) time.Time {
	if s.state() != set {
		return time.Time{}
	}
	return s.moment()
}

// list is a repeated field: two elements, one or none.
func list[T any](s seed, sample func(seed) T) []T {
	var values []T
	for i := range elements(s) {
		values = append(values, sample(s.at(strconv.Itoa(i))))
	}
	return values
}

func elements(s seed) int {
	return [...]int{set: 2, zero: 1, absent: 0}[s.state()]
}

// laterField is a field number that no message of the API has: a later API's field.
const laterField = 18999

// later is what a message holds of a later API in this sample: a field the wire layer has no
// name for, in half of them.
func later(s seed) string {
	s = s.at("later")
	if s.state() != set {
		return ""
	}
	return string(protowire.AppendString(protowire.AppendTag(nil, laterField, protowire.BytesType), s.text()))
}
