// Code generated by protoc-gen-panel-go from v1/panel.proto. DO NOT EDIT.

package pethost

import (
	"context"
	"errors"
	"fmt"
	"iter"
	"net/http/httptest"
	"reflect"
	"testing"
	"time"

	"connectrpc.com/connect/v2"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// The checks of the streams: how a stream's method yields what the fake of the API
// (checks_test.go) sends and passes over its pulses, how it fails and ends, and that leaving
// its loop ends the call. A stream's messages go through TestCalls too, as every method's do.

// answerStream is the fake's handler of every stream.
func answerStream[R proto.Message](ctx context.Context, x *exchange, request proto.Message, send func(R) error) error {
	x.received = request

	responses := x.responses
	if len(responses) == 0 && x.response != nil {
		responses = []proto.Message{x.response}
	}
	for _, response := range responses {
		if err := send(response.(R)); err != nil {
			return err
		}
	}

	// The check that waits is the one that made left: a later one has another, or none.
	if left := x.left; left != nil {
		<-ctx.Done()
		close(left)
		return ctx.Err()
	}
	return x.err
}

// streamOf is a stream's method as a call: to the checks of every method it is the call that
// returns the stream's first response, or the error that ended it. A sample with nothing set is
// a pulse to the stream, which yields no response for it: those checks get the response with
// nothing set, which is what the API sent.
func streamOf[Q, R any](name string, method func(*Client, context.Context, *Q) iter.Seq2[*R, error], request func(seed) Q, response func(seed) R, wireRequest, wireResponse proto.Message) call {
	first := func(client *Client, ctx context.Context, q *Q) (*R, error) {
		var got *R
		for r, err := range method(client, ctx, q) {
			if err != nil {
				return nil, err
			}
			if got == nil {
				got = r
			}
		}
		if got == nil {
			got = new(R)
		}
		return got, nil
	}

	c := callOf(name, first, request, response, wireRequest, wireResponse)
	c.stream = func(ctx context.Context, client *Client) iter.Seq2[any, error] {
		return func(yield func(any, error) bool) {
			for r, err := range method(client, ctx, nil) {
				if r == nil {
					if !yield(nil, err) {
						return
					}
					continue
				}
				if !yield(*r, err) {
					return
				}
			}
		}
	}
	return c
}

// TestStreams: a stream's method yields each response as the API sends it, in their order, and
// none for a pulse, wherever it stands among them; an error, the call's own or one that ends
// the stream, comes once, last, beside no response; a stream that ends by itself ends the loop;
// and leaving the loop ends the call, as does its context's end. All of it holds over HTTP/1.1
// and over HTTP/2.
func TestStreams(t *testing.T) {
	for _, over := range []struct {
		name      string
		serve     func(*testing.T) (*fake, *httptest.Server)
		httpMajor int
	}{
		{"without TLS", serve, 1},
		{"over TLS", serveTLS, 2},
	} {
		t.Run(over.name, func(t *testing.T) {
			api, server := over.serve(t)
			streams(t, api, clientOf(server, account))
			if api.httpMajor != over.httpMajor {
				t.Errorf("the calls came over HTTP/%d, want HTTP/%d", api.httpMajor, over.httpMajor)
			}
		})
	}
}

// streams checks each stream against one fake, which sends three responses with pulses before,
// between and after them.
func streams(t *testing.T, api *fake, client *Client) {
	bothWays := bothWaysOf()

	for _, call := range calls {
		if call.stream == nil {
			continue
		}
		t.Run(call.name, func(t *testing.T) {
			samples, said := saying(call, bothWays)
			pulse := call.response
			api.responses = []proto.Message{pulse, said[0], pulse, pulse, said[1], said[2], pulse}
			t.Cleanup(func() { api.responses, api.err, api.left = nil, nil, nil })

			streamNotMade(t, client, call)
			streamFails(t, api, client, call, samples)
			streamEnds(t, api, client, call, len(samples))
			streamLeft(t, api, client, call, len(samples))
			streamBounded(t, api, client, call, len(samples))
			streamPulses(t, api, client, call)
		})
	}
}

// saying are the first three samples of a stream's response that say something, and the
// responses the API sends for them: a sample with nothing set is no bytes on the wire, which is
// a pulse.
func saying(call call, bothWays map[protoreflect.FullName]bool) ([]seed, []proto.Message) {
	received := &wireSample{bothWays: bothWays, had: map[string]bool{}}

	var samples []seed
	var said []proto.Message
	for n := seed(1); len(samples) < 3; n++ {
		sample := n.at(call.name)
		response := received.message(call.response, sample)
		if proto.Size(response) == 0 {
			continue
		}
		samples = append(samples, sample)
		said = append(said, response)
	}
	return samples, said
}

// streamNotMade: a call that fails before any response, here for a context cancelled before
// it, yields its error alone.
func streamNotMade(t *testing.T, client *Client, call call) {
	cancelled, cancel := context.WithCancel(t.Context())
	cancel()

	n := 0
	for got, err := range call.stream(cancelled, client) {
		if e, ok := err.(*Error); got != nil || !ok || e.Code != CodeCanceled || !errors.Is(err, context.Canceled) {
			t.Fatalf("a stream of a cancelled context yielded %v and %#v", got, err)
		}
		n++
	}
	if n != 1 {
		t.Fatalf("a stream of a cancelled context yielded %d pairs, want its error alone", n)
	}
}

// streamFails: a stream the API ends with an error yields each response before it, then the
// error.
func streamFails(t *testing.T, api *fake, client *Client, call call, samples []seed) {
	api.err = connect.NewError(connect.CodeOutOfRange, "why")

	n := 0
	for got, err := range call.stream(t.Context(), client) {
		switch {
		case n < len(samples) && err == nil:
			if where := differ(reflect.ValueOf(got), reflect.ValueOf(call.want(samples[n])), fmt.Sprintf("response %d", n)); where != "" {
				t.Fatal(where)
			}
		case n == len(samples) && got == nil:
			if e, ok := err.(*Error); !ok || e.Code != CodeOutOfRange || e.Message != "why" {
				t.Fatalf("the stream ended with %#v, want the API's OUT_OF_RANGE", err)
			}
		default:
			t.Fatalf("pair %d of the stream is %v and %v", n, got, err)
		}
		n++
	}
	if n != len(samples)+1 {
		t.Fatalf("the stream yielded %d pairs, want %d responses and the error", n, len(samples))
	}
}

// streamEnds: a stream the API ends without an error ends the loop after its responses. Its
// call is the Connect protocol's: binary protobuf, each message in an envelope.
func streamEnds(t *testing.T, api *fake, client *Client, call call, responses int) {
	api.err = nil

	n := 0
	for _, err := range call.stream(t.Context(), client) {
		if err != nil {
			t.Fatalf("a stream that ended by itself: %v", err)
		}
		n++
	}
	if n != responses {
		t.Fatalf("a stream that ended by itself yielded %d responses, want %d", n, responses)
	}
	if got, want := api.header.Get("Content-Type"), "application/connect+proto"; got != want {
		t.Fatalf("the stream's call was of the content type %q, want %q", got, want)
	}
}

// streamLeft: while the API waits, the last response it sent has come, not held back for a
// next one, and leaving the loop there ends the call: the API sees its caller gone. Over HTTP/2
// that is the stream's reset, on a connection that stays open: the next call goes by it. Over
// HTTP/1.1 only the connection's end stops an answer.
func streamLeft(t *testing.T, api *fake, client *Client, call call, responses int) {
	api.left = make(chan struct{})
	opened := api.connections.Load()

	n := 0
	for _, err := range call.stream(t.Context(), client) {
		if err != nil {
			t.Fatal(err)
		}
		n++
		if n == responses {
			break
		}
	}

	select {
	case <-api.left:
	case <-time.After(10 * time.Second):
		t.Fatal("the API still streams to a caller that left the loop")
	}

	api.left = nil
	streamEnds(t, api, client, call, responses)
	if now := api.connections.Load(); api.httpMajor == 2 && now != opened {
		t.Fatalf("leaving the loop cost the connection: %d had been opened before it, and %d after the next call", opened, now)
	}
}

// streamBounded: a context that ends while the API waits ends the loop with its error and the
// call: one the program cancels after the last response, and one whose deadline passes, which
// the API is told of too.
func streamBounded(t *testing.T, api *fake, client *Client, call call, responses int) {
	cancelled, cancel := context.WithCancel(t.Context())
	defer cancel()
	cut(t, api, call.stream(cancelled, client), CodeCanceled, func(pairs int) {
		if pairs == responses {
			cancel()
		}
	})

	late, release := context.WithTimeout(t.Context(), 200*time.Millisecond)
	defer release()
	cut(t, api, call.stream(late, client), CodeDeadlineExceeded, func(int) {})
	if api.header.Get("Connect-Timeout-Ms") == "" {
		t.Fatal("a stream whose context has a deadline was called without it")
	}
}

// streamPulses: a stream of pulses alone yields nothing: the loop ends when the API ends the
// stream, and with the API's error alone when it ends it so.
func streamPulses(t *testing.T, api *fake, client *Client, call call) {
	api.responses = []proto.Message{call.response, call.response, call.response}
	api.err, api.left = nil, nil

	for got, err := range call.stream(t.Context(), client) {
		t.Fatalf("a stream of pulses alone yielded %v and %v", got, err)
	}

	api.err = connect.NewError(connect.CodeOutOfRange, "why")
	n := 0
	for got, err := range call.stream(t.Context(), client) {
		if e, ok := err.(*Error); got != nil || !ok || e.Code != CodeOutOfRange || e.Message != "why" {
			t.Fatalf("a stream of pulses that failed yielded %v and %#v, want the API's OUT_OF_RANGE alone", got, err)
		}
		n++
	}
	if n != 1 {
		t.Fatalf("a stream of pulses that failed yielded %d pairs, want its error alone", n)
	}
}

// cut ranges over a stream whose API waits, telling each how many pairs have come: the loop
// must end with an error of the code want, and the API see its caller gone.
func cut(t *testing.T, api *fake, stream iter.Seq2[any, error], want Code, each func(pairs int)) {
	api.left = make(chan struct{})

	pairs := 0
	var last error
	for _, err := range stream {
		pairs++
		last = err
		each(pairs)
	}
	if e, ok := last.(*Error); !ok || e.Code != want {
		t.Fatalf("a stream whose context ended, ended after %d pairs with %#v: want %s", pairs, last, want)
	}

	select {
	case <-api.left:
	case <-time.After(10 * time.Second):
		t.Fatal("the API still streams to a caller whose context ended")
	}
}
