// Code generated by protoc-gen-panel-go from v1/panel.proto. DO NOT EDIT.

package pethost

import (
	"fmt"
	"strconv"

	"google.golang.org/protobuf/encoding/protowire"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
	_ "google.golang.org/protobuf/types/descriptorpb" // A descriptor has its options only with this.
	"google.golang.org/protobuf/types/known/timestamppb"
)

// The samples as the wire layer has them: a wire message filled from its own descriptor, by the
// seed that fills the public struct (seed_test.go), and by the API's rules of what is sent.
// This is the checks' own statement of those rules, apart from the generator's.

// wireSample fills wire messages, and keeps what its samples had.
type wireSample struct {
	// The message is a request, as the package must have sent the public sample: an unmarked
	// scalar's zero is left out, and so are a later API's fields unless the message is one a
	// response gave back whole.
	sent bool

	bothWays map[protoreflect.FullName]bool // The messages requests and responses share.
	had      map[string]bool                // What the samples so far had of each field: see needs.
}

// message is the sample of a wire message of of's type.
func (w *wireSample) message(of proto.Message, s seed) proto.Message {
	m := of.ProtoReflect().New()
	w.fill(m, s)
	return m.Interface()
}

func (w *wireSample) fill(m protoreflect.Message, s seed) {
	md := m.Descriptor()
	if md.Fields().ByNumber(laterField) != nil {
		panic(fmt.Sprintf("%s has field %d: the checks need another number for a later API's field", md.FullName(), laterField))
	}

	for i := range md.Fields().Len() {
		if fd := md.Fields().Get(i); fd.ContainingOneof() == nil {
			w.field(m, fd, s.at(string(fd.FullName())))
		}
	}
	chosen := false
	for i := range md.Oneofs().Len() {
		od := md.Oneofs().Get(i)
		chosen = w.oneof(m, od, s.at(string(od.FullName()))) || chosen
	}

	// What the package does not know of a message may be a member of its oneof: it is sent
	// back only while no member is set, and only in a message a response can have given.
	unknown := later(s)
	if w.sent && (!w.bothWays[md.FullName()] || chosen) {
		unknown = ""
	}
	if unknown != "" {
		m.SetUnknown(protoreflect.RawFields(unknown))
		w.had[key(md.FullName(), "later")] = true
	}
}

func (w *wireSample) field(m protoreflect.Message, fd protoreflect.FieldDescriptor, s seed) {
	st := s.state()

	switch {
	case fd.IsList():
		values := m.Mutable(fd).List()
		for i := range elements(s) {
			values.Append(w.element(values, fd, s.at(strconv.Itoa(i))))
		}

	case fd.Message() != nil:
		st = w.inner(m, fd, s)

	case st == set:
		m.Set(fd, wireScalar(fd, s, w.unnamed))

	// The API may send a zero it need not; the package sends only a marked one.
	case st == zero && (!w.sent || isMarked(fd)):
		m.Set(fd, fd.Default())
	}
	w.had[key(fd.FullName(), st)] = true
}

// inner sets a message-typed field, and reports the state it took: a time has no zero of its
// own to be set to.
func (w *wireSample) inner(m protoreflect.Message, fd protoreflect.FieldDescriptor, s seed) state {
	st := s.state()

	switch {
	case isMoment(fd) && st == set:
		m.Set(fd, wireMoment(s))
	case isMoment(fd):
		return absent
	case st == set:
		w.fill(m.Mutable(fd).Message(), s)
	case st == zero:
		m.Mutable(fd)
	}
	return st
}

func (w *wireSample) element(values protoreflect.List, fd protoreflect.FieldDescriptor, s seed) protoreflect.Value {
	switch {
	case isMoment(fd):
		return wireMoment(s)
	case fd.Message() != nil:
		element := values.NewElement()
		w.fill(element.Message(), s)
		return element
	}
	return wireScalar(fd, s, w.unnamed)
}

// oneof sets the member the sample picks, with its value or its zero, and reports whether it
// set one.
func (w *wireSample) oneof(m protoreflect.Message, od protoreflect.OneofDescriptor, s seed) bool {
	i := s.member(od.Fields().Len())
	if i == od.Fields().Len() {
		w.had[key(od.FullName(), absent)] = true
		return false
	}

	fd := od.Fields().Get(i)
	st := min(s.state(), zero) // A member that is set is never absent.
	switch {
	case fd.Message() != nil && st == set:
		w.fill(m.Mutable(fd).Message(), s)
	case fd.Message() != nil:
		m.Mutable(fd)
	case st == set:
		m.Set(fd, wireScalar(fd, s, w.unnamed))
	default:
		m.Set(fd, fd.Default())
	}
	w.had[key(fd.FullName(), st)] = true
	return true
}

func (w *wireSample) unnamed() {
	w.had[unnamedNumber] = true
}

// wireScalar is scalar's value as the wire layer has it, by the proto's kind. unnamed is told
// of an enum's number that its enum has no name for.
func wireScalar(fd protoreflect.FieldDescriptor, s seed, unnamed func()) protoreflect.Value {
	switch fd.Kind() {
	case protoreflect.StringKind:
		return protoreflect.ValueOfString(s.text())
	case protoreflect.BytesKind:
		return protoreflect.ValueOfBytes([]byte(s.text()))
	case protoreflect.BoolKind:
		return protoreflect.ValueOfBool(true)
	case protoreflect.EnumKind:
		if fd.Enum().Values().ByNumber(protoreflect.EnumNumber(s.number())) == nil {
			unnamed()
		}
		return protoreflect.ValueOfEnum(protoreflect.EnumNumber(s.number()))
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		return protoreflect.ValueOfInt32(s.number())
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		return protoreflect.ValueOfUint32(uint32(s.wide()) | 1)
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		return protoreflect.ValueOfInt64(int64(s.wide()))
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		return protoreflect.ValueOfUint64(s.wide())
	case protoreflect.FloatKind:
		return protoreflect.ValueOfFloat32(float32(s.number()) + 0.5)
	case protoreflect.DoubleKind:
		return protoreflect.ValueOfFloat64(float64(s.number()) + 0.5)
	}
	panic("no sample of a " + fd.Kind().String())
}

const momentName = "google.protobuf.Timestamp"

func isMoment(fd protoreflect.FieldDescriptor) bool {
	return fd.Message() != nil && fd.Message().FullName() == momentName
}

func wireMoment(s seed) protoreflect.Value {
	return protoreflect.ValueOfMessage(timestamppb.New(s.moment()).ProtoReflect())
}

// optionalOption is the field number of the proto's (optional) option.
const optionalOption = 50002

// isMarked reports whether the proto marks a field (optional): its zero is a value, and is
// sent. The wire layer has no Go type for the option, so it lies among the unknown fields of
// the field's options.
func isMarked(fd protoreflect.FieldDescriptor) bool {
	options := fd.Options().ProtoReflect()
	if !options.IsValid() {
		return false // The field has no option at all.
	}

	raw := options.GetUnknown()
	for len(raw) > 0 {
		number, kind, n := protowire.ConsumeTag(raw)
		raw = raw[n:]
		if number == optionalOption && kind == protowire.VarintType {
			marked, _ := protowire.ConsumeVarint(raw)
			return marked == 1
		}
		raw = raw[protowire.ConsumeFieldValue(number, kind, raw):]
	}
	return false
}

// ── What the samples must have had ─────────────────────────────────────────

func key(name protoreflect.FullName, what any) string {
	return fmt.Sprint(name, " ", what)
}

// unnamedNumber is had once an enum's field took a number its enum has no name for.
const unnamedNumber = "an enum's number without a name"

// needs lists what the samples of a message must have had before its check is done: each
// field of it, and of every message it holds, in each state it can be in; each member of each
// oneof set and zero, and none; a later API's field where one is kept; and an enum's number
// without a name.
func (w *wireSample) needs(md protoreflect.MessageDescriptor, visited map[protoreflect.FullName]bool) []string {
	if visited[md.FullName()] || md.FullName() == momentName {
		return nil
	}
	visited[md.FullName()] = true

	var keys []string
	if !w.sent || w.bothWays[md.FullName()] {
		keys = append(keys, key(md.FullName(), "later"))
	}
	for i := range md.Oneofs().Len() {
		keys = append(keys, key(md.Oneofs().Get(i).FullName(), absent))
	}
	for i := range md.Fields().Len() {
		fd := md.Fields().Get(i)
		states := []state{set, zero, absent}
		switch {
		case fd.ContainingOneof() != nil:
			states = []state{set, zero}
		case isMoment(fd) && !fd.IsList():
			states = []state{set, absent}
		}
		for _, st := range states {
			keys = append(keys, key(fd.FullName(), st))
		}

		if fd.Enum() != nil && hasUnnamed(fd.Enum()) {
			keys = append(keys, unnamedNumber)
		}
		if fd.Message() != nil {
			keys = append(keys, w.needs(fd.Message(), visited)...)
		}
	}
	return keys
}

// hasUnnamed reports whether a sample's number can be one the enum has no name for.
func hasUnnamed(ed protoreflect.EnumDescriptor) bool {
	for n := protoreflect.EnumNumber(1); n <= 50; n++ {
		if ed.Values().ByNumber(n) == nil {
			return true
		}
	}
	return false
}

// lacks are the needs of a message that no sample has had yet.
func (w *wireSample) lacks(of proto.Message) []string {
	var lacks []string
	for _, need := range w.needs(of.ProtoReflect().Descriptor(), map[protoreflect.FullName]bool{}) {
		if !w.had[need] {
			lacks = append(lacks, need)
		}
	}
	return lacks
}
