// @generated by buffa-codegen. DO NOT EDIT.
// source: v1/panel.proto

pub mod run_machine_action_request {
    #[allow(unused_imports)]
    use super::*;
    #[derive(Clone, Debug)]
    pub enum Action<'a> {
        AddSshKey(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::SshKeyView<'a>,
            >,
        ),
        RemoveSshKeyFingerprint(&'a str),
        RestartMachine(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::RestartMachineActionView<'a>,
            >,
        ),
        CancelRestart(bool),
        EndSessionId(&'a str),
    }
}
pub mod project_source {
    #[allow(unused_imports)]
    use super::*;
    #[derive(Clone, Debug)]
    pub enum Kind<'a> {
        Files(bool),
        Github(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::GithubSourceView<'a>,
            >,
        ),
    }
}
pub mod deploy_project_request {
    #[allow(unused_imports)]
    use super::*;
    #[derive(Clone, Debug)]
    pub enum Version<'a> {
        UploadId(&'a str),
        Commit(&'a str),
        NewestCommit(bool),
        RollbackDeployId(&'a str),
    }
}
pub mod file_change {
    #[allow(unused_imports)]
    use super::*;
    #[derive(Clone, Debug)]
    pub enum Change<'a> {
        Text(&'a str),
        Data(&'a [u8]),
        MakeDirectory(bool),
        Delete(bool),
        DeleteTree(bool),
        RenameTo(&'a str),
    }
}
pub mod run_project_action_request {
    #[allow(unused_imports)]
    use super::*;
    #[derive(Clone, Debug)]
    pub enum Action<'a> {
        StartServices(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::ServicesActionView<'a>,
            >,
        ),
        StopServices(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::ServicesActionView<'a>,
            >,
        ),
        RestartServices(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::ServicesActionView<'a>,
            >,
        ),
        RecreateService(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::RecreateServiceActionView<'a>,
            >,
        ),
        BackUp(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::BackUpActionView<'a>,
            >,
        ),
        RestoreSnapshot(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::RestoreSnapshotActionView<'a>,
            >,
        ),
        CancelOperation(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::CancelOperationActionView<'a>,
            >,
        ),
        DeleteProject(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::DeleteProjectActionView<'a>,
            >,
        ),
        SetSource(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::ProjectSourceView<'a>,
            >,
        ),
        DeleteVolume(&'a str),
    }
}
pub mod read_path_request {
    #[allow(unused_imports)]
    use super::*;
    #[derive(Clone, Debug)]
    pub enum Root<'a> {
        Service(&'a str),
        Volume(&'a str),
    }
}
pub mod create_transfer_request {
    #[allow(unused_imports)]
    use super::*;
    #[derive(Clone, Debug)]
    pub enum Transfer<'a> {
        UploadArchive(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::ArchiveUploadView<'a>,
            >,
        ),
        UploadFile(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::FileUploadView<'a>,
            >,
        ),
        Download(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::PathDownloadView<'a>,
            >,
        ),
    }
}
pub mod file_upload {
    #[allow(unused_imports)]
    use super::*;
    #[derive(Clone, Debug)]
    pub enum Root<'a> {
        Service(&'a str),
        Volume(&'a str),
    }
}
pub mod path_download {
    #[allow(unused_imports)]
    use super::*;
    #[derive(Clone, Debug)]
    pub enum Root<'a> {
        Service(&'a str),
        Volume(&'a str),
    }
}
pub mod watch_operation_response {
    #[allow(unused_imports)]
    use super::*;
    #[derive(Clone, Debug)]
    pub enum Message<'a> {
        Log(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::OperationLogLineView<'a>,
            >,
        ),
        FinishedOperation(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::OperationView<'a>,
            >,
        ),
    }
}
